// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dataarchive/proto/dataarchive.proto

package dataarchiveconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	dataarchive "p9e.in/ugcl/dataarchive/api/v1/dataarchive"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DataArchiveServiceName is the fully-qualified name of the DataArchiveService service.
	DataArchiveServiceName = "dataarchive.api.v1.dataarchive.DataArchiveService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DataArchiveServiceCreateRetentionPolicyProcedure is the fully-qualified name of the
	// DataArchiveService's CreateRetentionPolicy RPC.
	DataArchiveServiceCreateRetentionPolicyProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/CreateRetentionPolicy"
	// DataArchiveServiceGetRetentionPolicyProcedure is the fully-qualified name of the
	// DataArchiveService's GetRetentionPolicy RPC.
	DataArchiveServiceGetRetentionPolicyProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetRetentionPolicy"
	// DataArchiveServiceUpdateRetentionPolicyProcedure is the fully-qualified name of the
	// DataArchiveService's UpdateRetentionPolicy RPC.
	DataArchiveServiceUpdateRetentionPolicyProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/UpdateRetentionPolicy"
	// DataArchiveServiceDeleteRetentionPolicyProcedure is the fully-qualified name of the
	// DataArchiveService's DeleteRetentionPolicy RPC.
	DataArchiveServiceDeleteRetentionPolicyProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/DeleteRetentionPolicy"
	// DataArchiveServiceListRetentionPoliciesProcedure is the fully-qualified name of the
	// DataArchiveService's ListRetentionPolicies RPC.
	DataArchiveServiceListRetentionPoliciesProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ListRetentionPolicies"
	// DataArchiveServiceExecuteRetentionPolicyProcedure is the fully-qualified name of the
	// DataArchiveService's ExecuteRetentionPolicy RPC.
	DataArchiveServiceExecuteRetentionPolicyProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ExecuteRetentionPolicy"
	// DataArchiveServiceGetArchivalJobProcedure is the fully-qualified name of the DataArchiveService's
	// GetArchivalJob RPC.
	DataArchiveServiceGetArchivalJobProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetArchivalJob"
	// DataArchiveServiceListArchivalJobsProcedure is the fully-qualified name of the
	// DataArchiveService's ListArchivalJobs RPC.
	DataArchiveServiceListArchivalJobsProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ListArchivalJobs"
	// DataArchiveServiceCancelArchivalJobProcedure is the fully-qualified name of the
	// DataArchiveService's CancelArchivalJob RPC.
	DataArchiveServiceCancelArchivalJobProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/CancelArchivalJob"
	// DataArchiveServiceRetryArchivalJobProcedure is the fully-qualified name of the
	// DataArchiveService's RetryArchivalJob RPC.
	DataArchiveServiceRetryArchivalJobProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/RetryArchivalJob"
	// DataArchiveServiceCreateLegalHoldProcedure is the fully-qualified name of the
	// DataArchiveService's CreateLegalHold RPC.
	DataArchiveServiceCreateLegalHoldProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/CreateLegalHold"
	// DataArchiveServiceGetLegalHoldProcedure is the fully-qualified name of the DataArchiveService's
	// GetLegalHold RPC.
	DataArchiveServiceGetLegalHoldProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetLegalHold"
	// DataArchiveServiceUpdateLegalHoldProcedure is the fully-qualified name of the
	// DataArchiveService's UpdateLegalHold RPC.
	DataArchiveServiceUpdateLegalHoldProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/UpdateLegalHold"
	// DataArchiveServiceDeleteLegalHoldProcedure is the fully-qualified name of the
	// DataArchiveService's DeleteLegalHold RPC.
	DataArchiveServiceDeleteLegalHoldProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/DeleteLegalHold"
	// DataArchiveServiceListLegalHoldsProcedure is the fully-qualified name of the DataArchiveService's
	// ListLegalHolds RPC.
	DataArchiveServiceListLegalHoldsProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ListLegalHolds"
	// DataArchiveServiceCreateDataInventoryProcedure is the fully-qualified name of the
	// DataArchiveService's CreateDataInventory RPC.
	DataArchiveServiceCreateDataInventoryProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/CreateDataInventory"
	// DataArchiveServiceGetDataInventoryProcedure is the fully-qualified name of the
	// DataArchiveService's GetDataInventory RPC.
	DataArchiveServiceGetDataInventoryProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetDataInventory"
	// DataArchiveServiceUpdateDataInventoryProcedure is the fully-qualified name of the
	// DataArchiveService's UpdateDataInventory RPC.
	DataArchiveServiceUpdateDataInventoryProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/UpdateDataInventory"
	// DataArchiveServiceListDataInventoriesProcedure is the fully-qualified name of the
	// DataArchiveService's ListDataInventories RPC.
	DataArchiveServiceListDataInventoriesProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ListDataInventories"
	// DataArchiveServiceScanDataSourcesProcedure is the fully-qualified name of the
	// DataArchiveService's ScanDataSources RPC.
	DataArchiveServiceScanDataSourcesProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ScanDataSources"
	// DataArchiveServiceSearchArchivedDataProcedure is the fully-qualified name of the
	// DataArchiveService's SearchArchivedData RPC.
	DataArchiveServiceSearchArchivedDataProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/SearchArchivedData"
	// DataArchiveServiceRestoreArchivedDataProcedure is the fully-qualified name of the
	// DataArchiveService's RestoreArchivedData RPC.
	DataArchiveServiceRestoreArchivedDataProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/RestoreArchivedData"
	// DataArchiveServiceGetArchivedDataInfoProcedure is the fully-qualified name of the
	// DataArchiveService's GetArchivedDataInfo RPC.
	DataArchiveServiceGetArchivedDataInfoProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetArchivedDataInfo"
	// DataArchiveServiceDeleteArchivedDataProcedure is the fully-qualified name of the
	// DataArchiveService's DeleteArchivedData RPC.
	DataArchiveServiceDeleteArchivedDataProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/DeleteArchivedData"
	// DataArchiveServiceCreateComplianceAuditProcedure is the fully-qualified name of the
	// DataArchiveService's CreateComplianceAudit RPC.
	DataArchiveServiceCreateComplianceAuditProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/CreateComplianceAudit"
	// DataArchiveServiceGetComplianceAuditProcedure is the fully-qualified name of the
	// DataArchiveService's GetComplianceAudit RPC.
	DataArchiveServiceGetComplianceAuditProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetComplianceAudit"
	// DataArchiveServiceListComplianceAuditsProcedure is the fully-qualified name of the
	// DataArchiveService's ListComplianceAudits RPC.
	DataArchiveServiceListComplianceAuditsProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/ListComplianceAudits"
	// DataArchiveServiceGenerateComplianceReportProcedure is the fully-qualified name of the
	// DataArchiveService's GenerateComplianceReport RPC.
	DataArchiveServiceGenerateComplianceReportProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GenerateComplianceReport"
	// DataArchiveServiceGetArchiveMetricsProcedure is the fully-qualified name of the
	// DataArchiveService's GetArchiveMetrics RPC.
	DataArchiveServiceGetArchiveMetricsProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetArchiveMetrics"
	// DataArchiveServiceGetStorageSavingsProcedure is the fully-qualified name of the
	// DataArchiveService's GetStorageSavings RPC.
	DataArchiveServiceGetStorageSavingsProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetStorageSavings"
	// DataArchiveServiceGetRetentionDashboardProcedure is the fully-qualified name of the
	// DataArchiveService's GetRetentionDashboard RPC.
	DataArchiveServiceGetRetentionDashboardProcedure = "/dataarchive.api.v1.dataarchive.DataArchiveService/GetRetentionDashboard"
)

// DataArchiveServiceClient is a client for the dataarchive.api.v1.dataarchive.DataArchiveService
// service.
type DataArchiveServiceClient interface {
	// Retention Policy Management
	CreateRetentionPolicy(context.Context, *connect.Request[dataarchive.CreateRetentionPolicyRequest]) (*connect.Response[dataarchive.CreateRetentionPolicyResponse], error)
	GetRetentionPolicy(context.Context, *connect.Request[dataarchive.GetRetentionPolicyRequest]) (*connect.Response[dataarchive.GetRetentionPolicyResponse], error)
	UpdateRetentionPolicy(context.Context, *connect.Request[dataarchive.UpdateRetentionPolicyRequest]) (*connect.Response[dataarchive.UpdateRetentionPolicyResponse], error)
	DeleteRetentionPolicy(context.Context, *connect.Request[dataarchive.DeleteRetentionPolicyRequest]) (*connect.Response[emptypb.Empty], error)
	ListRetentionPolicies(context.Context, *connect.Request[dataarchive.ListRetentionPoliciesRequest]) (*connect.Response[dataarchive.ListRetentionPoliciesResponse], error)
	ExecuteRetentionPolicy(context.Context, *connect.Request[dataarchive.ExecuteRetentionPolicyRequest]) (*connect.Response[dataarchive.ExecuteRetentionPolicyResponse], error)
	// Archival Job Management
	GetArchivalJob(context.Context, *connect.Request[dataarchive.GetArchivalJobRequest]) (*connect.Response[dataarchive.GetArchivalJobResponse], error)
	ListArchivalJobs(context.Context, *connect.Request[dataarchive.ListArchivalJobsRequest]) (*connect.Response[dataarchive.ListArchivalJobsResponse], error)
	CancelArchivalJob(context.Context, *connect.Request[dataarchive.CancelArchivalJobRequest]) (*connect.Response[emptypb.Empty], error)
	RetryArchivalJob(context.Context, *connect.Request[dataarchive.RetryArchivalJobRequest]) (*connect.Response[dataarchive.RetryArchivalJobResponse], error)
	// Legal Hold Management
	CreateLegalHold(context.Context, *connect.Request[dataarchive.CreateLegalHoldRequest]) (*connect.Response[dataarchive.CreateLegalHoldResponse], error)
	GetLegalHold(context.Context, *connect.Request[dataarchive.GetLegalHoldRequest]) (*connect.Response[dataarchive.GetLegalHoldResponse], error)
	UpdateLegalHold(context.Context, *connect.Request[dataarchive.UpdateLegalHoldRequest]) (*connect.Response[dataarchive.UpdateLegalHoldResponse], error)
	DeleteLegalHold(context.Context, *connect.Request[dataarchive.DeleteLegalHoldRequest]) (*connect.Response[emptypb.Empty], error)
	ListLegalHolds(context.Context, *connect.Request[dataarchive.ListLegalHoldsRequest]) (*connect.Response[dataarchive.ListLegalHoldsResponse], error)
	// Data Inventory Management
	CreateDataInventory(context.Context, *connect.Request[dataarchive.CreateDataInventoryRequest]) (*connect.Response[dataarchive.CreateDataInventoryResponse], error)
	GetDataInventory(context.Context, *connect.Request[dataarchive.GetDataInventoryRequest]) (*connect.Response[dataarchive.GetDataInventoryResponse], error)
	UpdateDataInventory(context.Context, *connect.Request[dataarchive.UpdateDataInventoryRequest]) (*connect.Response[dataarchive.UpdateDataInventoryResponse], error)
	ListDataInventories(context.Context, *connect.Request[dataarchive.ListDataInventoriesRequest]) (*connect.Response[dataarchive.ListDataInventoriesResponse], error)
	ScanDataSources(context.Context, *connect.Request[dataarchive.ScanDataSourcesRequest]) (*connect.Response[dataarchive.ScanDataSourcesResponse], error)
	// Archived Data Management
	SearchArchivedData(context.Context, *connect.Request[dataarchive.SearchArchivedDataRequest]) (*connect.Response[dataarchive.SearchArchivedDataResponse], error)
	RestoreArchivedData(context.Context, *connect.Request[dataarchive.RestoreArchivedDataRequest]) (*connect.Response[dataarchive.RestoreArchivedDataResponse], error)
	GetArchivedDataInfo(context.Context, *connect.Request[dataarchive.GetArchivedDataInfoRequest]) (*connect.Response[dataarchive.GetArchivedDataInfoResponse], error)
	DeleteArchivedData(context.Context, *connect.Request[dataarchive.DeleteArchivedDataRequest]) (*connect.Response[emptypb.Empty], error)
	// Compliance and Auditing
	CreateComplianceAudit(context.Context, *connect.Request[dataarchive.CreateComplianceAuditRequest]) (*connect.Response[dataarchive.CreateComplianceAuditResponse], error)
	GetComplianceAudit(context.Context, *connect.Request[dataarchive.GetComplianceAuditRequest]) (*connect.Response[dataarchive.GetComplianceAuditResponse], error)
	ListComplianceAudits(context.Context, *connect.Request[dataarchive.ListComplianceAuditsRequest]) (*connect.Response[dataarchive.ListComplianceAuditsResponse], error)
	GenerateComplianceReport(context.Context, *connect.Request[dataarchive.GenerateComplianceReportRequest]) (*connect.Response[dataarchive.GenerateComplianceReportResponse], error)
	// Analytics and Reporting
	GetArchiveMetrics(context.Context, *connect.Request[dataarchive.GetArchiveMetricsRequest]) (*connect.Response[dataarchive.GetArchiveMetricsResponse], error)
	GetStorageSavings(context.Context, *connect.Request[dataarchive.GetStorageSavingsRequest]) (*connect.Response[dataarchive.GetStorageSavingsResponse], error)
	GetRetentionDashboard(context.Context, *connect.Request[dataarchive.GetRetentionDashboardRequest]) (*connect.Response[dataarchive.GetRetentionDashboardResponse], error)
}

// NewDataArchiveServiceClient constructs a client for the
// dataarchive.api.v1.dataarchive.DataArchiveService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDataArchiveServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DataArchiveServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dataArchiveServiceMethods := dataarchive.File_dataarchive_proto_dataarchive_proto.Services().ByName("DataArchiveService").Methods()
	return &dataArchiveServiceClient{
		createRetentionPolicy: connect.NewClient[dataarchive.CreateRetentionPolicyRequest, dataarchive.CreateRetentionPolicyResponse](
			httpClient,
			baseURL+DataArchiveServiceCreateRetentionPolicyProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("CreateRetentionPolicy")),
			connect.WithClientOptions(opts...),
		),
		getRetentionPolicy: connect.NewClient[dataarchive.GetRetentionPolicyRequest, dataarchive.GetRetentionPolicyResponse](
			httpClient,
			baseURL+DataArchiveServiceGetRetentionPolicyProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetRetentionPolicy")),
			connect.WithClientOptions(opts...),
		),
		updateRetentionPolicy: connect.NewClient[dataarchive.UpdateRetentionPolicyRequest, dataarchive.UpdateRetentionPolicyResponse](
			httpClient,
			baseURL+DataArchiveServiceUpdateRetentionPolicyProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("UpdateRetentionPolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteRetentionPolicy: connect.NewClient[dataarchive.DeleteRetentionPolicyRequest, emptypb.Empty](
			httpClient,
			baseURL+DataArchiveServiceDeleteRetentionPolicyProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("DeleteRetentionPolicy")),
			connect.WithClientOptions(opts...),
		),
		listRetentionPolicies: connect.NewClient[dataarchive.ListRetentionPoliciesRequest, dataarchive.ListRetentionPoliciesResponse](
			httpClient,
			baseURL+DataArchiveServiceListRetentionPoliciesProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ListRetentionPolicies")),
			connect.WithClientOptions(opts...),
		),
		executeRetentionPolicy: connect.NewClient[dataarchive.ExecuteRetentionPolicyRequest, dataarchive.ExecuteRetentionPolicyResponse](
			httpClient,
			baseURL+DataArchiveServiceExecuteRetentionPolicyProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ExecuteRetentionPolicy")),
			connect.WithClientOptions(opts...),
		),
		getArchivalJob: connect.NewClient[dataarchive.GetArchivalJobRequest, dataarchive.GetArchivalJobResponse](
			httpClient,
			baseURL+DataArchiveServiceGetArchivalJobProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetArchivalJob")),
			connect.WithClientOptions(opts...),
		),
		listArchivalJobs: connect.NewClient[dataarchive.ListArchivalJobsRequest, dataarchive.ListArchivalJobsResponse](
			httpClient,
			baseURL+DataArchiveServiceListArchivalJobsProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ListArchivalJobs")),
			connect.WithClientOptions(opts...),
		),
		cancelArchivalJob: connect.NewClient[dataarchive.CancelArchivalJobRequest, emptypb.Empty](
			httpClient,
			baseURL+DataArchiveServiceCancelArchivalJobProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("CancelArchivalJob")),
			connect.WithClientOptions(opts...),
		),
		retryArchivalJob: connect.NewClient[dataarchive.RetryArchivalJobRequest, dataarchive.RetryArchivalJobResponse](
			httpClient,
			baseURL+DataArchiveServiceRetryArchivalJobProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("RetryArchivalJob")),
			connect.WithClientOptions(opts...),
		),
		createLegalHold: connect.NewClient[dataarchive.CreateLegalHoldRequest, dataarchive.CreateLegalHoldResponse](
			httpClient,
			baseURL+DataArchiveServiceCreateLegalHoldProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("CreateLegalHold")),
			connect.WithClientOptions(opts...),
		),
		getLegalHold: connect.NewClient[dataarchive.GetLegalHoldRequest, dataarchive.GetLegalHoldResponse](
			httpClient,
			baseURL+DataArchiveServiceGetLegalHoldProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetLegalHold")),
			connect.WithClientOptions(opts...),
		),
		updateLegalHold: connect.NewClient[dataarchive.UpdateLegalHoldRequest, dataarchive.UpdateLegalHoldResponse](
			httpClient,
			baseURL+DataArchiveServiceUpdateLegalHoldProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("UpdateLegalHold")),
			connect.WithClientOptions(opts...),
		),
		deleteLegalHold: connect.NewClient[dataarchive.DeleteLegalHoldRequest, emptypb.Empty](
			httpClient,
			baseURL+DataArchiveServiceDeleteLegalHoldProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("DeleteLegalHold")),
			connect.WithClientOptions(opts...),
		),
		listLegalHolds: connect.NewClient[dataarchive.ListLegalHoldsRequest, dataarchive.ListLegalHoldsResponse](
			httpClient,
			baseURL+DataArchiveServiceListLegalHoldsProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ListLegalHolds")),
			connect.WithClientOptions(opts...),
		),
		createDataInventory: connect.NewClient[dataarchive.CreateDataInventoryRequest, dataarchive.CreateDataInventoryResponse](
			httpClient,
			baseURL+DataArchiveServiceCreateDataInventoryProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("CreateDataInventory")),
			connect.WithClientOptions(opts...),
		),
		getDataInventory: connect.NewClient[dataarchive.GetDataInventoryRequest, dataarchive.GetDataInventoryResponse](
			httpClient,
			baseURL+DataArchiveServiceGetDataInventoryProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetDataInventory")),
			connect.WithClientOptions(opts...),
		),
		updateDataInventory: connect.NewClient[dataarchive.UpdateDataInventoryRequest, dataarchive.UpdateDataInventoryResponse](
			httpClient,
			baseURL+DataArchiveServiceUpdateDataInventoryProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("UpdateDataInventory")),
			connect.WithClientOptions(opts...),
		),
		listDataInventories: connect.NewClient[dataarchive.ListDataInventoriesRequest, dataarchive.ListDataInventoriesResponse](
			httpClient,
			baseURL+DataArchiveServiceListDataInventoriesProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ListDataInventories")),
			connect.WithClientOptions(opts...),
		),
		scanDataSources: connect.NewClient[dataarchive.ScanDataSourcesRequest, dataarchive.ScanDataSourcesResponse](
			httpClient,
			baseURL+DataArchiveServiceScanDataSourcesProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ScanDataSources")),
			connect.WithClientOptions(opts...),
		),
		searchArchivedData: connect.NewClient[dataarchive.SearchArchivedDataRequest, dataarchive.SearchArchivedDataResponse](
			httpClient,
			baseURL+DataArchiveServiceSearchArchivedDataProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("SearchArchivedData")),
			connect.WithClientOptions(opts...),
		),
		restoreArchivedData: connect.NewClient[dataarchive.RestoreArchivedDataRequest, dataarchive.RestoreArchivedDataResponse](
			httpClient,
			baseURL+DataArchiveServiceRestoreArchivedDataProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("RestoreArchivedData")),
			connect.WithClientOptions(opts...),
		),
		getArchivedDataInfo: connect.NewClient[dataarchive.GetArchivedDataInfoRequest, dataarchive.GetArchivedDataInfoResponse](
			httpClient,
			baseURL+DataArchiveServiceGetArchivedDataInfoProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetArchivedDataInfo")),
			connect.WithClientOptions(opts...),
		),
		deleteArchivedData: connect.NewClient[dataarchive.DeleteArchivedDataRequest, emptypb.Empty](
			httpClient,
			baseURL+DataArchiveServiceDeleteArchivedDataProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("DeleteArchivedData")),
			connect.WithClientOptions(opts...),
		),
		createComplianceAudit: connect.NewClient[dataarchive.CreateComplianceAuditRequest, dataarchive.CreateComplianceAuditResponse](
			httpClient,
			baseURL+DataArchiveServiceCreateComplianceAuditProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("CreateComplianceAudit")),
			connect.WithClientOptions(opts...),
		),
		getComplianceAudit: connect.NewClient[dataarchive.GetComplianceAuditRequest, dataarchive.GetComplianceAuditResponse](
			httpClient,
			baseURL+DataArchiveServiceGetComplianceAuditProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetComplianceAudit")),
			connect.WithClientOptions(opts...),
		),
		listComplianceAudits: connect.NewClient[dataarchive.ListComplianceAuditsRequest, dataarchive.ListComplianceAuditsResponse](
			httpClient,
			baseURL+DataArchiveServiceListComplianceAuditsProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("ListComplianceAudits")),
			connect.WithClientOptions(opts...),
		),
		generateComplianceReport: connect.NewClient[dataarchive.GenerateComplianceReportRequest, dataarchive.GenerateComplianceReportResponse](
			httpClient,
			baseURL+DataArchiveServiceGenerateComplianceReportProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GenerateComplianceReport")),
			connect.WithClientOptions(opts...),
		),
		getArchiveMetrics: connect.NewClient[dataarchive.GetArchiveMetricsRequest, dataarchive.GetArchiveMetricsResponse](
			httpClient,
			baseURL+DataArchiveServiceGetArchiveMetricsProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetArchiveMetrics")),
			connect.WithClientOptions(opts...),
		),
		getStorageSavings: connect.NewClient[dataarchive.GetStorageSavingsRequest, dataarchive.GetStorageSavingsResponse](
			httpClient,
			baseURL+DataArchiveServiceGetStorageSavingsProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetStorageSavings")),
			connect.WithClientOptions(opts...),
		),
		getRetentionDashboard: connect.NewClient[dataarchive.GetRetentionDashboardRequest, dataarchive.GetRetentionDashboardResponse](
			httpClient,
			baseURL+DataArchiveServiceGetRetentionDashboardProcedure,
			connect.WithSchema(dataArchiveServiceMethods.ByName("GetRetentionDashboard")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dataArchiveServiceClient implements DataArchiveServiceClient.
type dataArchiveServiceClient struct {
	createRetentionPolicy    *connect.Client[dataarchive.CreateRetentionPolicyRequest, dataarchive.CreateRetentionPolicyResponse]
	getRetentionPolicy       *connect.Client[dataarchive.GetRetentionPolicyRequest, dataarchive.GetRetentionPolicyResponse]
	updateRetentionPolicy    *connect.Client[dataarchive.UpdateRetentionPolicyRequest, dataarchive.UpdateRetentionPolicyResponse]
	deleteRetentionPolicy    *connect.Client[dataarchive.DeleteRetentionPolicyRequest, emptypb.Empty]
	listRetentionPolicies    *connect.Client[dataarchive.ListRetentionPoliciesRequest, dataarchive.ListRetentionPoliciesResponse]
	executeRetentionPolicy   *connect.Client[dataarchive.ExecuteRetentionPolicyRequest, dataarchive.ExecuteRetentionPolicyResponse]
	getArchivalJob           *connect.Client[dataarchive.GetArchivalJobRequest, dataarchive.GetArchivalJobResponse]
	listArchivalJobs         *connect.Client[dataarchive.ListArchivalJobsRequest, dataarchive.ListArchivalJobsResponse]
	cancelArchivalJob        *connect.Client[dataarchive.CancelArchivalJobRequest, emptypb.Empty]
	retryArchivalJob         *connect.Client[dataarchive.RetryArchivalJobRequest, dataarchive.RetryArchivalJobResponse]
	createLegalHold          *connect.Client[dataarchive.CreateLegalHoldRequest, dataarchive.CreateLegalHoldResponse]
	getLegalHold             *connect.Client[dataarchive.GetLegalHoldRequest, dataarchive.GetLegalHoldResponse]
	updateLegalHold          *connect.Client[dataarchive.UpdateLegalHoldRequest, dataarchive.UpdateLegalHoldResponse]
	deleteLegalHold          *connect.Client[dataarchive.DeleteLegalHoldRequest, emptypb.Empty]
	listLegalHolds           *connect.Client[dataarchive.ListLegalHoldsRequest, dataarchive.ListLegalHoldsResponse]
	createDataInventory      *connect.Client[dataarchive.CreateDataInventoryRequest, dataarchive.CreateDataInventoryResponse]
	getDataInventory         *connect.Client[dataarchive.GetDataInventoryRequest, dataarchive.GetDataInventoryResponse]
	updateDataInventory      *connect.Client[dataarchive.UpdateDataInventoryRequest, dataarchive.UpdateDataInventoryResponse]
	listDataInventories      *connect.Client[dataarchive.ListDataInventoriesRequest, dataarchive.ListDataInventoriesResponse]
	scanDataSources          *connect.Client[dataarchive.ScanDataSourcesRequest, dataarchive.ScanDataSourcesResponse]
	searchArchivedData       *connect.Client[dataarchive.SearchArchivedDataRequest, dataarchive.SearchArchivedDataResponse]
	restoreArchivedData      *connect.Client[dataarchive.RestoreArchivedDataRequest, dataarchive.RestoreArchivedDataResponse]
	getArchivedDataInfo      *connect.Client[dataarchive.GetArchivedDataInfoRequest, dataarchive.GetArchivedDataInfoResponse]
	deleteArchivedData       *connect.Client[dataarchive.DeleteArchivedDataRequest, emptypb.Empty]
	createComplianceAudit    *connect.Client[dataarchive.CreateComplianceAuditRequest, dataarchive.CreateComplianceAuditResponse]
	getComplianceAudit       *connect.Client[dataarchive.GetComplianceAuditRequest, dataarchive.GetComplianceAuditResponse]
	listComplianceAudits     *connect.Client[dataarchive.ListComplianceAuditsRequest, dataarchive.ListComplianceAuditsResponse]
	generateComplianceReport *connect.Client[dataarchive.GenerateComplianceReportRequest, dataarchive.GenerateComplianceReportResponse]
	getArchiveMetrics        *connect.Client[dataarchive.GetArchiveMetricsRequest, dataarchive.GetArchiveMetricsResponse]
	getStorageSavings        *connect.Client[dataarchive.GetStorageSavingsRequest, dataarchive.GetStorageSavingsResponse]
	getRetentionDashboard    *connect.Client[dataarchive.GetRetentionDashboardRequest, dataarchive.GetRetentionDashboardResponse]
}

// CreateRetentionPolicy calls
// dataarchive.api.v1.dataarchive.DataArchiveService.CreateRetentionPolicy.
func (c *dataArchiveServiceClient) CreateRetentionPolicy(ctx context.Context, req *connect.Request[dataarchive.CreateRetentionPolicyRequest]) (*connect.Response[dataarchive.CreateRetentionPolicyResponse], error) {
	return c.createRetentionPolicy.CallUnary(ctx, req)
}

// GetRetentionPolicy calls dataarchive.api.v1.dataarchive.DataArchiveService.GetRetentionPolicy.
func (c *dataArchiveServiceClient) GetRetentionPolicy(ctx context.Context, req *connect.Request[dataarchive.GetRetentionPolicyRequest]) (*connect.Response[dataarchive.GetRetentionPolicyResponse], error) {
	return c.getRetentionPolicy.CallUnary(ctx, req)
}

// UpdateRetentionPolicy calls
// dataarchive.api.v1.dataarchive.DataArchiveService.UpdateRetentionPolicy.
func (c *dataArchiveServiceClient) UpdateRetentionPolicy(ctx context.Context, req *connect.Request[dataarchive.UpdateRetentionPolicyRequest]) (*connect.Response[dataarchive.UpdateRetentionPolicyResponse], error) {
	return c.updateRetentionPolicy.CallUnary(ctx, req)
}

// DeleteRetentionPolicy calls
// dataarchive.api.v1.dataarchive.DataArchiveService.DeleteRetentionPolicy.
func (c *dataArchiveServiceClient) DeleteRetentionPolicy(ctx context.Context, req *connect.Request[dataarchive.DeleteRetentionPolicyRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteRetentionPolicy.CallUnary(ctx, req)
}

// ListRetentionPolicies calls
// dataarchive.api.v1.dataarchive.DataArchiveService.ListRetentionPolicies.
func (c *dataArchiveServiceClient) ListRetentionPolicies(ctx context.Context, req *connect.Request[dataarchive.ListRetentionPoliciesRequest]) (*connect.Response[dataarchive.ListRetentionPoliciesResponse], error) {
	return c.listRetentionPolicies.CallUnary(ctx, req)
}

// ExecuteRetentionPolicy calls
// dataarchive.api.v1.dataarchive.DataArchiveService.ExecuteRetentionPolicy.
func (c *dataArchiveServiceClient) ExecuteRetentionPolicy(ctx context.Context, req *connect.Request[dataarchive.ExecuteRetentionPolicyRequest]) (*connect.Response[dataarchive.ExecuteRetentionPolicyResponse], error) {
	return c.executeRetentionPolicy.CallUnary(ctx, req)
}

// GetArchivalJob calls dataarchive.api.v1.dataarchive.DataArchiveService.GetArchivalJob.
func (c *dataArchiveServiceClient) GetArchivalJob(ctx context.Context, req *connect.Request[dataarchive.GetArchivalJobRequest]) (*connect.Response[dataarchive.GetArchivalJobResponse], error) {
	return c.getArchivalJob.CallUnary(ctx, req)
}

// ListArchivalJobs calls dataarchive.api.v1.dataarchive.DataArchiveService.ListArchivalJobs.
func (c *dataArchiveServiceClient) ListArchivalJobs(ctx context.Context, req *connect.Request[dataarchive.ListArchivalJobsRequest]) (*connect.Response[dataarchive.ListArchivalJobsResponse], error) {
	return c.listArchivalJobs.CallUnary(ctx, req)
}

// CancelArchivalJob calls dataarchive.api.v1.dataarchive.DataArchiveService.CancelArchivalJob.
func (c *dataArchiveServiceClient) CancelArchivalJob(ctx context.Context, req *connect.Request[dataarchive.CancelArchivalJobRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.cancelArchivalJob.CallUnary(ctx, req)
}

// RetryArchivalJob calls dataarchive.api.v1.dataarchive.DataArchiveService.RetryArchivalJob.
func (c *dataArchiveServiceClient) RetryArchivalJob(ctx context.Context, req *connect.Request[dataarchive.RetryArchivalJobRequest]) (*connect.Response[dataarchive.RetryArchivalJobResponse], error) {
	return c.retryArchivalJob.CallUnary(ctx, req)
}

// CreateLegalHold calls dataarchive.api.v1.dataarchive.DataArchiveService.CreateLegalHold.
func (c *dataArchiveServiceClient) CreateLegalHold(ctx context.Context, req *connect.Request[dataarchive.CreateLegalHoldRequest]) (*connect.Response[dataarchive.CreateLegalHoldResponse], error) {
	return c.createLegalHold.CallUnary(ctx, req)
}

// GetLegalHold calls dataarchive.api.v1.dataarchive.DataArchiveService.GetLegalHold.
func (c *dataArchiveServiceClient) GetLegalHold(ctx context.Context, req *connect.Request[dataarchive.GetLegalHoldRequest]) (*connect.Response[dataarchive.GetLegalHoldResponse], error) {
	return c.getLegalHold.CallUnary(ctx, req)
}

// UpdateLegalHold calls dataarchive.api.v1.dataarchive.DataArchiveService.UpdateLegalHold.
func (c *dataArchiveServiceClient) UpdateLegalHold(ctx context.Context, req *connect.Request[dataarchive.UpdateLegalHoldRequest]) (*connect.Response[dataarchive.UpdateLegalHoldResponse], error) {
	return c.updateLegalHold.CallUnary(ctx, req)
}

// DeleteLegalHold calls dataarchive.api.v1.dataarchive.DataArchiveService.DeleteLegalHold.
func (c *dataArchiveServiceClient) DeleteLegalHold(ctx context.Context, req *connect.Request[dataarchive.DeleteLegalHoldRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteLegalHold.CallUnary(ctx, req)
}

// ListLegalHolds calls dataarchive.api.v1.dataarchive.DataArchiveService.ListLegalHolds.
func (c *dataArchiveServiceClient) ListLegalHolds(ctx context.Context, req *connect.Request[dataarchive.ListLegalHoldsRequest]) (*connect.Response[dataarchive.ListLegalHoldsResponse], error) {
	return c.listLegalHolds.CallUnary(ctx, req)
}

// CreateDataInventory calls dataarchive.api.v1.dataarchive.DataArchiveService.CreateDataInventory.
func (c *dataArchiveServiceClient) CreateDataInventory(ctx context.Context, req *connect.Request[dataarchive.CreateDataInventoryRequest]) (*connect.Response[dataarchive.CreateDataInventoryResponse], error) {
	return c.createDataInventory.CallUnary(ctx, req)
}

// GetDataInventory calls dataarchive.api.v1.dataarchive.DataArchiveService.GetDataInventory.
func (c *dataArchiveServiceClient) GetDataInventory(ctx context.Context, req *connect.Request[dataarchive.GetDataInventoryRequest]) (*connect.Response[dataarchive.GetDataInventoryResponse], error) {
	return c.getDataInventory.CallUnary(ctx, req)
}

// UpdateDataInventory calls dataarchive.api.v1.dataarchive.DataArchiveService.UpdateDataInventory.
func (c *dataArchiveServiceClient) UpdateDataInventory(ctx context.Context, req *connect.Request[dataarchive.UpdateDataInventoryRequest]) (*connect.Response[dataarchive.UpdateDataInventoryResponse], error) {
	return c.updateDataInventory.CallUnary(ctx, req)
}

// ListDataInventories calls dataarchive.api.v1.dataarchive.DataArchiveService.ListDataInventories.
func (c *dataArchiveServiceClient) ListDataInventories(ctx context.Context, req *connect.Request[dataarchive.ListDataInventoriesRequest]) (*connect.Response[dataarchive.ListDataInventoriesResponse], error) {
	return c.listDataInventories.CallUnary(ctx, req)
}

// ScanDataSources calls dataarchive.api.v1.dataarchive.DataArchiveService.ScanDataSources.
func (c *dataArchiveServiceClient) ScanDataSources(ctx context.Context, req *connect.Request[dataarchive.ScanDataSourcesRequest]) (*connect.Response[dataarchive.ScanDataSourcesResponse], error) {
	return c.scanDataSources.CallUnary(ctx, req)
}

// SearchArchivedData calls dataarchive.api.v1.dataarchive.DataArchiveService.SearchArchivedData.
func (c *dataArchiveServiceClient) SearchArchivedData(ctx context.Context, req *connect.Request[dataarchive.SearchArchivedDataRequest]) (*connect.Response[dataarchive.SearchArchivedDataResponse], error) {
	return c.searchArchivedData.CallUnary(ctx, req)
}

// RestoreArchivedData calls dataarchive.api.v1.dataarchive.DataArchiveService.RestoreArchivedData.
func (c *dataArchiveServiceClient) RestoreArchivedData(ctx context.Context, req *connect.Request[dataarchive.RestoreArchivedDataRequest]) (*connect.Response[dataarchive.RestoreArchivedDataResponse], error) {
	return c.restoreArchivedData.CallUnary(ctx, req)
}

// GetArchivedDataInfo calls dataarchive.api.v1.dataarchive.DataArchiveService.GetArchivedDataInfo.
func (c *dataArchiveServiceClient) GetArchivedDataInfo(ctx context.Context, req *connect.Request[dataarchive.GetArchivedDataInfoRequest]) (*connect.Response[dataarchive.GetArchivedDataInfoResponse], error) {
	return c.getArchivedDataInfo.CallUnary(ctx, req)
}

// DeleteArchivedData calls dataarchive.api.v1.dataarchive.DataArchiveService.DeleteArchivedData.
func (c *dataArchiveServiceClient) DeleteArchivedData(ctx context.Context, req *connect.Request[dataarchive.DeleteArchivedDataRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteArchivedData.CallUnary(ctx, req)
}

// CreateComplianceAudit calls
// dataarchive.api.v1.dataarchive.DataArchiveService.CreateComplianceAudit.
func (c *dataArchiveServiceClient) CreateComplianceAudit(ctx context.Context, req *connect.Request[dataarchive.CreateComplianceAuditRequest]) (*connect.Response[dataarchive.CreateComplianceAuditResponse], error) {
	return c.createComplianceAudit.CallUnary(ctx, req)
}

// GetComplianceAudit calls dataarchive.api.v1.dataarchive.DataArchiveService.GetComplianceAudit.
func (c *dataArchiveServiceClient) GetComplianceAudit(ctx context.Context, req *connect.Request[dataarchive.GetComplianceAuditRequest]) (*connect.Response[dataarchive.GetComplianceAuditResponse], error) {
	return c.getComplianceAudit.CallUnary(ctx, req)
}

// ListComplianceAudits calls
// dataarchive.api.v1.dataarchive.DataArchiveService.ListComplianceAudits.
func (c *dataArchiveServiceClient) ListComplianceAudits(ctx context.Context, req *connect.Request[dataarchive.ListComplianceAuditsRequest]) (*connect.Response[dataarchive.ListComplianceAuditsResponse], error) {
	return c.listComplianceAudits.CallUnary(ctx, req)
}

// GenerateComplianceReport calls
// dataarchive.api.v1.dataarchive.DataArchiveService.GenerateComplianceReport.
func (c *dataArchiveServiceClient) GenerateComplianceReport(ctx context.Context, req *connect.Request[dataarchive.GenerateComplianceReportRequest]) (*connect.Response[dataarchive.GenerateComplianceReportResponse], error) {
	return c.generateComplianceReport.CallUnary(ctx, req)
}

// GetArchiveMetrics calls dataarchive.api.v1.dataarchive.DataArchiveService.GetArchiveMetrics.
func (c *dataArchiveServiceClient) GetArchiveMetrics(ctx context.Context, req *connect.Request[dataarchive.GetArchiveMetricsRequest]) (*connect.Response[dataarchive.GetArchiveMetricsResponse], error) {
	return c.getArchiveMetrics.CallUnary(ctx, req)
}

// GetStorageSavings calls dataarchive.api.v1.dataarchive.DataArchiveService.GetStorageSavings.
func (c *dataArchiveServiceClient) GetStorageSavings(ctx context.Context, req *connect.Request[dataarchive.GetStorageSavingsRequest]) (*connect.Response[dataarchive.GetStorageSavingsResponse], error) {
	return c.getStorageSavings.CallUnary(ctx, req)
}

// GetRetentionDashboard calls
// dataarchive.api.v1.dataarchive.DataArchiveService.GetRetentionDashboard.
func (c *dataArchiveServiceClient) GetRetentionDashboard(ctx context.Context, req *connect.Request[dataarchive.GetRetentionDashboardRequest]) (*connect.Response[dataarchive.GetRetentionDashboardResponse], error) {
	return c.getRetentionDashboard.CallUnary(ctx, req)
}

// DataArchiveServiceHandler is an implementation of the
// dataarchive.api.v1.dataarchive.DataArchiveService service.
type DataArchiveServiceHandler interface {
	// Retention Policy Management
	CreateRetentionPolicy(context.Context, *connect.Request[dataarchive.CreateRetentionPolicyRequest]) (*connect.Response[dataarchive.CreateRetentionPolicyResponse], error)
	GetRetentionPolicy(context.Context, *connect.Request[dataarchive.GetRetentionPolicyRequest]) (*connect.Response[dataarchive.GetRetentionPolicyResponse], error)
	UpdateRetentionPolicy(context.Context, *connect.Request[dataarchive.UpdateRetentionPolicyRequest]) (*connect.Response[dataarchive.UpdateRetentionPolicyResponse], error)
	DeleteRetentionPolicy(context.Context, *connect.Request[dataarchive.DeleteRetentionPolicyRequest]) (*connect.Response[emptypb.Empty], error)
	ListRetentionPolicies(context.Context, *connect.Request[dataarchive.ListRetentionPoliciesRequest]) (*connect.Response[dataarchive.ListRetentionPoliciesResponse], error)
	ExecuteRetentionPolicy(context.Context, *connect.Request[dataarchive.ExecuteRetentionPolicyRequest]) (*connect.Response[dataarchive.ExecuteRetentionPolicyResponse], error)
	// Archival Job Management
	GetArchivalJob(context.Context, *connect.Request[dataarchive.GetArchivalJobRequest]) (*connect.Response[dataarchive.GetArchivalJobResponse], error)
	ListArchivalJobs(context.Context, *connect.Request[dataarchive.ListArchivalJobsRequest]) (*connect.Response[dataarchive.ListArchivalJobsResponse], error)
	CancelArchivalJob(context.Context, *connect.Request[dataarchive.CancelArchivalJobRequest]) (*connect.Response[emptypb.Empty], error)
	RetryArchivalJob(context.Context, *connect.Request[dataarchive.RetryArchivalJobRequest]) (*connect.Response[dataarchive.RetryArchivalJobResponse], error)
	// Legal Hold Management
	CreateLegalHold(context.Context, *connect.Request[dataarchive.CreateLegalHoldRequest]) (*connect.Response[dataarchive.CreateLegalHoldResponse], error)
	GetLegalHold(context.Context, *connect.Request[dataarchive.GetLegalHoldRequest]) (*connect.Response[dataarchive.GetLegalHoldResponse], error)
	UpdateLegalHold(context.Context, *connect.Request[dataarchive.UpdateLegalHoldRequest]) (*connect.Response[dataarchive.UpdateLegalHoldResponse], error)
	DeleteLegalHold(context.Context, *connect.Request[dataarchive.DeleteLegalHoldRequest]) (*connect.Response[emptypb.Empty], error)
	ListLegalHolds(context.Context, *connect.Request[dataarchive.ListLegalHoldsRequest]) (*connect.Response[dataarchive.ListLegalHoldsResponse], error)
	// Data Inventory Management
	CreateDataInventory(context.Context, *connect.Request[dataarchive.CreateDataInventoryRequest]) (*connect.Response[dataarchive.CreateDataInventoryResponse], error)
	GetDataInventory(context.Context, *connect.Request[dataarchive.GetDataInventoryRequest]) (*connect.Response[dataarchive.GetDataInventoryResponse], error)
	UpdateDataInventory(context.Context, *connect.Request[dataarchive.UpdateDataInventoryRequest]) (*connect.Response[dataarchive.UpdateDataInventoryResponse], error)
	ListDataInventories(context.Context, *connect.Request[dataarchive.ListDataInventoriesRequest]) (*connect.Response[dataarchive.ListDataInventoriesResponse], error)
	ScanDataSources(context.Context, *connect.Request[dataarchive.ScanDataSourcesRequest]) (*connect.Response[dataarchive.ScanDataSourcesResponse], error)
	// Archived Data Management
	SearchArchivedData(context.Context, *connect.Request[dataarchive.SearchArchivedDataRequest]) (*connect.Response[dataarchive.SearchArchivedDataResponse], error)
	RestoreArchivedData(context.Context, *connect.Request[dataarchive.RestoreArchivedDataRequest]) (*connect.Response[dataarchive.RestoreArchivedDataResponse], error)
	GetArchivedDataInfo(context.Context, *connect.Request[dataarchive.GetArchivedDataInfoRequest]) (*connect.Response[dataarchive.GetArchivedDataInfoResponse], error)
	DeleteArchivedData(context.Context, *connect.Request[dataarchive.DeleteArchivedDataRequest]) (*connect.Response[emptypb.Empty], error)
	// Compliance and Auditing
	CreateComplianceAudit(context.Context, *connect.Request[dataarchive.CreateComplianceAuditRequest]) (*connect.Response[dataarchive.CreateComplianceAuditResponse], error)
	GetComplianceAudit(context.Context, *connect.Request[dataarchive.GetComplianceAuditRequest]) (*connect.Response[dataarchive.GetComplianceAuditResponse], error)
	ListComplianceAudits(context.Context, *connect.Request[dataarchive.ListComplianceAuditsRequest]) (*connect.Response[dataarchive.ListComplianceAuditsResponse], error)
	GenerateComplianceReport(context.Context, *connect.Request[dataarchive.GenerateComplianceReportRequest]) (*connect.Response[dataarchive.GenerateComplianceReportResponse], error)
	// Analytics and Reporting
	GetArchiveMetrics(context.Context, *connect.Request[dataarchive.GetArchiveMetricsRequest]) (*connect.Response[dataarchive.GetArchiveMetricsResponse], error)
	GetStorageSavings(context.Context, *connect.Request[dataarchive.GetStorageSavingsRequest]) (*connect.Response[dataarchive.GetStorageSavingsResponse], error)
	GetRetentionDashboard(context.Context, *connect.Request[dataarchive.GetRetentionDashboardRequest]) (*connect.Response[dataarchive.GetRetentionDashboardResponse], error)
}

// NewDataArchiveServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDataArchiveServiceHandler(svc DataArchiveServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dataArchiveServiceMethods := dataarchive.File_dataarchive_proto_dataarchive_proto.Services().ByName("DataArchiveService").Methods()
	dataArchiveServiceCreateRetentionPolicyHandler := connect.NewUnaryHandler(
		DataArchiveServiceCreateRetentionPolicyProcedure,
		svc.CreateRetentionPolicy,
		connect.WithSchema(dataArchiveServiceMethods.ByName("CreateRetentionPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetRetentionPolicyHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetRetentionPolicyProcedure,
		svc.GetRetentionPolicy,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetRetentionPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceUpdateRetentionPolicyHandler := connect.NewUnaryHandler(
		DataArchiveServiceUpdateRetentionPolicyProcedure,
		svc.UpdateRetentionPolicy,
		connect.WithSchema(dataArchiveServiceMethods.ByName("UpdateRetentionPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceDeleteRetentionPolicyHandler := connect.NewUnaryHandler(
		DataArchiveServiceDeleteRetentionPolicyProcedure,
		svc.DeleteRetentionPolicy,
		connect.WithSchema(dataArchiveServiceMethods.ByName("DeleteRetentionPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceListRetentionPoliciesHandler := connect.NewUnaryHandler(
		DataArchiveServiceListRetentionPoliciesProcedure,
		svc.ListRetentionPolicies,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ListRetentionPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceExecuteRetentionPolicyHandler := connect.NewUnaryHandler(
		DataArchiveServiceExecuteRetentionPolicyProcedure,
		svc.ExecuteRetentionPolicy,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ExecuteRetentionPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetArchivalJobHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetArchivalJobProcedure,
		svc.GetArchivalJob,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetArchivalJob")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceListArchivalJobsHandler := connect.NewUnaryHandler(
		DataArchiveServiceListArchivalJobsProcedure,
		svc.ListArchivalJobs,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ListArchivalJobs")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceCancelArchivalJobHandler := connect.NewUnaryHandler(
		DataArchiveServiceCancelArchivalJobProcedure,
		svc.CancelArchivalJob,
		connect.WithSchema(dataArchiveServiceMethods.ByName("CancelArchivalJob")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceRetryArchivalJobHandler := connect.NewUnaryHandler(
		DataArchiveServiceRetryArchivalJobProcedure,
		svc.RetryArchivalJob,
		connect.WithSchema(dataArchiveServiceMethods.ByName("RetryArchivalJob")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceCreateLegalHoldHandler := connect.NewUnaryHandler(
		DataArchiveServiceCreateLegalHoldProcedure,
		svc.CreateLegalHold,
		connect.WithSchema(dataArchiveServiceMethods.ByName("CreateLegalHold")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetLegalHoldHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetLegalHoldProcedure,
		svc.GetLegalHold,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetLegalHold")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceUpdateLegalHoldHandler := connect.NewUnaryHandler(
		DataArchiveServiceUpdateLegalHoldProcedure,
		svc.UpdateLegalHold,
		connect.WithSchema(dataArchiveServiceMethods.ByName("UpdateLegalHold")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceDeleteLegalHoldHandler := connect.NewUnaryHandler(
		DataArchiveServiceDeleteLegalHoldProcedure,
		svc.DeleteLegalHold,
		connect.WithSchema(dataArchiveServiceMethods.ByName("DeleteLegalHold")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceListLegalHoldsHandler := connect.NewUnaryHandler(
		DataArchiveServiceListLegalHoldsProcedure,
		svc.ListLegalHolds,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ListLegalHolds")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceCreateDataInventoryHandler := connect.NewUnaryHandler(
		DataArchiveServiceCreateDataInventoryProcedure,
		svc.CreateDataInventory,
		connect.WithSchema(dataArchiveServiceMethods.ByName("CreateDataInventory")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetDataInventoryHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetDataInventoryProcedure,
		svc.GetDataInventory,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetDataInventory")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceUpdateDataInventoryHandler := connect.NewUnaryHandler(
		DataArchiveServiceUpdateDataInventoryProcedure,
		svc.UpdateDataInventory,
		connect.WithSchema(dataArchiveServiceMethods.ByName("UpdateDataInventory")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceListDataInventoriesHandler := connect.NewUnaryHandler(
		DataArchiveServiceListDataInventoriesProcedure,
		svc.ListDataInventories,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ListDataInventories")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceScanDataSourcesHandler := connect.NewUnaryHandler(
		DataArchiveServiceScanDataSourcesProcedure,
		svc.ScanDataSources,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ScanDataSources")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceSearchArchivedDataHandler := connect.NewUnaryHandler(
		DataArchiveServiceSearchArchivedDataProcedure,
		svc.SearchArchivedData,
		connect.WithSchema(dataArchiveServiceMethods.ByName("SearchArchivedData")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceRestoreArchivedDataHandler := connect.NewUnaryHandler(
		DataArchiveServiceRestoreArchivedDataProcedure,
		svc.RestoreArchivedData,
		connect.WithSchema(dataArchiveServiceMethods.ByName("RestoreArchivedData")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetArchivedDataInfoHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetArchivedDataInfoProcedure,
		svc.GetArchivedDataInfo,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetArchivedDataInfo")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceDeleteArchivedDataHandler := connect.NewUnaryHandler(
		DataArchiveServiceDeleteArchivedDataProcedure,
		svc.DeleteArchivedData,
		connect.WithSchema(dataArchiveServiceMethods.ByName("DeleteArchivedData")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceCreateComplianceAuditHandler := connect.NewUnaryHandler(
		DataArchiveServiceCreateComplianceAuditProcedure,
		svc.CreateComplianceAudit,
		connect.WithSchema(dataArchiveServiceMethods.ByName("CreateComplianceAudit")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetComplianceAuditHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetComplianceAuditProcedure,
		svc.GetComplianceAudit,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetComplianceAudit")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceListComplianceAuditsHandler := connect.NewUnaryHandler(
		DataArchiveServiceListComplianceAuditsProcedure,
		svc.ListComplianceAudits,
		connect.WithSchema(dataArchiveServiceMethods.ByName("ListComplianceAudits")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGenerateComplianceReportHandler := connect.NewUnaryHandler(
		DataArchiveServiceGenerateComplianceReportProcedure,
		svc.GenerateComplianceReport,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GenerateComplianceReport")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetArchiveMetricsHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetArchiveMetricsProcedure,
		svc.GetArchiveMetrics,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetArchiveMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetStorageSavingsHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetStorageSavingsProcedure,
		svc.GetStorageSavings,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetStorageSavings")),
		connect.WithHandlerOptions(opts...),
	)
	dataArchiveServiceGetRetentionDashboardHandler := connect.NewUnaryHandler(
		DataArchiveServiceGetRetentionDashboardProcedure,
		svc.GetRetentionDashboard,
		connect.WithSchema(dataArchiveServiceMethods.ByName("GetRetentionDashboard")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dataarchive.api.v1.dataarchive.DataArchiveService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DataArchiveServiceCreateRetentionPolicyProcedure:
			dataArchiveServiceCreateRetentionPolicyHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetRetentionPolicyProcedure:
			dataArchiveServiceGetRetentionPolicyHandler.ServeHTTP(w, r)
		case DataArchiveServiceUpdateRetentionPolicyProcedure:
			dataArchiveServiceUpdateRetentionPolicyHandler.ServeHTTP(w, r)
		case DataArchiveServiceDeleteRetentionPolicyProcedure:
			dataArchiveServiceDeleteRetentionPolicyHandler.ServeHTTP(w, r)
		case DataArchiveServiceListRetentionPoliciesProcedure:
			dataArchiveServiceListRetentionPoliciesHandler.ServeHTTP(w, r)
		case DataArchiveServiceExecuteRetentionPolicyProcedure:
			dataArchiveServiceExecuteRetentionPolicyHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetArchivalJobProcedure:
			dataArchiveServiceGetArchivalJobHandler.ServeHTTP(w, r)
		case DataArchiveServiceListArchivalJobsProcedure:
			dataArchiveServiceListArchivalJobsHandler.ServeHTTP(w, r)
		case DataArchiveServiceCancelArchivalJobProcedure:
			dataArchiveServiceCancelArchivalJobHandler.ServeHTTP(w, r)
		case DataArchiveServiceRetryArchivalJobProcedure:
			dataArchiveServiceRetryArchivalJobHandler.ServeHTTP(w, r)
		case DataArchiveServiceCreateLegalHoldProcedure:
			dataArchiveServiceCreateLegalHoldHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetLegalHoldProcedure:
			dataArchiveServiceGetLegalHoldHandler.ServeHTTP(w, r)
		case DataArchiveServiceUpdateLegalHoldProcedure:
			dataArchiveServiceUpdateLegalHoldHandler.ServeHTTP(w, r)
		case DataArchiveServiceDeleteLegalHoldProcedure:
			dataArchiveServiceDeleteLegalHoldHandler.ServeHTTP(w, r)
		case DataArchiveServiceListLegalHoldsProcedure:
			dataArchiveServiceListLegalHoldsHandler.ServeHTTP(w, r)
		case DataArchiveServiceCreateDataInventoryProcedure:
			dataArchiveServiceCreateDataInventoryHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetDataInventoryProcedure:
			dataArchiveServiceGetDataInventoryHandler.ServeHTTP(w, r)
		case DataArchiveServiceUpdateDataInventoryProcedure:
			dataArchiveServiceUpdateDataInventoryHandler.ServeHTTP(w, r)
		case DataArchiveServiceListDataInventoriesProcedure:
			dataArchiveServiceListDataInventoriesHandler.ServeHTTP(w, r)
		case DataArchiveServiceScanDataSourcesProcedure:
			dataArchiveServiceScanDataSourcesHandler.ServeHTTP(w, r)
		case DataArchiveServiceSearchArchivedDataProcedure:
			dataArchiveServiceSearchArchivedDataHandler.ServeHTTP(w, r)
		case DataArchiveServiceRestoreArchivedDataProcedure:
			dataArchiveServiceRestoreArchivedDataHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetArchivedDataInfoProcedure:
			dataArchiveServiceGetArchivedDataInfoHandler.ServeHTTP(w, r)
		case DataArchiveServiceDeleteArchivedDataProcedure:
			dataArchiveServiceDeleteArchivedDataHandler.ServeHTTP(w, r)
		case DataArchiveServiceCreateComplianceAuditProcedure:
			dataArchiveServiceCreateComplianceAuditHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetComplianceAuditProcedure:
			dataArchiveServiceGetComplianceAuditHandler.ServeHTTP(w, r)
		case DataArchiveServiceListComplianceAuditsProcedure:
			dataArchiveServiceListComplianceAuditsHandler.ServeHTTP(w, r)
		case DataArchiveServiceGenerateComplianceReportProcedure:
			dataArchiveServiceGenerateComplianceReportHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetArchiveMetricsProcedure:
			dataArchiveServiceGetArchiveMetricsHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetStorageSavingsProcedure:
			dataArchiveServiceGetStorageSavingsHandler.ServeHTTP(w, r)
		case DataArchiveServiceGetRetentionDashboardProcedure:
			dataArchiveServiceGetRetentionDashboardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDataArchiveServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDataArchiveServiceHandler struct{}

func (UnimplementedDataArchiveServiceHandler) CreateRetentionPolicy(context.Context, *connect.Request[dataarchive.CreateRetentionPolicyRequest]) (*connect.Response[dataarchive.CreateRetentionPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.CreateRetentionPolicy is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetRetentionPolicy(context.Context, *connect.Request[dataarchive.GetRetentionPolicyRequest]) (*connect.Response[dataarchive.GetRetentionPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetRetentionPolicy is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) UpdateRetentionPolicy(context.Context, *connect.Request[dataarchive.UpdateRetentionPolicyRequest]) (*connect.Response[dataarchive.UpdateRetentionPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.UpdateRetentionPolicy is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) DeleteRetentionPolicy(context.Context, *connect.Request[dataarchive.DeleteRetentionPolicyRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.DeleteRetentionPolicy is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ListRetentionPolicies(context.Context, *connect.Request[dataarchive.ListRetentionPoliciesRequest]) (*connect.Response[dataarchive.ListRetentionPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ListRetentionPolicies is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ExecuteRetentionPolicy(context.Context, *connect.Request[dataarchive.ExecuteRetentionPolicyRequest]) (*connect.Response[dataarchive.ExecuteRetentionPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ExecuteRetentionPolicy is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetArchivalJob(context.Context, *connect.Request[dataarchive.GetArchivalJobRequest]) (*connect.Response[dataarchive.GetArchivalJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetArchivalJob is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ListArchivalJobs(context.Context, *connect.Request[dataarchive.ListArchivalJobsRequest]) (*connect.Response[dataarchive.ListArchivalJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ListArchivalJobs is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) CancelArchivalJob(context.Context, *connect.Request[dataarchive.CancelArchivalJobRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.CancelArchivalJob is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) RetryArchivalJob(context.Context, *connect.Request[dataarchive.RetryArchivalJobRequest]) (*connect.Response[dataarchive.RetryArchivalJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.RetryArchivalJob is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) CreateLegalHold(context.Context, *connect.Request[dataarchive.CreateLegalHoldRequest]) (*connect.Response[dataarchive.CreateLegalHoldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.CreateLegalHold is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetLegalHold(context.Context, *connect.Request[dataarchive.GetLegalHoldRequest]) (*connect.Response[dataarchive.GetLegalHoldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetLegalHold is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) UpdateLegalHold(context.Context, *connect.Request[dataarchive.UpdateLegalHoldRequest]) (*connect.Response[dataarchive.UpdateLegalHoldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.UpdateLegalHold is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) DeleteLegalHold(context.Context, *connect.Request[dataarchive.DeleteLegalHoldRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.DeleteLegalHold is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ListLegalHolds(context.Context, *connect.Request[dataarchive.ListLegalHoldsRequest]) (*connect.Response[dataarchive.ListLegalHoldsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ListLegalHolds is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) CreateDataInventory(context.Context, *connect.Request[dataarchive.CreateDataInventoryRequest]) (*connect.Response[dataarchive.CreateDataInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.CreateDataInventory is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetDataInventory(context.Context, *connect.Request[dataarchive.GetDataInventoryRequest]) (*connect.Response[dataarchive.GetDataInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetDataInventory is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) UpdateDataInventory(context.Context, *connect.Request[dataarchive.UpdateDataInventoryRequest]) (*connect.Response[dataarchive.UpdateDataInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.UpdateDataInventory is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ListDataInventories(context.Context, *connect.Request[dataarchive.ListDataInventoriesRequest]) (*connect.Response[dataarchive.ListDataInventoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ListDataInventories is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ScanDataSources(context.Context, *connect.Request[dataarchive.ScanDataSourcesRequest]) (*connect.Response[dataarchive.ScanDataSourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ScanDataSources is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) SearchArchivedData(context.Context, *connect.Request[dataarchive.SearchArchivedDataRequest]) (*connect.Response[dataarchive.SearchArchivedDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.SearchArchivedData is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) RestoreArchivedData(context.Context, *connect.Request[dataarchive.RestoreArchivedDataRequest]) (*connect.Response[dataarchive.RestoreArchivedDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.RestoreArchivedData is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetArchivedDataInfo(context.Context, *connect.Request[dataarchive.GetArchivedDataInfoRequest]) (*connect.Response[dataarchive.GetArchivedDataInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetArchivedDataInfo is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) DeleteArchivedData(context.Context, *connect.Request[dataarchive.DeleteArchivedDataRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.DeleteArchivedData is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) CreateComplianceAudit(context.Context, *connect.Request[dataarchive.CreateComplianceAuditRequest]) (*connect.Response[dataarchive.CreateComplianceAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.CreateComplianceAudit is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetComplianceAudit(context.Context, *connect.Request[dataarchive.GetComplianceAuditRequest]) (*connect.Response[dataarchive.GetComplianceAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetComplianceAudit is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) ListComplianceAudits(context.Context, *connect.Request[dataarchive.ListComplianceAuditsRequest]) (*connect.Response[dataarchive.ListComplianceAuditsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.ListComplianceAudits is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GenerateComplianceReport(context.Context, *connect.Request[dataarchive.GenerateComplianceReportRequest]) (*connect.Response[dataarchive.GenerateComplianceReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GenerateComplianceReport is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetArchiveMetrics(context.Context, *connect.Request[dataarchive.GetArchiveMetricsRequest]) (*connect.Response[dataarchive.GetArchiveMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetArchiveMetrics is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetStorageSavings(context.Context, *connect.Request[dataarchive.GetStorageSavingsRequest]) (*connect.Response[dataarchive.GetStorageSavingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetStorageSavings is not implemented"))
}

func (UnimplementedDataArchiveServiceHandler) GetRetentionDashboard(context.Context, *connect.Request[dataarchive.GetRetentionDashboardRequest]) (*connect.Response[dataarchive.GetRetentionDashboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dataarchive.api.v1.dataarchive.DataArchiveService.GetRetentionDashboard is not implemented"))
}
