// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/proto/permission.proto

package permissionconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	permission "p9e.in/ugcl/identity/api/v2/permission"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PermissionServiceName is the fully-qualified name of the PermissionService service.
	PermissionServiceName = "user.api.v2.permission.PermissionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PermissionServiceGrantProcedure is the fully-qualified name of the PermissionService's Grant RPC.
	PermissionServiceGrantProcedure = "/user.api.v2.permission.PermissionService/Grant"
	// PermissionServiceRevokeProcedure is the fully-qualified name of the PermissionService's Revoke
	// RPC.
	PermissionServiceRevokeProcedure = "/user.api.v2.permission.PermissionService/Revoke"
	// PermissionServiceCheckProcedure is the fully-qualified name of the PermissionService's Check RPC.
	PermissionServiceCheckProcedure = "/user.api.v2.permission.PermissionService/Check"
	// PermissionServiceGetPermissionsProcedure is the fully-qualified name of the PermissionService's
	// GetPermissions RPC.
	PermissionServiceGetPermissionsProcedure = "/user.api.v2.permission.PermissionService/GetPermissions"
	// PermissionServiceListPermissionsByRoleProcedure is the fully-qualified name of the
	// PermissionService's ListPermissionsByRole RPC.
	PermissionServiceListPermissionsByRoleProcedure = "/user.api.v2.permission.PermissionService/ListPermissionsByRole"
	// PermissionServiceListPermissionsByUserProcedure is the fully-qualified name of the
	// PermissionService's ListPermissionsByUser RPC.
	PermissionServiceListPermissionsByUserProcedure = "/user.api.v2.permission.PermissionService/ListPermissionsByUser"
)

// PermissionServiceClient is a client for the user.api.v2.permission.PermissionService service.
type PermissionServiceClient interface {
	Grant(context.Context, *connect.Request[permission.Permission]) (*connect.Response[emptypb.Empty], error)
	Revoke(context.Context, *connect.Request[permission.RevokePermissionRequest]) (*connect.Response[emptypb.Empty], error)
	Check(context.Context, *connect.Request[permission.CheckPermissionRequest]) (*connect.Response[permission.CheckPermissionResponse], error)
	GetPermissions(context.Context, *connect.Request[permission.ListPermissionsRequest]) (*connect.Response[permission.ListPermissionsResponse], error)
	ListPermissionsByRole(context.Context, *connect.Request[permission.RoleIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error)
	ListPermissionsByUser(context.Context, *connect.Request[permission.UserIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error)
}

// NewPermissionServiceClient constructs a client for the user.api.v2.permission.PermissionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPermissionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PermissionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	permissionServiceMethods := permission.File_identity_proto_permission_proto.Services().ByName("PermissionService").Methods()
	return &permissionServiceClient{
		grant: connect.NewClient[permission.Permission, emptypb.Empty](
			httpClient,
			baseURL+PermissionServiceGrantProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("Grant")),
			connect.WithClientOptions(opts...),
		),
		revoke: connect.NewClient[permission.RevokePermissionRequest, emptypb.Empty](
			httpClient,
			baseURL+PermissionServiceRevokeProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("Revoke")),
			connect.WithClientOptions(opts...),
		),
		check: connect.NewClient[permission.CheckPermissionRequest, permission.CheckPermissionResponse](
			httpClient,
			baseURL+PermissionServiceCheckProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("Check")),
			connect.WithClientOptions(opts...),
		),
		getPermissions: connect.NewClient[permission.ListPermissionsRequest, permission.ListPermissionsResponse](
			httpClient,
			baseURL+PermissionServiceGetPermissionsProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("GetPermissions")),
			connect.WithClientOptions(opts...),
		),
		listPermissionsByRole: connect.NewClient[permission.RoleIdentifier, permission.ListPermissionsResponse](
			httpClient,
			baseURL+PermissionServiceListPermissionsByRoleProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("ListPermissionsByRole")),
			connect.WithClientOptions(opts...),
		),
		listPermissionsByUser: connect.NewClient[permission.UserIdentifier, permission.ListPermissionsResponse](
			httpClient,
			baseURL+PermissionServiceListPermissionsByUserProcedure,
			connect.WithSchema(permissionServiceMethods.ByName("ListPermissionsByUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// permissionServiceClient implements PermissionServiceClient.
type permissionServiceClient struct {
	grant                 *connect.Client[permission.Permission, emptypb.Empty]
	revoke                *connect.Client[permission.RevokePermissionRequest, emptypb.Empty]
	check                 *connect.Client[permission.CheckPermissionRequest, permission.CheckPermissionResponse]
	getPermissions        *connect.Client[permission.ListPermissionsRequest, permission.ListPermissionsResponse]
	listPermissionsByRole *connect.Client[permission.RoleIdentifier, permission.ListPermissionsResponse]
	listPermissionsByUser *connect.Client[permission.UserIdentifier, permission.ListPermissionsResponse]
}

// Grant calls user.api.v2.permission.PermissionService.Grant.
func (c *permissionServiceClient) Grant(ctx context.Context, req *connect.Request[permission.Permission]) (*connect.Response[emptypb.Empty], error) {
	return c.grant.CallUnary(ctx, req)
}

// Revoke calls user.api.v2.permission.PermissionService.Revoke.
func (c *permissionServiceClient) Revoke(ctx context.Context, req *connect.Request[permission.RevokePermissionRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revoke.CallUnary(ctx, req)
}

// Check calls user.api.v2.permission.PermissionService.Check.
func (c *permissionServiceClient) Check(ctx context.Context, req *connect.Request[permission.CheckPermissionRequest]) (*connect.Response[permission.CheckPermissionResponse], error) {
	return c.check.CallUnary(ctx, req)
}

// GetPermissions calls user.api.v2.permission.PermissionService.GetPermissions.
func (c *permissionServiceClient) GetPermissions(ctx context.Context, req *connect.Request[permission.ListPermissionsRequest]) (*connect.Response[permission.ListPermissionsResponse], error) {
	return c.getPermissions.CallUnary(ctx, req)
}

// ListPermissionsByRole calls user.api.v2.permission.PermissionService.ListPermissionsByRole.
func (c *permissionServiceClient) ListPermissionsByRole(ctx context.Context, req *connect.Request[permission.RoleIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error) {
	return c.listPermissionsByRole.CallUnary(ctx, req)
}

// ListPermissionsByUser calls user.api.v2.permission.PermissionService.ListPermissionsByUser.
func (c *permissionServiceClient) ListPermissionsByUser(ctx context.Context, req *connect.Request[permission.UserIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error) {
	return c.listPermissionsByUser.CallUnary(ctx, req)
}

// PermissionServiceHandler is an implementation of the user.api.v2.permission.PermissionService
// service.
type PermissionServiceHandler interface {
	Grant(context.Context, *connect.Request[permission.Permission]) (*connect.Response[emptypb.Empty], error)
	Revoke(context.Context, *connect.Request[permission.RevokePermissionRequest]) (*connect.Response[emptypb.Empty], error)
	Check(context.Context, *connect.Request[permission.CheckPermissionRequest]) (*connect.Response[permission.CheckPermissionResponse], error)
	GetPermissions(context.Context, *connect.Request[permission.ListPermissionsRequest]) (*connect.Response[permission.ListPermissionsResponse], error)
	ListPermissionsByRole(context.Context, *connect.Request[permission.RoleIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error)
	ListPermissionsByUser(context.Context, *connect.Request[permission.UserIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error)
}

// NewPermissionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPermissionServiceHandler(svc PermissionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	permissionServiceMethods := permission.File_identity_proto_permission_proto.Services().ByName("PermissionService").Methods()
	permissionServiceGrantHandler := connect.NewUnaryHandler(
		PermissionServiceGrantProcedure,
		svc.Grant,
		connect.WithSchema(permissionServiceMethods.ByName("Grant")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceRevokeHandler := connect.NewUnaryHandler(
		PermissionServiceRevokeProcedure,
		svc.Revoke,
		connect.WithSchema(permissionServiceMethods.ByName("Revoke")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceCheckHandler := connect.NewUnaryHandler(
		PermissionServiceCheckProcedure,
		svc.Check,
		connect.WithSchema(permissionServiceMethods.ByName("Check")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceGetPermissionsHandler := connect.NewUnaryHandler(
		PermissionServiceGetPermissionsProcedure,
		svc.GetPermissions,
		connect.WithSchema(permissionServiceMethods.ByName("GetPermissions")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceListPermissionsByRoleHandler := connect.NewUnaryHandler(
		PermissionServiceListPermissionsByRoleProcedure,
		svc.ListPermissionsByRole,
		connect.WithSchema(permissionServiceMethods.ByName("ListPermissionsByRole")),
		connect.WithHandlerOptions(opts...),
	)
	permissionServiceListPermissionsByUserHandler := connect.NewUnaryHandler(
		PermissionServiceListPermissionsByUserProcedure,
		svc.ListPermissionsByUser,
		connect.WithSchema(permissionServiceMethods.ByName("ListPermissionsByUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.api.v2.permission.PermissionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PermissionServiceGrantProcedure:
			permissionServiceGrantHandler.ServeHTTP(w, r)
		case PermissionServiceRevokeProcedure:
			permissionServiceRevokeHandler.ServeHTTP(w, r)
		case PermissionServiceCheckProcedure:
			permissionServiceCheckHandler.ServeHTTP(w, r)
		case PermissionServiceGetPermissionsProcedure:
			permissionServiceGetPermissionsHandler.ServeHTTP(w, r)
		case PermissionServiceListPermissionsByRoleProcedure:
			permissionServiceListPermissionsByRoleHandler.ServeHTTP(w, r)
		case PermissionServiceListPermissionsByUserProcedure:
			permissionServiceListPermissionsByUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPermissionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPermissionServiceHandler struct{}

func (UnimplementedPermissionServiceHandler) Grant(context.Context, *connect.Request[permission.Permission]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.permission.PermissionService.Grant is not implemented"))
}

func (UnimplementedPermissionServiceHandler) Revoke(context.Context, *connect.Request[permission.RevokePermissionRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.permission.PermissionService.Revoke is not implemented"))
}

func (UnimplementedPermissionServiceHandler) Check(context.Context, *connect.Request[permission.CheckPermissionRequest]) (*connect.Response[permission.CheckPermissionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.permission.PermissionService.Check is not implemented"))
}

func (UnimplementedPermissionServiceHandler) GetPermissions(context.Context, *connect.Request[permission.ListPermissionsRequest]) (*connect.Response[permission.ListPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.permission.PermissionService.GetPermissions is not implemented"))
}

func (UnimplementedPermissionServiceHandler) ListPermissionsByRole(context.Context, *connect.Request[permission.RoleIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.permission.PermissionService.ListPermissionsByRole is not implemented"))
}

func (UnimplementedPermissionServiceHandler) ListPermissionsByUser(context.Context, *connect.Request[permission.UserIdentifier]) (*connect.Response[permission.ListPermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.permission.PermissionService.ListPermissionsByUser is not implemented"))
}
