// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scheduler/proto/scheduler.proto

package schedulerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	scheduler "p9e.in/ugcl/scheduler/api/v1/scheduler"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SchedulerServiceName is the fully-qualified name of the SchedulerService service.
	SchedulerServiceName = "scheduler.api.v1.scheduler.SchedulerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SchedulerServiceCreateJobProcedure is the fully-qualified name of the SchedulerService's
	// CreateJob RPC.
	SchedulerServiceCreateJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/CreateJob"
	// SchedulerServiceGetJobProcedure is the fully-qualified name of the SchedulerService's GetJob RPC.
	SchedulerServiceGetJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/GetJob"
	// SchedulerServiceUpdateJobProcedure is the fully-qualified name of the SchedulerService's
	// UpdateJob RPC.
	SchedulerServiceUpdateJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/UpdateJob"
	// SchedulerServiceDeleteJobProcedure is the fully-qualified name of the SchedulerService's
	// DeleteJob RPC.
	SchedulerServiceDeleteJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/DeleteJob"
	// SchedulerServiceListJobsProcedure is the fully-qualified name of the SchedulerService's ListJobs
	// RPC.
	SchedulerServiceListJobsProcedure = "/scheduler.api.v1.scheduler.SchedulerService/ListJobs"
	// SchedulerServiceEnableJobProcedure is the fully-qualified name of the SchedulerService's
	// EnableJob RPC.
	SchedulerServiceEnableJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/EnableJob"
	// SchedulerServiceDisableJobProcedure is the fully-qualified name of the SchedulerService's
	// DisableJob RPC.
	SchedulerServiceDisableJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/DisableJob"
	// SchedulerServiceTriggerJobProcedure is the fully-qualified name of the SchedulerService's
	// TriggerJob RPC.
	SchedulerServiceTriggerJobProcedure = "/scheduler.api.v1.scheduler.SchedulerService/TriggerJob"
	// SchedulerServiceGetJobExecutionsProcedure is the fully-qualified name of the SchedulerService's
	// GetJobExecutions RPC.
	SchedulerServiceGetJobExecutionsProcedure = "/scheduler.api.v1.scheduler.SchedulerService/GetJobExecutions"
	// SchedulerServiceGetJobExecutionProcedure is the fully-qualified name of the SchedulerService's
	// GetJobExecution RPC.
	SchedulerServiceGetJobExecutionProcedure = "/scheduler.api.v1.scheduler.SchedulerService/GetJobExecution"
	// SchedulerServiceCancelJobExecutionProcedure is the fully-qualified name of the SchedulerService's
	// CancelJobExecution RPC.
	SchedulerServiceCancelJobExecutionProcedure = "/scheduler.api.v1.scheduler.SchedulerService/CancelJobExecution"
	// SchedulerServiceGetSchedulerHealthProcedure is the fully-qualified name of the SchedulerService's
	// GetSchedulerHealth RPC.
	SchedulerServiceGetSchedulerHealthProcedure = "/scheduler.api.v1.scheduler.SchedulerService/GetSchedulerHealth"
	// SchedulerServiceGetJobStatisticsProcedure is the fully-qualified name of the SchedulerService's
	// GetJobStatistics RPC.
	SchedulerServiceGetJobStatisticsProcedure = "/scheduler.api.v1.scheduler.SchedulerService/GetJobStatistics"
)

// SchedulerServiceClient is a client for the scheduler.api.v1.scheduler.SchedulerService service.
type SchedulerServiceClient interface {
	// Job Management
	CreateJob(context.Context, *connect.Request[scheduler.CreateJobRequest]) (*connect.Response[scheduler.CreateJobResponse], error)
	GetJob(context.Context, *connect.Request[scheduler.GetJobRequest]) (*connect.Response[scheduler.GetJobResponse], error)
	UpdateJob(context.Context, *connect.Request[scheduler.UpdateJobRequest]) (*connect.Response[scheduler.UpdateJobResponse], error)
	DeleteJob(context.Context, *connect.Request[scheduler.DeleteJobRequest]) (*connect.Response[scheduler.DeleteJobResponse], error)
	ListJobs(context.Context, *connect.Request[scheduler.ListJobsRequest]) (*connect.Response[scheduler.ListJobsResponse], error)
	// Job Control
	EnableJob(context.Context, *connect.Request[scheduler.EnableJobRequest]) (*connect.Response[scheduler.EnableJobResponse], error)
	DisableJob(context.Context, *connect.Request[scheduler.DisableJobRequest]) (*connect.Response[scheduler.DisableJobResponse], error)
	TriggerJob(context.Context, *connect.Request[scheduler.TriggerJobRequest]) (*connect.Response[scheduler.TriggerJobResponse], error)
	// Execution Monitoring
	GetJobExecutions(context.Context, *connect.Request[scheduler.GetJobExecutionsRequest]) (*connect.Response[scheduler.GetJobExecutionsResponse], error)
	GetJobExecution(context.Context, *connect.Request[scheduler.GetJobExecutionRequest]) (*connect.Response[scheduler.GetJobExecutionResponse], error)
	CancelJobExecution(context.Context, *connect.Request[scheduler.CancelJobExecutionRequest]) (*connect.Response[scheduler.CancelJobExecutionResponse], error)
	// Health and Status
	GetSchedulerHealth(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[scheduler.GetSchedulerHealthResponse], error)
	GetJobStatistics(context.Context, *connect.Request[scheduler.GetJobStatisticsRequest]) (*connect.Response[scheduler.GetJobStatisticsResponse], error)
}

// NewSchedulerServiceClient constructs a client for the scheduler.api.v1.scheduler.SchedulerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSchedulerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SchedulerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	schedulerServiceMethods := scheduler.File_scheduler_proto_scheduler_proto.Services().ByName("SchedulerService").Methods()
	return &schedulerServiceClient{
		createJob: connect.NewClient[scheduler.CreateJobRequest, scheduler.CreateJobResponse](
			httpClient,
			baseURL+SchedulerServiceCreateJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("CreateJob")),
			connect.WithClientOptions(opts...),
		),
		getJob: connect.NewClient[scheduler.GetJobRequest, scheduler.GetJobResponse](
			httpClient,
			baseURL+SchedulerServiceGetJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("GetJob")),
			connect.WithClientOptions(opts...),
		),
		updateJob: connect.NewClient[scheduler.UpdateJobRequest, scheduler.UpdateJobResponse](
			httpClient,
			baseURL+SchedulerServiceUpdateJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("UpdateJob")),
			connect.WithClientOptions(opts...),
		),
		deleteJob: connect.NewClient[scheduler.DeleteJobRequest, scheduler.DeleteJobResponse](
			httpClient,
			baseURL+SchedulerServiceDeleteJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("DeleteJob")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[scheduler.ListJobsRequest, scheduler.ListJobsResponse](
			httpClient,
			baseURL+SchedulerServiceListJobsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		enableJob: connect.NewClient[scheduler.EnableJobRequest, scheduler.EnableJobResponse](
			httpClient,
			baseURL+SchedulerServiceEnableJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("EnableJob")),
			connect.WithClientOptions(opts...),
		),
		disableJob: connect.NewClient[scheduler.DisableJobRequest, scheduler.DisableJobResponse](
			httpClient,
			baseURL+SchedulerServiceDisableJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("DisableJob")),
			connect.WithClientOptions(opts...),
		),
		triggerJob: connect.NewClient[scheduler.TriggerJobRequest, scheduler.TriggerJobResponse](
			httpClient,
			baseURL+SchedulerServiceTriggerJobProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("TriggerJob")),
			connect.WithClientOptions(opts...),
		),
		getJobExecutions: connect.NewClient[scheduler.GetJobExecutionsRequest, scheduler.GetJobExecutionsResponse](
			httpClient,
			baseURL+SchedulerServiceGetJobExecutionsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("GetJobExecutions")),
			connect.WithClientOptions(opts...),
		),
		getJobExecution: connect.NewClient[scheduler.GetJobExecutionRequest, scheduler.GetJobExecutionResponse](
			httpClient,
			baseURL+SchedulerServiceGetJobExecutionProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("GetJobExecution")),
			connect.WithClientOptions(opts...),
		),
		cancelJobExecution: connect.NewClient[scheduler.CancelJobExecutionRequest, scheduler.CancelJobExecutionResponse](
			httpClient,
			baseURL+SchedulerServiceCancelJobExecutionProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("CancelJobExecution")),
			connect.WithClientOptions(opts...),
		),
		getSchedulerHealth: connect.NewClient[emptypb.Empty, scheduler.GetSchedulerHealthResponse](
			httpClient,
			baseURL+SchedulerServiceGetSchedulerHealthProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("GetSchedulerHealth")),
			connect.WithClientOptions(opts...),
		),
		getJobStatistics: connect.NewClient[scheduler.GetJobStatisticsRequest, scheduler.GetJobStatisticsResponse](
			httpClient,
			baseURL+SchedulerServiceGetJobStatisticsProcedure,
			connect.WithSchema(schedulerServiceMethods.ByName("GetJobStatistics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// schedulerServiceClient implements SchedulerServiceClient.
type schedulerServiceClient struct {
	createJob          *connect.Client[scheduler.CreateJobRequest, scheduler.CreateJobResponse]
	getJob             *connect.Client[scheduler.GetJobRequest, scheduler.GetJobResponse]
	updateJob          *connect.Client[scheduler.UpdateJobRequest, scheduler.UpdateJobResponse]
	deleteJob          *connect.Client[scheduler.DeleteJobRequest, scheduler.DeleteJobResponse]
	listJobs           *connect.Client[scheduler.ListJobsRequest, scheduler.ListJobsResponse]
	enableJob          *connect.Client[scheduler.EnableJobRequest, scheduler.EnableJobResponse]
	disableJob         *connect.Client[scheduler.DisableJobRequest, scheduler.DisableJobResponse]
	triggerJob         *connect.Client[scheduler.TriggerJobRequest, scheduler.TriggerJobResponse]
	getJobExecutions   *connect.Client[scheduler.GetJobExecutionsRequest, scheduler.GetJobExecutionsResponse]
	getJobExecution    *connect.Client[scheduler.GetJobExecutionRequest, scheduler.GetJobExecutionResponse]
	cancelJobExecution *connect.Client[scheduler.CancelJobExecutionRequest, scheduler.CancelJobExecutionResponse]
	getSchedulerHealth *connect.Client[emptypb.Empty, scheduler.GetSchedulerHealthResponse]
	getJobStatistics   *connect.Client[scheduler.GetJobStatisticsRequest, scheduler.GetJobStatisticsResponse]
}

// CreateJob calls scheduler.api.v1.scheduler.SchedulerService.CreateJob.
func (c *schedulerServiceClient) CreateJob(ctx context.Context, req *connect.Request[scheduler.CreateJobRequest]) (*connect.Response[scheduler.CreateJobResponse], error) {
	return c.createJob.CallUnary(ctx, req)
}

// GetJob calls scheduler.api.v1.scheduler.SchedulerService.GetJob.
func (c *schedulerServiceClient) GetJob(ctx context.Context, req *connect.Request[scheduler.GetJobRequest]) (*connect.Response[scheduler.GetJobResponse], error) {
	return c.getJob.CallUnary(ctx, req)
}

// UpdateJob calls scheduler.api.v1.scheduler.SchedulerService.UpdateJob.
func (c *schedulerServiceClient) UpdateJob(ctx context.Context, req *connect.Request[scheduler.UpdateJobRequest]) (*connect.Response[scheduler.UpdateJobResponse], error) {
	return c.updateJob.CallUnary(ctx, req)
}

// DeleteJob calls scheduler.api.v1.scheduler.SchedulerService.DeleteJob.
func (c *schedulerServiceClient) DeleteJob(ctx context.Context, req *connect.Request[scheduler.DeleteJobRequest]) (*connect.Response[scheduler.DeleteJobResponse], error) {
	return c.deleteJob.CallUnary(ctx, req)
}

// ListJobs calls scheduler.api.v1.scheduler.SchedulerService.ListJobs.
func (c *schedulerServiceClient) ListJobs(ctx context.Context, req *connect.Request[scheduler.ListJobsRequest]) (*connect.Response[scheduler.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// EnableJob calls scheduler.api.v1.scheduler.SchedulerService.EnableJob.
func (c *schedulerServiceClient) EnableJob(ctx context.Context, req *connect.Request[scheduler.EnableJobRequest]) (*connect.Response[scheduler.EnableJobResponse], error) {
	return c.enableJob.CallUnary(ctx, req)
}

// DisableJob calls scheduler.api.v1.scheduler.SchedulerService.DisableJob.
func (c *schedulerServiceClient) DisableJob(ctx context.Context, req *connect.Request[scheduler.DisableJobRequest]) (*connect.Response[scheduler.DisableJobResponse], error) {
	return c.disableJob.CallUnary(ctx, req)
}

// TriggerJob calls scheduler.api.v1.scheduler.SchedulerService.TriggerJob.
func (c *schedulerServiceClient) TriggerJob(ctx context.Context, req *connect.Request[scheduler.TriggerJobRequest]) (*connect.Response[scheduler.TriggerJobResponse], error) {
	return c.triggerJob.CallUnary(ctx, req)
}

// GetJobExecutions calls scheduler.api.v1.scheduler.SchedulerService.GetJobExecutions.
func (c *schedulerServiceClient) GetJobExecutions(ctx context.Context, req *connect.Request[scheduler.GetJobExecutionsRequest]) (*connect.Response[scheduler.GetJobExecutionsResponse], error) {
	return c.getJobExecutions.CallUnary(ctx, req)
}

// GetJobExecution calls scheduler.api.v1.scheduler.SchedulerService.GetJobExecution.
func (c *schedulerServiceClient) GetJobExecution(ctx context.Context, req *connect.Request[scheduler.GetJobExecutionRequest]) (*connect.Response[scheduler.GetJobExecutionResponse], error) {
	return c.getJobExecution.CallUnary(ctx, req)
}

// CancelJobExecution calls scheduler.api.v1.scheduler.SchedulerService.CancelJobExecution.
func (c *schedulerServiceClient) CancelJobExecution(ctx context.Context, req *connect.Request[scheduler.CancelJobExecutionRequest]) (*connect.Response[scheduler.CancelJobExecutionResponse], error) {
	return c.cancelJobExecution.CallUnary(ctx, req)
}

// GetSchedulerHealth calls scheduler.api.v1.scheduler.SchedulerService.GetSchedulerHealth.
func (c *schedulerServiceClient) GetSchedulerHealth(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[scheduler.GetSchedulerHealthResponse], error) {
	return c.getSchedulerHealth.CallUnary(ctx, req)
}

// GetJobStatistics calls scheduler.api.v1.scheduler.SchedulerService.GetJobStatistics.
func (c *schedulerServiceClient) GetJobStatistics(ctx context.Context, req *connect.Request[scheduler.GetJobStatisticsRequest]) (*connect.Response[scheduler.GetJobStatisticsResponse], error) {
	return c.getJobStatistics.CallUnary(ctx, req)
}

// SchedulerServiceHandler is an implementation of the scheduler.api.v1.scheduler.SchedulerService
// service.
type SchedulerServiceHandler interface {
	// Job Management
	CreateJob(context.Context, *connect.Request[scheduler.CreateJobRequest]) (*connect.Response[scheduler.CreateJobResponse], error)
	GetJob(context.Context, *connect.Request[scheduler.GetJobRequest]) (*connect.Response[scheduler.GetJobResponse], error)
	UpdateJob(context.Context, *connect.Request[scheduler.UpdateJobRequest]) (*connect.Response[scheduler.UpdateJobResponse], error)
	DeleteJob(context.Context, *connect.Request[scheduler.DeleteJobRequest]) (*connect.Response[scheduler.DeleteJobResponse], error)
	ListJobs(context.Context, *connect.Request[scheduler.ListJobsRequest]) (*connect.Response[scheduler.ListJobsResponse], error)
	// Job Control
	EnableJob(context.Context, *connect.Request[scheduler.EnableJobRequest]) (*connect.Response[scheduler.EnableJobResponse], error)
	DisableJob(context.Context, *connect.Request[scheduler.DisableJobRequest]) (*connect.Response[scheduler.DisableJobResponse], error)
	TriggerJob(context.Context, *connect.Request[scheduler.TriggerJobRequest]) (*connect.Response[scheduler.TriggerJobResponse], error)
	// Execution Monitoring
	GetJobExecutions(context.Context, *connect.Request[scheduler.GetJobExecutionsRequest]) (*connect.Response[scheduler.GetJobExecutionsResponse], error)
	GetJobExecution(context.Context, *connect.Request[scheduler.GetJobExecutionRequest]) (*connect.Response[scheduler.GetJobExecutionResponse], error)
	CancelJobExecution(context.Context, *connect.Request[scheduler.CancelJobExecutionRequest]) (*connect.Response[scheduler.CancelJobExecutionResponse], error)
	// Health and Status
	GetSchedulerHealth(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[scheduler.GetSchedulerHealthResponse], error)
	GetJobStatistics(context.Context, *connect.Request[scheduler.GetJobStatisticsRequest]) (*connect.Response[scheduler.GetJobStatisticsResponse], error)
}

// NewSchedulerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSchedulerServiceHandler(svc SchedulerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	schedulerServiceMethods := scheduler.File_scheduler_proto_scheduler_proto.Services().ByName("SchedulerService").Methods()
	schedulerServiceCreateJobHandler := connect.NewUnaryHandler(
		SchedulerServiceCreateJobProcedure,
		svc.CreateJob,
		connect.WithSchema(schedulerServiceMethods.ByName("CreateJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceGetJobHandler := connect.NewUnaryHandler(
		SchedulerServiceGetJobProcedure,
		svc.GetJob,
		connect.WithSchema(schedulerServiceMethods.ByName("GetJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceUpdateJobHandler := connect.NewUnaryHandler(
		SchedulerServiceUpdateJobProcedure,
		svc.UpdateJob,
		connect.WithSchema(schedulerServiceMethods.ByName("UpdateJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceDeleteJobHandler := connect.NewUnaryHandler(
		SchedulerServiceDeleteJobProcedure,
		svc.DeleteJob,
		connect.WithSchema(schedulerServiceMethods.ByName("DeleteJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceListJobsHandler := connect.NewUnaryHandler(
		SchedulerServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(schedulerServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceEnableJobHandler := connect.NewUnaryHandler(
		SchedulerServiceEnableJobProcedure,
		svc.EnableJob,
		connect.WithSchema(schedulerServiceMethods.ByName("EnableJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceDisableJobHandler := connect.NewUnaryHandler(
		SchedulerServiceDisableJobProcedure,
		svc.DisableJob,
		connect.WithSchema(schedulerServiceMethods.ByName("DisableJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceTriggerJobHandler := connect.NewUnaryHandler(
		SchedulerServiceTriggerJobProcedure,
		svc.TriggerJob,
		connect.WithSchema(schedulerServiceMethods.ByName("TriggerJob")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceGetJobExecutionsHandler := connect.NewUnaryHandler(
		SchedulerServiceGetJobExecutionsProcedure,
		svc.GetJobExecutions,
		connect.WithSchema(schedulerServiceMethods.ByName("GetJobExecutions")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceGetJobExecutionHandler := connect.NewUnaryHandler(
		SchedulerServiceGetJobExecutionProcedure,
		svc.GetJobExecution,
		connect.WithSchema(schedulerServiceMethods.ByName("GetJobExecution")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceCancelJobExecutionHandler := connect.NewUnaryHandler(
		SchedulerServiceCancelJobExecutionProcedure,
		svc.CancelJobExecution,
		connect.WithSchema(schedulerServiceMethods.ByName("CancelJobExecution")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceGetSchedulerHealthHandler := connect.NewUnaryHandler(
		SchedulerServiceGetSchedulerHealthProcedure,
		svc.GetSchedulerHealth,
		connect.WithSchema(schedulerServiceMethods.ByName("GetSchedulerHealth")),
		connect.WithHandlerOptions(opts...),
	)
	schedulerServiceGetJobStatisticsHandler := connect.NewUnaryHandler(
		SchedulerServiceGetJobStatisticsProcedure,
		svc.GetJobStatistics,
		connect.WithSchema(schedulerServiceMethods.ByName("GetJobStatistics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scheduler.api.v1.scheduler.SchedulerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SchedulerServiceCreateJobProcedure:
			schedulerServiceCreateJobHandler.ServeHTTP(w, r)
		case SchedulerServiceGetJobProcedure:
			schedulerServiceGetJobHandler.ServeHTTP(w, r)
		case SchedulerServiceUpdateJobProcedure:
			schedulerServiceUpdateJobHandler.ServeHTTP(w, r)
		case SchedulerServiceDeleteJobProcedure:
			schedulerServiceDeleteJobHandler.ServeHTTP(w, r)
		case SchedulerServiceListJobsProcedure:
			schedulerServiceListJobsHandler.ServeHTTP(w, r)
		case SchedulerServiceEnableJobProcedure:
			schedulerServiceEnableJobHandler.ServeHTTP(w, r)
		case SchedulerServiceDisableJobProcedure:
			schedulerServiceDisableJobHandler.ServeHTTP(w, r)
		case SchedulerServiceTriggerJobProcedure:
			schedulerServiceTriggerJobHandler.ServeHTTP(w, r)
		case SchedulerServiceGetJobExecutionsProcedure:
			schedulerServiceGetJobExecutionsHandler.ServeHTTP(w, r)
		case SchedulerServiceGetJobExecutionProcedure:
			schedulerServiceGetJobExecutionHandler.ServeHTTP(w, r)
		case SchedulerServiceCancelJobExecutionProcedure:
			schedulerServiceCancelJobExecutionHandler.ServeHTTP(w, r)
		case SchedulerServiceGetSchedulerHealthProcedure:
			schedulerServiceGetSchedulerHealthHandler.ServeHTTP(w, r)
		case SchedulerServiceGetJobStatisticsProcedure:
			schedulerServiceGetJobStatisticsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSchedulerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSchedulerServiceHandler struct{}

func (UnimplementedSchedulerServiceHandler) CreateJob(context.Context, *connect.Request[scheduler.CreateJobRequest]) (*connect.Response[scheduler.CreateJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.CreateJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) GetJob(context.Context, *connect.Request[scheduler.GetJobRequest]) (*connect.Response[scheduler.GetJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.GetJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) UpdateJob(context.Context, *connect.Request[scheduler.UpdateJobRequest]) (*connect.Response[scheduler.UpdateJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.UpdateJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) DeleteJob(context.Context, *connect.Request[scheduler.DeleteJobRequest]) (*connect.Response[scheduler.DeleteJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.DeleteJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) ListJobs(context.Context, *connect.Request[scheduler.ListJobsRequest]) (*connect.Response[scheduler.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.ListJobs is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) EnableJob(context.Context, *connect.Request[scheduler.EnableJobRequest]) (*connect.Response[scheduler.EnableJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.EnableJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) DisableJob(context.Context, *connect.Request[scheduler.DisableJobRequest]) (*connect.Response[scheduler.DisableJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.DisableJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) TriggerJob(context.Context, *connect.Request[scheduler.TriggerJobRequest]) (*connect.Response[scheduler.TriggerJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.TriggerJob is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) GetJobExecutions(context.Context, *connect.Request[scheduler.GetJobExecutionsRequest]) (*connect.Response[scheduler.GetJobExecutionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.GetJobExecutions is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) GetJobExecution(context.Context, *connect.Request[scheduler.GetJobExecutionRequest]) (*connect.Response[scheduler.GetJobExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.GetJobExecution is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) CancelJobExecution(context.Context, *connect.Request[scheduler.CancelJobExecutionRequest]) (*connect.Response[scheduler.CancelJobExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.CancelJobExecution is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) GetSchedulerHealth(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[scheduler.GetSchedulerHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.GetSchedulerHealth is not implemented"))
}

func (UnimplementedSchedulerServiceHandler) GetJobStatistics(context.Context, *connect.Request[scheduler.GetJobStatisticsRequest]) (*connect.Response[scheduler.GetJobStatisticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scheduler.api.v1.scheduler.SchedulerService.GetJobStatistics is not implemented"))
}
