// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: insightviewer/proto/insightviewer.proto

package insightviewerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	insightviewer "p9e.in/ugcl/insightviewer/api/v1/insightviewer"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReportExecutionServiceName is the fully-qualified name of the ReportExecutionService service.
	ReportExecutionServiceName = "insightviewer.api.v1.insightviewer.ReportExecutionService"
	// ReportSchedulingServiceName is the fully-qualified name of the ReportSchedulingService service.
	ReportSchedulingServiceName = "insightviewer.api.v1.insightviewer.ReportSchedulingService"
	// ReportSubscriptionServiceName is the fully-qualified name of the ReportSubscriptionService
	// service.
	ReportSubscriptionServiceName = "insightviewer.api.v1.insightviewer.ReportSubscriptionService"
	// ReportAlertsServiceName is the fully-qualified name of the ReportAlertsService service.
	ReportAlertsServiceName = "insightviewer.api.v1.insightviewer.ReportAlertsService"
	// CacheServiceName is the fully-qualified name of the CacheService service.
	CacheServiceName = "insightviewer.api.v1.insightviewer.CacheService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReportExecutionServiceExecuteReportProcedure is the fully-qualified name of the
	// ReportExecutionService's ExecuteReport RPC.
	ReportExecutionServiceExecuteReportProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/ExecuteReport"
	// ReportExecutionServiceGetReportRunProcedure is the fully-qualified name of the
	// ReportExecutionService's GetReportRun RPC.
	ReportExecutionServiceGetReportRunProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/GetReportRun"
	// ReportExecutionServiceGetReportRunStatusProcedure is the fully-qualified name of the
	// ReportExecutionService's GetReportRunStatus RPC.
	ReportExecutionServiceGetReportRunStatusProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/GetReportRunStatus"
	// ReportExecutionServiceCancelReportRunProcedure is the fully-qualified name of the
	// ReportExecutionService's CancelReportRun RPC.
	ReportExecutionServiceCancelReportRunProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/CancelReportRun"
	// ReportExecutionServiceGetReportRunHistoryProcedure is the fully-qualified name of the
	// ReportExecutionService's GetReportRunHistory RPC.
	ReportExecutionServiceGetReportRunHistoryProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/GetReportRunHistory"
	// ReportExecutionServiceGetReportResultsProcedure is the fully-qualified name of the
	// ReportExecutionService's GetReportResults RPC.
	ReportExecutionServiceGetReportResultsProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/GetReportResults"
	// ReportExecutionServiceStreamReportResultsProcedure is the fully-qualified name of the
	// ReportExecutionService's StreamReportResults RPC.
	ReportExecutionServiceStreamReportResultsProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/StreamReportResults"
	// ReportExecutionServiceExportReportProcedure is the fully-qualified name of the
	// ReportExecutionService's ExportReport RPC.
	ReportExecutionServiceExportReportProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/ExportReport"
	// ReportExecutionServiceGetExportStatusProcedure is the fully-qualified name of the
	// ReportExecutionService's GetExportStatus RPC.
	ReportExecutionServiceGetExportStatusProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/GetExportStatus"
	// ReportExecutionServiceDownloadExportProcedure is the fully-qualified name of the
	// ReportExecutionService's DownloadExport RPC.
	ReportExecutionServiceDownloadExportProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/DownloadExport"
	// ReportExecutionServiceGetExportHistoryProcedure is the fully-qualified name of the
	// ReportExecutionService's GetExportHistory RPC.
	ReportExecutionServiceGetExportHistoryProcedure = "/insightviewer.api.v1.insightviewer.ReportExecutionService/GetExportHistory"
	// ReportSchedulingServiceCreateScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's CreateSchedule RPC.
	ReportSchedulingServiceCreateScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/CreateSchedule"
	// ReportSchedulingServiceGetScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's GetSchedule RPC.
	ReportSchedulingServiceGetScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/GetSchedule"
	// ReportSchedulingServiceUpdateScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's UpdateSchedule RPC.
	ReportSchedulingServiceUpdateScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/UpdateSchedule"
	// ReportSchedulingServiceDeleteScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's DeleteSchedule RPC.
	ReportSchedulingServiceDeleteScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/DeleteSchedule"
	// ReportSchedulingServiceGetSchedulesByReportProcedure is the fully-qualified name of the
	// ReportSchedulingService's GetSchedulesByReport RPC.
	ReportSchedulingServiceGetSchedulesByReportProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/GetSchedulesByReport"
	// ReportSchedulingServiceGetUserSchedulesProcedure is the fully-qualified name of the
	// ReportSchedulingService's GetUserSchedules RPC.
	ReportSchedulingServiceGetUserSchedulesProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/GetUserSchedules"
	// ReportSchedulingServiceEnableScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's EnableSchedule RPC.
	ReportSchedulingServiceEnableScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/EnableSchedule"
	// ReportSchedulingServiceDisableScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's DisableSchedule RPC.
	ReportSchedulingServiceDisableScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/DisableSchedule"
	// ReportSchedulingServiceTriggerScheduleProcedure is the fully-qualified name of the
	// ReportSchedulingService's TriggerSchedule RPC.
	ReportSchedulingServiceTriggerScheduleProcedure = "/insightviewer.api.v1.insightviewer.ReportSchedulingService/TriggerSchedule"
	// ReportSubscriptionServiceCreateSubscriptionProcedure is the fully-qualified name of the
	// ReportSubscriptionService's CreateSubscription RPC.
	ReportSubscriptionServiceCreateSubscriptionProcedure = "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/CreateSubscription"
	// ReportSubscriptionServiceGetSubscriptionProcedure is the fully-qualified name of the
	// ReportSubscriptionService's GetSubscription RPC.
	ReportSubscriptionServiceGetSubscriptionProcedure = "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/GetSubscription"
	// ReportSubscriptionServiceUpdateSubscriptionProcedure is the fully-qualified name of the
	// ReportSubscriptionService's UpdateSubscription RPC.
	ReportSubscriptionServiceUpdateSubscriptionProcedure = "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/UpdateSubscription"
	// ReportSubscriptionServiceDeleteSubscriptionProcedure is the fully-qualified name of the
	// ReportSubscriptionService's DeleteSubscription RPC.
	ReportSubscriptionServiceDeleteSubscriptionProcedure = "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/DeleteSubscription"
	// ReportSubscriptionServiceGetUserSubscriptionsProcedure is the fully-qualified name of the
	// ReportSubscriptionService's GetUserSubscriptions RPC.
	ReportSubscriptionServiceGetUserSubscriptionsProcedure = "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/GetUserSubscriptions"
	// ReportSubscriptionServiceGetReportSubscriptionsProcedure is the fully-qualified name of the
	// ReportSubscriptionService's GetReportSubscriptions RPC.
	ReportSubscriptionServiceGetReportSubscriptionsProcedure = "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/GetReportSubscriptions"
	// ReportAlertsServiceCreateAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// CreateAlert RPC.
	ReportAlertsServiceCreateAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/CreateAlert"
	// ReportAlertsServiceGetAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// GetAlert RPC.
	ReportAlertsServiceGetAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/GetAlert"
	// ReportAlertsServiceUpdateAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// UpdateAlert RPC.
	ReportAlertsServiceUpdateAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/UpdateAlert"
	// ReportAlertsServiceDeleteAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// DeleteAlert RPC.
	ReportAlertsServiceDeleteAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/DeleteAlert"
	// ReportAlertsServiceGetReportAlertsProcedure is the fully-qualified name of the
	// ReportAlertsService's GetReportAlerts RPC.
	ReportAlertsServiceGetReportAlertsProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/GetReportAlerts"
	// ReportAlertsServiceGetUserAlertsProcedure is the fully-qualified name of the
	// ReportAlertsService's GetUserAlerts RPC.
	ReportAlertsServiceGetUserAlertsProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/GetUserAlerts"
	// ReportAlertsServiceEnableAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// EnableAlert RPC.
	ReportAlertsServiceEnableAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/EnableAlert"
	// ReportAlertsServiceDisableAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// DisableAlert RPC.
	ReportAlertsServiceDisableAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/DisableAlert"
	// ReportAlertsServiceTestAlertProcedure is the fully-qualified name of the ReportAlertsService's
	// TestAlert RPC.
	ReportAlertsServiceTestAlertProcedure = "/insightviewer.api.v1.insightviewer.ReportAlertsService/TestAlert"
	// CacheServiceGetCachedResultProcedure is the fully-qualified name of the CacheService's
	// GetCachedResult RPC.
	CacheServiceGetCachedResultProcedure = "/insightviewer.api.v1.insightviewer.CacheService/GetCachedResult"
	// CacheServiceInvalidateCacheProcedure is the fully-qualified name of the CacheService's
	// InvalidateCache RPC.
	CacheServiceInvalidateCacheProcedure = "/insightviewer.api.v1.insightviewer.CacheService/InvalidateCache"
	// CacheServiceGetCacheStatisticsProcedure is the fully-qualified name of the CacheService's
	// GetCacheStatistics RPC.
	CacheServiceGetCacheStatisticsProcedure = "/insightviewer.api.v1.insightviewer.CacheService/GetCacheStatistics"
	// CacheServiceCleanupCacheProcedure is the fully-qualified name of the CacheService's CleanupCache
	// RPC.
	CacheServiceCleanupCacheProcedure = "/insightviewer.api.v1.insightviewer.CacheService/CleanupCache"
)

// ReportExecutionServiceClient is a client for the
// insightviewer.api.v1.insightviewer.ReportExecutionService service.
type ReportExecutionServiceClient interface {
	// Report execution
	ExecuteReport(context.Context, *connect.Request[insightviewer.ExecuteReportRequest]) (*connect.Response[insightviewer.ExecuteReportResponse], error)
	GetReportRun(context.Context, *connect.Request[insightviewer.GetReportRunRequest]) (*connect.Response[insightviewer.GetReportRunResponse], error)
	GetReportRunStatus(context.Context, *connect.Request[insightviewer.GetReportRunStatusRequest]) (*connect.Response[insightviewer.GetReportRunStatusResponse], error)
	CancelReportRun(context.Context, *connect.Request[insightviewer.CancelReportRunRequest]) (*connect.Response[insightviewer.CancelReportRunResponse], error)
	GetReportRunHistory(context.Context, *connect.Request[insightviewer.GetReportRunHistoryRequest]) (*connect.Response[insightviewer.GetReportRunHistoryResponse], error)
	// Result management
	GetReportResults(context.Context, *connect.Request[insightviewer.GetReportResultsRequest]) (*connect.Response[insightviewer.GetReportResultsResponse], error)
	StreamReportResults(context.Context, *connect.Request[insightviewer.StreamReportResultsRequest]) (*connect.ServerStreamForClient[insightviewer.StreamReportResultsResponse], error)
	// Export functionality
	ExportReport(context.Context, *connect.Request[insightviewer.ExportReportRequest]) (*connect.Response[insightviewer.ExportReportResponse], error)
	GetExportStatus(context.Context, *connect.Request[insightviewer.GetExportStatusRequest]) (*connect.Response[insightviewer.GetExportStatusResponse], error)
	DownloadExport(context.Context, *connect.Request[insightviewer.DownloadExportRequest]) (*connect.ServerStreamForClient[insightviewer.DownloadExportResponse], error)
	GetExportHistory(context.Context, *connect.Request[insightviewer.GetExportHistoryRequest]) (*connect.Response[insightviewer.GetExportHistoryResponse], error)
}

// NewReportExecutionServiceClient constructs a client for the
// insightviewer.api.v1.insightviewer.ReportExecutionService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReportExecutionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReportExecutionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reportExecutionServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportExecutionService").Methods()
	return &reportExecutionServiceClient{
		executeReport: connect.NewClient[insightviewer.ExecuteReportRequest, insightviewer.ExecuteReportResponse](
			httpClient,
			baseURL+ReportExecutionServiceExecuteReportProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("ExecuteReport")),
			connect.WithClientOptions(opts...),
		),
		getReportRun: connect.NewClient[insightviewer.GetReportRunRequest, insightviewer.GetReportRunResponse](
			httpClient,
			baseURL+ReportExecutionServiceGetReportRunProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportRun")),
			connect.WithClientOptions(opts...),
		),
		getReportRunStatus: connect.NewClient[insightviewer.GetReportRunStatusRequest, insightviewer.GetReportRunStatusResponse](
			httpClient,
			baseURL+ReportExecutionServiceGetReportRunStatusProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportRunStatus")),
			connect.WithClientOptions(opts...),
		),
		cancelReportRun: connect.NewClient[insightviewer.CancelReportRunRequest, insightviewer.CancelReportRunResponse](
			httpClient,
			baseURL+ReportExecutionServiceCancelReportRunProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("CancelReportRun")),
			connect.WithClientOptions(opts...),
		),
		getReportRunHistory: connect.NewClient[insightviewer.GetReportRunHistoryRequest, insightviewer.GetReportRunHistoryResponse](
			httpClient,
			baseURL+ReportExecutionServiceGetReportRunHistoryProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportRunHistory")),
			connect.WithClientOptions(opts...),
		),
		getReportResults: connect.NewClient[insightviewer.GetReportResultsRequest, insightviewer.GetReportResultsResponse](
			httpClient,
			baseURL+ReportExecutionServiceGetReportResultsProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportResults")),
			connect.WithClientOptions(opts...),
		),
		streamReportResults: connect.NewClient[insightviewer.StreamReportResultsRequest, insightviewer.StreamReportResultsResponse](
			httpClient,
			baseURL+ReportExecutionServiceStreamReportResultsProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("StreamReportResults")),
			connect.WithClientOptions(opts...),
		),
		exportReport: connect.NewClient[insightviewer.ExportReportRequest, insightviewer.ExportReportResponse](
			httpClient,
			baseURL+ReportExecutionServiceExportReportProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("ExportReport")),
			connect.WithClientOptions(opts...),
		),
		getExportStatus: connect.NewClient[insightviewer.GetExportStatusRequest, insightviewer.GetExportStatusResponse](
			httpClient,
			baseURL+ReportExecutionServiceGetExportStatusProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("GetExportStatus")),
			connect.WithClientOptions(opts...),
		),
		downloadExport: connect.NewClient[insightviewer.DownloadExportRequest, insightviewer.DownloadExportResponse](
			httpClient,
			baseURL+ReportExecutionServiceDownloadExportProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("DownloadExport")),
			connect.WithClientOptions(opts...),
		),
		getExportHistory: connect.NewClient[insightviewer.GetExportHistoryRequest, insightviewer.GetExportHistoryResponse](
			httpClient,
			baseURL+ReportExecutionServiceGetExportHistoryProcedure,
			connect.WithSchema(reportExecutionServiceMethods.ByName("GetExportHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reportExecutionServiceClient implements ReportExecutionServiceClient.
type reportExecutionServiceClient struct {
	executeReport       *connect.Client[insightviewer.ExecuteReportRequest, insightviewer.ExecuteReportResponse]
	getReportRun        *connect.Client[insightviewer.GetReportRunRequest, insightviewer.GetReportRunResponse]
	getReportRunStatus  *connect.Client[insightviewer.GetReportRunStatusRequest, insightviewer.GetReportRunStatusResponse]
	cancelReportRun     *connect.Client[insightviewer.CancelReportRunRequest, insightviewer.CancelReportRunResponse]
	getReportRunHistory *connect.Client[insightviewer.GetReportRunHistoryRequest, insightviewer.GetReportRunHistoryResponse]
	getReportResults    *connect.Client[insightviewer.GetReportResultsRequest, insightviewer.GetReportResultsResponse]
	streamReportResults *connect.Client[insightviewer.StreamReportResultsRequest, insightviewer.StreamReportResultsResponse]
	exportReport        *connect.Client[insightviewer.ExportReportRequest, insightviewer.ExportReportResponse]
	getExportStatus     *connect.Client[insightviewer.GetExportStatusRequest, insightviewer.GetExportStatusResponse]
	downloadExport      *connect.Client[insightviewer.DownloadExportRequest, insightviewer.DownloadExportResponse]
	getExportHistory    *connect.Client[insightviewer.GetExportHistoryRequest, insightviewer.GetExportHistoryResponse]
}

// ExecuteReport calls insightviewer.api.v1.insightviewer.ReportExecutionService.ExecuteReport.
func (c *reportExecutionServiceClient) ExecuteReport(ctx context.Context, req *connect.Request[insightviewer.ExecuteReportRequest]) (*connect.Response[insightviewer.ExecuteReportResponse], error) {
	return c.executeReport.CallUnary(ctx, req)
}

// GetReportRun calls insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportRun.
func (c *reportExecutionServiceClient) GetReportRun(ctx context.Context, req *connect.Request[insightviewer.GetReportRunRequest]) (*connect.Response[insightviewer.GetReportRunResponse], error) {
	return c.getReportRun.CallUnary(ctx, req)
}

// GetReportRunStatus calls
// insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportRunStatus.
func (c *reportExecutionServiceClient) GetReportRunStatus(ctx context.Context, req *connect.Request[insightviewer.GetReportRunStatusRequest]) (*connect.Response[insightviewer.GetReportRunStatusResponse], error) {
	return c.getReportRunStatus.CallUnary(ctx, req)
}

// CancelReportRun calls insightviewer.api.v1.insightviewer.ReportExecutionService.CancelReportRun.
func (c *reportExecutionServiceClient) CancelReportRun(ctx context.Context, req *connect.Request[insightviewer.CancelReportRunRequest]) (*connect.Response[insightviewer.CancelReportRunResponse], error) {
	return c.cancelReportRun.CallUnary(ctx, req)
}

// GetReportRunHistory calls
// insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportRunHistory.
func (c *reportExecutionServiceClient) GetReportRunHistory(ctx context.Context, req *connect.Request[insightviewer.GetReportRunHistoryRequest]) (*connect.Response[insightviewer.GetReportRunHistoryResponse], error) {
	return c.getReportRunHistory.CallUnary(ctx, req)
}

// GetReportResults calls
// insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportResults.
func (c *reportExecutionServiceClient) GetReportResults(ctx context.Context, req *connect.Request[insightviewer.GetReportResultsRequest]) (*connect.Response[insightviewer.GetReportResultsResponse], error) {
	return c.getReportResults.CallUnary(ctx, req)
}

// StreamReportResults calls
// insightviewer.api.v1.insightviewer.ReportExecutionService.StreamReportResults.
func (c *reportExecutionServiceClient) StreamReportResults(ctx context.Context, req *connect.Request[insightviewer.StreamReportResultsRequest]) (*connect.ServerStreamForClient[insightviewer.StreamReportResultsResponse], error) {
	return c.streamReportResults.CallServerStream(ctx, req)
}

// ExportReport calls insightviewer.api.v1.insightviewer.ReportExecutionService.ExportReport.
func (c *reportExecutionServiceClient) ExportReport(ctx context.Context, req *connect.Request[insightviewer.ExportReportRequest]) (*connect.Response[insightviewer.ExportReportResponse], error) {
	return c.exportReport.CallUnary(ctx, req)
}

// GetExportStatus calls insightviewer.api.v1.insightviewer.ReportExecutionService.GetExportStatus.
func (c *reportExecutionServiceClient) GetExportStatus(ctx context.Context, req *connect.Request[insightviewer.GetExportStatusRequest]) (*connect.Response[insightviewer.GetExportStatusResponse], error) {
	return c.getExportStatus.CallUnary(ctx, req)
}

// DownloadExport calls insightviewer.api.v1.insightviewer.ReportExecutionService.DownloadExport.
func (c *reportExecutionServiceClient) DownloadExport(ctx context.Context, req *connect.Request[insightviewer.DownloadExportRequest]) (*connect.ServerStreamForClient[insightviewer.DownloadExportResponse], error) {
	return c.downloadExport.CallServerStream(ctx, req)
}

// GetExportHistory calls
// insightviewer.api.v1.insightviewer.ReportExecutionService.GetExportHistory.
func (c *reportExecutionServiceClient) GetExportHistory(ctx context.Context, req *connect.Request[insightviewer.GetExportHistoryRequest]) (*connect.Response[insightviewer.GetExportHistoryResponse], error) {
	return c.getExportHistory.CallUnary(ctx, req)
}

// ReportExecutionServiceHandler is an implementation of the
// insightviewer.api.v1.insightviewer.ReportExecutionService service.
type ReportExecutionServiceHandler interface {
	// Report execution
	ExecuteReport(context.Context, *connect.Request[insightviewer.ExecuteReportRequest]) (*connect.Response[insightviewer.ExecuteReportResponse], error)
	GetReportRun(context.Context, *connect.Request[insightviewer.GetReportRunRequest]) (*connect.Response[insightviewer.GetReportRunResponse], error)
	GetReportRunStatus(context.Context, *connect.Request[insightviewer.GetReportRunStatusRequest]) (*connect.Response[insightviewer.GetReportRunStatusResponse], error)
	CancelReportRun(context.Context, *connect.Request[insightviewer.CancelReportRunRequest]) (*connect.Response[insightviewer.CancelReportRunResponse], error)
	GetReportRunHistory(context.Context, *connect.Request[insightviewer.GetReportRunHistoryRequest]) (*connect.Response[insightviewer.GetReportRunHistoryResponse], error)
	// Result management
	GetReportResults(context.Context, *connect.Request[insightviewer.GetReportResultsRequest]) (*connect.Response[insightviewer.GetReportResultsResponse], error)
	StreamReportResults(context.Context, *connect.Request[insightviewer.StreamReportResultsRequest], *connect.ServerStream[insightviewer.StreamReportResultsResponse]) error
	// Export functionality
	ExportReport(context.Context, *connect.Request[insightviewer.ExportReportRequest]) (*connect.Response[insightviewer.ExportReportResponse], error)
	GetExportStatus(context.Context, *connect.Request[insightviewer.GetExportStatusRequest]) (*connect.Response[insightviewer.GetExportStatusResponse], error)
	DownloadExport(context.Context, *connect.Request[insightviewer.DownloadExportRequest], *connect.ServerStream[insightviewer.DownloadExportResponse]) error
	GetExportHistory(context.Context, *connect.Request[insightviewer.GetExportHistoryRequest]) (*connect.Response[insightviewer.GetExportHistoryResponse], error)
}

// NewReportExecutionServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReportExecutionServiceHandler(svc ReportExecutionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reportExecutionServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportExecutionService").Methods()
	reportExecutionServiceExecuteReportHandler := connect.NewUnaryHandler(
		ReportExecutionServiceExecuteReportProcedure,
		svc.ExecuteReport,
		connect.WithSchema(reportExecutionServiceMethods.ByName("ExecuteReport")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceGetReportRunHandler := connect.NewUnaryHandler(
		ReportExecutionServiceGetReportRunProcedure,
		svc.GetReportRun,
		connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportRun")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceGetReportRunStatusHandler := connect.NewUnaryHandler(
		ReportExecutionServiceGetReportRunStatusProcedure,
		svc.GetReportRunStatus,
		connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportRunStatus")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceCancelReportRunHandler := connect.NewUnaryHandler(
		ReportExecutionServiceCancelReportRunProcedure,
		svc.CancelReportRun,
		connect.WithSchema(reportExecutionServiceMethods.ByName("CancelReportRun")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceGetReportRunHistoryHandler := connect.NewUnaryHandler(
		ReportExecutionServiceGetReportRunHistoryProcedure,
		svc.GetReportRunHistory,
		connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportRunHistory")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceGetReportResultsHandler := connect.NewUnaryHandler(
		ReportExecutionServiceGetReportResultsProcedure,
		svc.GetReportResults,
		connect.WithSchema(reportExecutionServiceMethods.ByName("GetReportResults")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceStreamReportResultsHandler := connect.NewServerStreamHandler(
		ReportExecutionServiceStreamReportResultsProcedure,
		svc.StreamReportResults,
		connect.WithSchema(reportExecutionServiceMethods.ByName("StreamReportResults")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceExportReportHandler := connect.NewUnaryHandler(
		ReportExecutionServiceExportReportProcedure,
		svc.ExportReport,
		connect.WithSchema(reportExecutionServiceMethods.ByName("ExportReport")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceGetExportStatusHandler := connect.NewUnaryHandler(
		ReportExecutionServiceGetExportStatusProcedure,
		svc.GetExportStatus,
		connect.WithSchema(reportExecutionServiceMethods.ByName("GetExportStatus")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceDownloadExportHandler := connect.NewServerStreamHandler(
		ReportExecutionServiceDownloadExportProcedure,
		svc.DownloadExport,
		connect.WithSchema(reportExecutionServiceMethods.ByName("DownloadExport")),
		connect.WithHandlerOptions(opts...),
	)
	reportExecutionServiceGetExportHistoryHandler := connect.NewUnaryHandler(
		ReportExecutionServiceGetExportHistoryProcedure,
		svc.GetExportHistory,
		connect.WithSchema(reportExecutionServiceMethods.ByName("GetExportHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/insightviewer.api.v1.insightviewer.ReportExecutionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReportExecutionServiceExecuteReportProcedure:
			reportExecutionServiceExecuteReportHandler.ServeHTTP(w, r)
		case ReportExecutionServiceGetReportRunProcedure:
			reportExecutionServiceGetReportRunHandler.ServeHTTP(w, r)
		case ReportExecutionServiceGetReportRunStatusProcedure:
			reportExecutionServiceGetReportRunStatusHandler.ServeHTTP(w, r)
		case ReportExecutionServiceCancelReportRunProcedure:
			reportExecutionServiceCancelReportRunHandler.ServeHTTP(w, r)
		case ReportExecutionServiceGetReportRunHistoryProcedure:
			reportExecutionServiceGetReportRunHistoryHandler.ServeHTTP(w, r)
		case ReportExecutionServiceGetReportResultsProcedure:
			reportExecutionServiceGetReportResultsHandler.ServeHTTP(w, r)
		case ReportExecutionServiceStreamReportResultsProcedure:
			reportExecutionServiceStreamReportResultsHandler.ServeHTTP(w, r)
		case ReportExecutionServiceExportReportProcedure:
			reportExecutionServiceExportReportHandler.ServeHTTP(w, r)
		case ReportExecutionServiceGetExportStatusProcedure:
			reportExecutionServiceGetExportStatusHandler.ServeHTTP(w, r)
		case ReportExecutionServiceDownloadExportProcedure:
			reportExecutionServiceDownloadExportHandler.ServeHTTP(w, r)
		case ReportExecutionServiceGetExportHistoryProcedure:
			reportExecutionServiceGetExportHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReportExecutionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReportExecutionServiceHandler struct{}

func (UnimplementedReportExecutionServiceHandler) ExecuteReport(context.Context, *connect.Request[insightviewer.ExecuteReportRequest]) (*connect.Response[insightviewer.ExecuteReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.ExecuteReport is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) GetReportRun(context.Context, *connect.Request[insightviewer.GetReportRunRequest]) (*connect.Response[insightviewer.GetReportRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportRun is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) GetReportRunStatus(context.Context, *connect.Request[insightviewer.GetReportRunStatusRequest]) (*connect.Response[insightviewer.GetReportRunStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportRunStatus is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) CancelReportRun(context.Context, *connect.Request[insightviewer.CancelReportRunRequest]) (*connect.Response[insightviewer.CancelReportRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.CancelReportRun is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) GetReportRunHistory(context.Context, *connect.Request[insightviewer.GetReportRunHistoryRequest]) (*connect.Response[insightviewer.GetReportRunHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportRunHistory is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) GetReportResults(context.Context, *connect.Request[insightviewer.GetReportResultsRequest]) (*connect.Response[insightviewer.GetReportResultsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.GetReportResults is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) StreamReportResults(context.Context, *connect.Request[insightviewer.StreamReportResultsRequest], *connect.ServerStream[insightviewer.StreamReportResultsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.StreamReportResults is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) ExportReport(context.Context, *connect.Request[insightviewer.ExportReportRequest]) (*connect.Response[insightviewer.ExportReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.ExportReport is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) GetExportStatus(context.Context, *connect.Request[insightviewer.GetExportStatusRequest]) (*connect.Response[insightviewer.GetExportStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.GetExportStatus is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) DownloadExport(context.Context, *connect.Request[insightviewer.DownloadExportRequest], *connect.ServerStream[insightviewer.DownloadExportResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.DownloadExport is not implemented"))
}

func (UnimplementedReportExecutionServiceHandler) GetExportHistory(context.Context, *connect.Request[insightviewer.GetExportHistoryRequest]) (*connect.Response[insightviewer.GetExportHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportExecutionService.GetExportHistory is not implemented"))
}

// ReportSchedulingServiceClient is a client for the
// insightviewer.api.v1.insightviewer.ReportSchedulingService service.
type ReportSchedulingServiceClient interface {
	// Schedule management
	CreateSchedule(context.Context, *connect.Request[insightviewer.CreateScheduleRequest]) (*connect.Response[insightviewer.CreateScheduleResponse], error)
	GetSchedule(context.Context, *connect.Request[insightviewer.GetScheduleRequest]) (*connect.Response[insightviewer.GetScheduleResponse], error)
	UpdateSchedule(context.Context, *connect.Request[insightviewer.UpdateScheduleRequest]) (*connect.Response[insightviewer.UpdateScheduleResponse], error)
	DeleteSchedule(context.Context, *connect.Request[insightviewer.DeleteScheduleRequest]) (*connect.Response[insightviewer.DeleteScheduleResponse], error)
	GetSchedulesByReport(context.Context, *connect.Request[insightviewer.GetSchedulesByReportRequest]) (*connect.Response[insightviewer.GetSchedulesByReportResponse], error)
	GetUserSchedules(context.Context, *connect.Request[insightviewer.GetUserSchedulesRequest]) (*connect.Response[insightviewer.GetUserSchedulesResponse], error)
	// Schedule control
	EnableSchedule(context.Context, *connect.Request[insightviewer.EnableScheduleRequest]) (*connect.Response[insightviewer.EnableScheduleResponse], error)
	DisableSchedule(context.Context, *connect.Request[insightviewer.DisableScheduleRequest]) (*connect.Response[insightviewer.DisableScheduleResponse], error)
	TriggerSchedule(context.Context, *connect.Request[insightviewer.TriggerScheduleRequest]) (*connect.Response[insightviewer.TriggerScheduleResponse], error)
}

// NewReportSchedulingServiceClient constructs a client for the
// insightviewer.api.v1.insightviewer.ReportSchedulingService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReportSchedulingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReportSchedulingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reportSchedulingServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportSchedulingService").Methods()
	return &reportSchedulingServiceClient{
		createSchedule: connect.NewClient[insightviewer.CreateScheduleRequest, insightviewer.CreateScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceCreateScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("CreateSchedule")),
			connect.WithClientOptions(opts...),
		),
		getSchedule: connect.NewClient[insightviewer.GetScheduleRequest, insightviewer.GetScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceGetScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("GetSchedule")),
			connect.WithClientOptions(opts...),
		),
		updateSchedule: connect.NewClient[insightviewer.UpdateScheduleRequest, insightviewer.UpdateScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceUpdateScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("UpdateSchedule")),
			connect.WithClientOptions(opts...),
		),
		deleteSchedule: connect.NewClient[insightviewer.DeleteScheduleRequest, insightviewer.DeleteScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceDeleteScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("DeleteSchedule")),
			connect.WithClientOptions(opts...),
		),
		getSchedulesByReport: connect.NewClient[insightviewer.GetSchedulesByReportRequest, insightviewer.GetSchedulesByReportResponse](
			httpClient,
			baseURL+ReportSchedulingServiceGetSchedulesByReportProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("GetSchedulesByReport")),
			connect.WithClientOptions(opts...),
		),
		getUserSchedules: connect.NewClient[insightviewer.GetUserSchedulesRequest, insightviewer.GetUserSchedulesResponse](
			httpClient,
			baseURL+ReportSchedulingServiceGetUserSchedulesProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("GetUserSchedules")),
			connect.WithClientOptions(opts...),
		),
		enableSchedule: connect.NewClient[insightviewer.EnableScheduleRequest, insightviewer.EnableScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceEnableScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("EnableSchedule")),
			connect.WithClientOptions(opts...),
		),
		disableSchedule: connect.NewClient[insightviewer.DisableScheduleRequest, insightviewer.DisableScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceDisableScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("DisableSchedule")),
			connect.WithClientOptions(opts...),
		),
		triggerSchedule: connect.NewClient[insightviewer.TriggerScheduleRequest, insightviewer.TriggerScheduleResponse](
			httpClient,
			baseURL+ReportSchedulingServiceTriggerScheduleProcedure,
			connect.WithSchema(reportSchedulingServiceMethods.ByName("TriggerSchedule")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reportSchedulingServiceClient implements ReportSchedulingServiceClient.
type reportSchedulingServiceClient struct {
	createSchedule       *connect.Client[insightviewer.CreateScheduleRequest, insightviewer.CreateScheduleResponse]
	getSchedule          *connect.Client[insightviewer.GetScheduleRequest, insightviewer.GetScheduleResponse]
	updateSchedule       *connect.Client[insightviewer.UpdateScheduleRequest, insightviewer.UpdateScheduleResponse]
	deleteSchedule       *connect.Client[insightviewer.DeleteScheduleRequest, insightviewer.DeleteScheduleResponse]
	getSchedulesByReport *connect.Client[insightviewer.GetSchedulesByReportRequest, insightviewer.GetSchedulesByReportResponse]
	getUserSchedules     *connect.Client[insightviewer.GetUserSchedulesRequest, insightviewer.GetUserSchedulesResponse]
	enableSchedule       *connect.Client[insightviewer.EnableScheduleRequest, insightviewer.EnableScheduleResponse]
	disableSchedule      *connect.Client[insightviewer.DisableScheduleRequest, insightviewer.DisableScheduleResponse]
	triggerSchedule      *connect.Client[insightviewer.TriggerScheduleRequest, insightviewer.TriggerScheduleResponse]
}

// CreateSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.CreateSchedule.
func (c *reportSchedulingServiceClient) CreateSchedule(ctx context.Context, req *connect.Request[insightviewer.CreateScheduleRequest]) (*connect.Response[insightviewer.CreateScheduleResponse], error) {
	return c.createSchedule.CallUnary(ctx, req)
}

// GetSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.GetSchedule.
func (c *reportSchedulingServiceClient) GetSchedule(ctx context.Context, req *connect.Request[insightviewer.GetScheduleRequest]) (*connect.Response[insightviewer.GetScheduleResponse], error) {
	return c.getSchedule.CallUnary(ctx, req)
}

// UpdateSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.UpdateSchedule.
func (c *reportSchedulingServiceClient) UpdateSchedule(ctx context.Context, req *connect.Request[insightviewer.UpdateScheduleRequest]) (*connect.Response[insightviewer.UpdateScheduleResponse], error) {
	return c.updateSchedule.CallUnary(ctx, req)
}

// DeleteSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.DeleteSchedule.
func (c *reportSchedulingServiceClient) DeleteSchedule(ctx context.Context, req *connect.Request[insightviewer.DeleteScheduleRequest]) (*connect.Response[insightviewer.DeleteScheduleResponse], error) {
	return c.deleteSchedule.CallUnary(ctx, req)
}

// GetSchedulesByReport calls
// insightviewer.api.v1.insightviewer.ReportSchedulingService.GetSchedulesByReport.
func (c *reportSchedulingServiceClient) GetSchedulesByReport(ctx context.Context, req *connect.Request[insightviewer.GetSchedulesByReportRequest]) (*connect.Response[insightviewer.GetSchedulesByReportResponse], error) {
	return c.getSchedulesByReport.CallUnary(ctx, req)
}

// GetUserSchedules calls
// insightviewer.api.v1.insightviewer.ReportSchedulingService.GetUserSchedules.
func (c *reportSchedulingServiceClient) GetUserSchedules(ctx context.Context, req *connect.Request[insightviewer.GetUserSchedulesRequest]) (*connect.Response[insightviewer.GetUserSchedulesResponse], error) {
	return c.getUserSchedules.CallUnary(ctx, req)
}

// EnableSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.EnableSchedule.
func (c *reportSchedulingServiceClient) EnableSchedule(ctx context.Context, req *connect.Request[insightviewer.EnableScheduleRequest]) (*connect.Response[insightviewer.EnableScheduleResponse], error) {
	return c.enableSchedule.CallUnary(ctx, req)
}

// DisableSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.DisableSchedule.
func (c *reportSchedulingServiceClient) DisableSchedule(ctx context.Context, req *connect.Request[insightviewer.DisableScheduleRequest]) (*connect.Response[insightviewer.DisableScheduleResponse], error) {
	return c.disableSchedule.CallUnary(ctx, req)
}

// TriggerSchedule calls insightviewer.api.v1.insightviewer.ReportSchedulingService.TriggerSchedule.
func (c *reportSchedulingServiceClient) TriggerSchedule(ctx context.Context, req *connect.Request[insightviewer.TriggerScheduleRequest]) (*connect.Response[insightviewer.TriggerScheduleResponse], error) {
	return c.triggerSchedule.CallUnary(ctx, req)
}

// ReportSchedulingServiceHandler is an implementation of the
// insightviewer.api.v1.insightviewer.ReportSchedulingService service.
type ReportSchedulingServiceHandler interface {
	// Schedule management
	CreateSchedule(context.Context, *connect.Request[insightviewer.CreateScheduleRequest]) (*connect.Response[insightviewer.CreateScheduleResponse], error)
	GetSchedule(context.Context, *connect.Request[insightviewer.GetScheduleRequest]) (*connect.Response[insightviewer.GetScheduleResponse], error)
	UpdateSchedule(context.Context, *connect.Request[insightviewer.UpdateScheduleRequest]) (*connect.Response[insightviewer.UpdateScheduleResponse], error)
	DeleteSchedule(context.Context, *connect.Request[insightviewer.DeleteScheduleRequest]) (*connect.Response[insightviewer.DeleteScheduleResponse], error)
	GetSchedulesByReport(context.Context, *connect.Request[insightviewer.GetSchedulesByReportRequest]) (*connect.Response[insightviewer.GetSchedulesByReportResponse], error)
	GetUserSchedules(context.Context, *connect.Request[insightviewer.GetUserSchedulesRequest]) (*connect.Response[insightviewer.GetUserSchedulesResponse], error)
	// Schedule control
	EnableSchedule(context.Context, *connect.Request[insightviewer.EnableScheduleRequest]) (*connect.Response[insightviewer.EnableScheduleResponse], error)
	DisableSchedule(context.Context, *connect.Request[insightviewer.DisableScheduleRequest]) (*connect.Response[insightviewer.DisableScheduleResponse], error)
	TriggerSchedule(context.Context, *connect.Request[insightviewer.TriggerScheduleRequest]) (*connect.Response[insightviewer.TriggerScheduleResponse], error)
}

// NewReportSchedulingServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReportSchedulingServiceHandler(svc ReportSchedulingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reportSchedulingServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportSchedulingService").Methods()
	reportSchedulingServiceCreateScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceCreateScheduleProcedure,
		svc.CreateSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("CreateSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceGetScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceGetScheduleProcedure,
		svc.GetSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("GetSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceUpdateScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceUpdateScheduleProcedure,
		svc.UpdateSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("UpdateSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceDeleteScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceDeleteScheduleProcedure,
		svc.DeleteSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("DeleteSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceGetSchedulesByReportHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceGetSchedulesByReportProcedure,
		svc.GetSchedulesByReport,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("GetSchedulesByReport")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceGetUserSchedulesHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceGetUserSchedulesProcedure,
		svc.GetUserSchedules,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("GetUserSchedules")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceEnableScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceEnableScheduleProcedure,
		svc.EnableSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("EnableSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceDisableScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceDisableScheduleProcedure,
		svc.DisableSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("DisableSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reportSchedulingServiceTriggerScheduleHandler := connect.NewUnaryHandler(
		ReportSchedulingServiceTriggerScheduleProcedure,
		svc.TriggerSchedule,
		connect.WithSchema(reportSchedulingServiceMethods.ByName("TriggerSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	return "/insightviewer.api.v1.insightviewer.ReportSchedulingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReportSchedulingServiceCreateScheduleProcedure:
			reportSchedulingServiceCreateScheduleHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceGetScheduleProcedure:
			reportSchedulingServiceGetScheduleHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceUpdateScheduleProcedure:
			reportSchedulingServiceUpdateScheduleHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceDeleteScheduleProcedure:
			reportSchedulingServiceDeleteScheduleHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceGetSchedulesByReportProcedure:
			reportSchedulingServiceGetSchedulesByReportHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceGetUserSchedulesProcedure:
			reportSchedulingServiceGetUserSchedulesHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceEnableScheduleProcedure:
			reportSchedulingServiceEnableScheduleHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceDisableScheduleProcedure:
			reportSchedulingServiceDisableScheduleHandler.ServeHTTP(w, r)
		case ReportSchedulingServiceTriggerScheduleProcedure:
			reportSchedulingServiceTriggerScheduleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReportSchedulingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReportSchedulingServiceHandler struct{}

func (UnimplementedReportSchedulingServiceHandler) CreateSchedule(context.Context, *connect.Request[insightviewer.CreateScheduleRequest]) (*connect.Response[insightviewer.CreateScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.CreateSchedule is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) GetSchedule(context.Context, *connect.Request[insightviewer.GetScheduleRequest]) (*connect.Response[insightviewer.GetScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.GetSchedule is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) UpdateSchedule(context.Context, *connect.Request[insightviewer.UpdateScheduleRequest]) (*connect.Response[insightviewer.UpdateScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.UpdateSchedule is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) DeleteSchedule(context.Context, *connect.Request[insightviewer.DeleteScheduleRequest]) (*connect.Response[insightviewer.DeleteScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.DeleteSchedule is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) GetSchedulesByReport(context.Context, *connect.Request[insightviewer.GetSchedulesByReportRequest]) (*connect.Response[insightviewer.GetSchedulesByReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.GetSchedulesByReport is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) GetUserSchedules(context.Context, *connect.Request[insightviewer.GetUserSchedulesRequest]) (*connect.Response[insightviewer.GetUserSchedulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.GetUserSchedules is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) EnableSchedule(context.Context, *connect.Request[insightviewer.EnableScheduleRequest]) (*connect.Response[insightviewer.EnableScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.EnableSchedule is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) DisableSchedule(context.Context, *connect.Request[insightviewer.DisableScheduleRequest]) (*connect.Response[insightviewer.DisableScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.DisableSchedule is not implemented"))
}

func (UnimplementedReportSchedulingServiceHandler) TriggerSchedule(context.Context, *connect.Request[insightviewer.TriggerScheduleRequest]) (*connect.Response[insightviewer.TriggerScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSchedulingService.TriggerSchedule is not implemented"))
}

// ReportSubscriptionServiceClient is a client for the
// insightviewer.api.v1.insightviewer.ReportSubscriptionService service.
type ReportSubscriptionServiceClient interface {
	// Subscription management
	CreateSubscription(context.Context, *connect.Request[insightviewer.CreateSubscriptionRequest]) (*connect.Response[insightviewer.CreateSubscriptionResponse], error)
	GetSubscription(context.Context, *connect.Request[insightviewer.GetSubscriptionRequest]) (*connect.Response[insightviewer.GetSubscriptionResponse], error)
	UpdateSubscription(context.Context, *connect.Request[insightviewer.UpdateSubscriptionRequest]) (*connect.Response[insightviewer.UpdateSubscriptionResponse], error)
	DeleteSubscription(context.Context, *connect.Request[insightviewer.DeleteSubscriptionRequest]) (*connect.Response[insightviewer.DeleteSubscriptionResponse], error)
	GetUserSubscriptions(context.Context, *connect.Request[insightviewer.GetUserSubscriptionsRequest]) (*connect.Response[insightviewer.GetUserSubscriptionsResponse], error)
	GetReportSubscriptions(context.Context, *connect.Request[insightviewer.GetReportSubscriptionsRequest]) (*connect.Response[insightviewer.GetReportSubscriptionsResponse], error)
}

// NewReportSubscriptionServiceClient constructs a client for the
// insightviewer.api.v1.insightviewer.ReportSubscriptionService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReportSubscriptionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReportSubscriptionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reportSubscriptionServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportSubscriptionService").Methods()
	return &reportSubscriptionServiceClient{
		createSubscription: connect.NewClient[insightviewer.CreateSubscriptionRequest, insightviewer.CreateSubscriptionResponse](
			httpClient,
			baseURL+ReportSubscriptionServiceCreateSubscriptionProcedure,
			connect.WithSchema(reportSubscriptionServiceMethods.ByName("CreateSubscription")),
			connect.WithClientOptions(opts...),
		),
		getSubscription: connect.NewClient[insightviewer.GetSubscriptionRequest, insightviewer.GetSubscriptionResponse](
			httpClient,
			baseURL+ReportSubscriptionServiceGetSubscriptionProcedure,
			connect.WithSchema(reportSubscriptionServiceMethods.ByName("GetSubscription")),
			connect.WithClientOptions(opts...),
		),
		updateSubscription: connect.NewClient[insightviewer.UpdateSubscriptionRequest, insightviewer.UpdateSubscriptionResponse](
			httpClient,
			baseURL+ReportSubscriptionServiceUpdateSubscriptionProcedure,
			connect.WithSchema(reportSubscriptionServiceMethods.ByName("UpdateSubscription")),
			connect.WithClientOptions(opts...),
		),
		deleteSubscription: connect.NewClient[insightviewer.DeleteSubscriptionRequest, insightviewer.DeleteSubscriptionResponse](
			httpClient,
			baseURL+ReportSubscriptionServiceDeleteSubscriptionProcedure,
			connect.WithSchema(reportSubscriptionServiceMethods.ByName("DeleteSubscription")),
			connect.WithClientOptions(opts...),
		),
		getUserSubscriptions: connect.NewClient[insightviewer.GetUserSubscriptionsRequest, insightviewer.GetUserSubscriptionsResponse](
			httpClient,
			baseURL+ReportSubscriptionServiceGetUserSubscriptionsProcedure,
			connect.WithSchema(reportSubscriptionServiceMethods.ByName("GetUserSubscriptions")),
			connect.WithClientOptions(opts...),
		),
		getReportSubscriptions: connect.NewClient[insightviewer.GetReportSubscriptionsRequest, insightviewer.GetReportSubscriptionsResponse](
			httpClient,
			baseURL+ReportSubscriptionServiceGetReportSubscriptionsProcedure,
			connect.WithSchema(reportSubscriptionServiceMethods.ByName("GetReportSubscriptions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reportSubscriptionServiceClient implements ReportSubscriptionServiceClient.
type reportSubscriptionServiceClient struct {
	createSubscription     *connect.Client[insightviewer.CreateSubscriptionRequest, insightviewer.CreateSubscriptionResponse]
	getSubscription        *connect.Client[insightviewer.GetSubscriptionRequest, insightviewer.GetSubscriptionResponse]
	updateSubscription     *connect.Client[insightviewer.UpdateSubscriptionRequest, insightviewer.UpdateSubscriptionResponse]
	deleteSubscription     *connect.Client[insightviewer.DeleteSubscriptionRequest, insightviewer.DeleteSubscriptionResponse]
	getUserSubscriptions   *connect.Client[insightviewer.GetUserSubscriptionsRequest, insightviewer.GetUserSubscriptionsResponse]
	getReportSubscriptions *connect.Client[insightviewer.GetReportSubscriptionsRequest, insightviewer.GetReportSubscriptionsResponse]
}

// CreateSubscription calls
// insightviewer.api.v1.insightviewer.ReportSubscriptionService.CreateSubscription.
func (c *reportSubscriptionServiceClient) CreateSubscription(ctx context.Context, req *connect.Request[insightviewer.CreateSubscriptionRequest]) (*connect.Response[insightviewer.CreateSubscriptionResponse], error) {
	return c.createSubscription.CallUnary(ctx, req)
}

// GetSubscription calls
// insightviewer.api.v1.insightviewer.ReportSubscriptionService.GetSubscription.
func (c *reportSubscriptionServiceClient) GetSubscription(ctx context.Context, req *connect.Request[insightviewer.GetSubscriptionRequest]) (*connect.Response[insightviewer.GetSubscriptionResponse], error) {
	return c.getSubscription.CallUnary(ctx, req)
}

// UpdateSubscription calls
// insightviewer.api.v1.insightviewer.ReportSubscriptionService.UpdateSubscription.
func (c *reportSubscriptionServiceClient) UpdateSubscription(ctx context.Context, req *connect.Request[insightviewer.UpdateSubscriptionRequest]) (*connect.Response[insightviewer.UpdateSubscriptionResponse], error) {
	return c.updateSubscription.CallUnary(ctx, req)
}

// DeleteSubscription calls
// insightviewer.api.v1.insightviewer.ReportSubscriptionService.DeleteSubscription.
func (c *reportSubscriptionServiceClient) DeleteSubscription(ctx context.Context, req *connect.Request[insightviewer.DeleteSubscriptionRequest]) (*connect.Response[insightviewer.DeleteSubscriptionResponse], error) {
	return c.deleteSubscription.CallUnary(ctx, req)
}

// GetUserSubscriptions calls
// insightviewer.api.v1.insightviewer.ReportSubscriptionService.GetUserSubscriptions.
func (c *reportSubscriptionServiceClient) GetUserSubscriptions(ctx context.Context, req *connect.Request[insightviewer.GetUserSubscriptionsRequest]) (*connect.Response[insightviewer.GetUserSubscriptionsResponse], error) {
	return c.getUserSubscriptions.CallUnary(ctx, req)
}

// GetReportSubscriptions calls
// insightviewer.api.v1.insightviewer.ReportSubscriptionService.GetReportSubscriptions.
func (c *reportSubscriptionServiceClient) GetReportSubscriptions(ctx context.Context, req *connect.Request[insightviewer.GetReportSubscriptionsRequest]) (*connect.Response[insightviewer.GetReportSubscriptionsResponse], error) {
	return c.getReportSubscriptions.CallUnary(ctx, req)
}

// ReportSubscriptionServiceHandler is an implementation of the
// insightviewer.api.v1.insightviewer.ReportSubscriptionService service.
type ReportSubscriptionServiceHandler interface {
	// Subscription management
	CreateSubscription(context.Context, *connect.Request[insightviewer.CreateSubscriptionRequest]) (*connect.Response[insightviewer.CreateSubscriptionResponse], error)
	GetSubscription(context.Context, *connect.Request[insightviewer.GetSubscriptionRequest]) (*connect.Response[insightviewer.GetSubscriptionResponse], error)
	UpdateSubscription(context.Context, *connect.Request[insightviewer.UpdateSubscriptionRequest]) (*connect.Response[insightviewer.UpdateSubscriptionResponse], error)
	DeleteSubscription(context.Context, *connect.Request[insightviewer.DeleteSubscriptionRequest]) (*connect.Response[insightviewer.DeleteSubscriptionResponse], error)
	GetUserSubscriptions(context.Context, *connect.Request[insightviewer.GetUserSubscriptionsRequest]) (*connect.Response[insightviewer.GetUserSubscriptionsResponse], error)
	GetReportSubscriptions(context.Context, *connect.Request[insightviewer.GetReportSubscriptionsRequest]) (*connect.Response[insightviewer.GetReportSubscriptionsResponse], error)
}

// NewReportSubscriptionServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReportSubscriptionServiceHandler(svc ReportSubscriptionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reportSubscriptionServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportSubscriptionService").Methods()
	reportSubscriptionServiceCreateSubscriptionHandler := connect.NewUnaryHandler(
		ReportSubscriptionServiceCreateSubscriptionProcedure,
		svc.CreateSubscription,
		connect.WithSchema(reportSubscriptionServiceMethods.ByName("CreateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	reportSubscriptionServiceGetSubscriptionHandler := connect.NewUnaryHandler(
		ReportSubscriptionServiceGetSubscriptionProcedure,
		svc.GetSubscription,
		connect.WithSchema(reportSubscriptionServiceMethods.ByName("GetSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	reportSubscriptionServiceUpdateSubscriptionHandler := connect.NewUnaryHandler(
		ReportSubscriptionServiceUpdateSubscriptionProcedure,
		svc.UpdateSubscription,
		connect.WithSchema(reportSubscriptionServiceMethods.ByName("UpdateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	reportSubscriptionServiceDeleteSubscriptionHandler := connect.NewUnaryHandler(
		ReportSubscriptionServiceDeleteSubscriptionProcedure,
		svc.DeleteSubscription,
		connect.WithSchema(reportSubscriptionServiceMethods.ByName("DeleteSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	reportSubscriptionServiceGetUserSubscriptionsHandler := connect.NewUnaryHandler(
		ReportSubscriptionServiceGetUserSubscriptionsProcedure,
		svc.GetUserSubscriptions,
		connect.WithSchema(reportSubscriptionServiceMethods.ByName("GetUserSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	reportSubscriptionServiceGetReportSubscriptionsHandler := connect.NewUnaryHandler(
		ReportSubscriptionServiceGetReportSubscriptionsProcedure,
		svc.GetReportSubscriptions,
		connect.WithSchema(reportSubscriptionServiceMethods.ByName("GetReportSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/insightviewer.api.v1.insightviewer.ReportSubscriptionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReportSubscriptionServiceCreateSubscriptionProcedure:
			reportSubscriptionServiceCreateSubscriptionHandler.ServeHTTP(w, r)
		case ReportSubscriptionServiceGetSubscriptionProcedure:
			reportSubscriptionServiceGetSubscriptionHandler.ServeHTTP(w, r)
		case ReportSubscriptionServiceUpdateSubscriptionProcedure:
			reportSubscriptionServiceUpdateSubscriptionHandler.ServeHTTP(w, r)
		case ReportSubscriptionServiceDeleteSubscriptionProcedure:
			reportSubscriptionServiceDeleteSubscriptionHandler.ServeHTTP(w, r)
		case ReportSubscriptionServiceGetUserSubscriptionsProcedure:
			reportSubscriptionServiceGetUserSubscriptionsHandler.ServeHTTP(w, r)
		case ReportSubscriptionServiceGetReportSubscriptionsProcedure:
			reportSubscriptionServiceGetReportSubscriptionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReportSubscriptionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReportSubscriptionServiceHandler struct{}

func (UnimplementedReportSubscriptionServiceHandler) CreateSubscription(context.Context, *connect.Request[insightviewer.CreateSubscriptionRequest]) (*connect.Response[insightviewer.CreateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSubscriptionService.CreateSubscription is not implemented"))
}

func (UnimplementedReportSubscriptionServiceHandler) GetSubscription(context.Context, *connect.Request[insightviewer.GetSubscriptionRequest]) (*connect.Response[insightviewer.GetSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSubscriptionService.GetSubscription is not implemented"))
}

func (UnimplementedReportSubscriptionServiceHandler) UpdateSubscription(context.Context, *connect.Request[insightviewer.UpdateSubscriptionRequest]) (*connect.Response[insightviewer.UpdateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSubscriptionService.UpdateSubscription is not implemented"))
}

func (UnimplementedReportSubscriptionServiceHandler) DeleteSubscription(context.Context, *connect.Request[insightviewer.DeleteSubscriptionRequest]) (*connect.Response[insightviewer.DeleteSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSubscriptionService.DeleteSubscription is not implemented"))
}

func (UnimplementedReportSubscriptionServiceHandler) GetUserSubscriptions(context.Context, *connect.Request[insightviewer.GetUserSubscriptionsRequest]) (*connect.Response[insightviewer.GetUserSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSubscriptionService.GetUserSubscriptions is not implemented"))
}

func (UnimplementedReportSubscriptionServiceHandler) GetReportSubscriptions(context.Context, *connect.Request[insightviewer.GetReportSubscriptionsRequest]) (*connect.Response[insightviewer.GetReportSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportSubscriptionService.GetReportSubscriptions is not implemented"))
}

// ReportAlertsServiceClient is a client for the
// insightviewer.api.v1.insightviewer.ReportAlertsService service.
type ReportAlertsServiceClient interface {
	// Alert management
	CreateAlert(context.Context, *connect.Request[insightviewer.CreateAlertRequest]) (*connect.Response[insightviewer.CreateAlertResponse], error)
	GetAlert(context.Context, *connect.Request[insightviewer.GetAlertRequest]) (*connect.Response[insightviewer.GetAlertResponse], error)
	UpdateAlert(context.Context, *connect.Request[insightviewer.UpdateAlertRequest]) (*connect.Response[insightviewer.UpdateAlertResponse], error)
	DeleteAlert(context.Context, *connect.Request[insightviewer.DeleteAlertRequest]) (*connect.Response[insightviewer.DeleteAlertResponse], error)
	GetReportAlerts(context.Context, *connect.Request[insightviewer.GetReportAlertsRequest]) (*connect.Response[insightviewer.GetReportAlertsResponse], error)
	GetUserAlerts(context.Context, *connect.Request[insightviewer.GetUserAlertsRequest]) (*connect.Response[insightviewer.GetUserAlertsResponse], error)
	// Alert control
	EnableAlert(context.Context, *connect.Request[insightviewer.EnableAlertRequest]) (*connect.Response[insightviewer.EnableAlertResponse], error)
	DisableAlert(context.Context, *connect.Request[insightviewer.DisableAlertRequest]) (*connect.Response[insightviewer.DisableAlertResponse], error)
	TestAlert(context.Context, *connect.Request[insightviewer.TestAlertRequest]) (*connect.Response[insightviewer.TestAlertResponse], error)
}

// NewReportAlertsServiceClient constructs a client for the
// insightviewer.api.v1.insightviewer.ReportAlertsService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReportAlertsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReportAlertsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reportAlertsServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportAlertsService").Methods()
	return &reportAlertsServiceClient{
		createAlert: connect.NewClient[insightviewer.CreateAlertRequest, insightviewer.CreateAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceCreateAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("CreateAlert")),
			connect.WithClientOptions(opts...),
		),
		getAlert: connect.NewClient[insightviewer.GetAlertRequest, insightviewer.GetAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceGetAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("GetAlert")),
			connect.WithClientOptions(opts...),
		),
		updateAlert: connect.NewClient[insightviewer.UpdateAlertRequest, insightviewer.UpdateAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceUpdateAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("UpdateAlert")),
			connect.WithClientOptions(opts...),
		),
		deleteAlert: connect.NewClient[insightviewer.DeleteAlertRequest, insightviewer.DeleteAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceDeleteAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("DeleteAlert")),
			connect.WithClientOptions(opts...),
		),
		getReportAlerts: connect.NewClient[insightviewer.GetReportAlertsRequest, insightviewer.GetReportAlertsResponse](
			httpClient,
			baseURL+ReportAlertsServiceGetReportAlertsProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("GetReportAlerts")),
			connect.WithClientOptions(opts...),
		),
		getUserAlerts: connect.NewClient[insightviewer.GetUserAlertsRequest, insightviewer.GetUserAlertsResponse](
			httpClient,
			baseURL+ReportAlertsServiceGetUserAlertsProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("GetUserAlerts")),
			connect.WithClientOptions(opts...),
		),
		enableAlert: connect.NewClient[insightviewer.EnableAlertRequest, insightviewer.EnableAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceEnableAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("EnableAlert")),
			connect.WithClientOptions(opts...),
		),
		disableAlert: connect.NewClient[insightviewer.DisableAlertRequest, insightviewer.DisableAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceDisableAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("DisableAlert")),
			connect.WithClientOptions(opts...),
		),
		testAlert: connect.NewClient[insightviewer.TestAlertRequest, insightviewer.TestAlertResponse](
			httpClient,
			baseURL+ReportAlertsServiceTestAlertProcedure,
			connect.WithSchema(reportAlertsServiceMethods.ByName("TestAlert")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reportAlertsServiceClient implements ReportAlertsServiceClient.
type reportAlertsServiceClient struct {
	createAlert     *connect.Client[insightviewer.CreateAlertRequest, insightviewer.CreateAlertResponse]
	getAlert        *connect.Client[insightviewer.GetAlertRequest, insightviewer.GetAlertResponse]
	updateAlert     *connect.Client[insightviewer.UpdateAlertRequest, insightviewer.UpdateAlertResponse]
	deleteAlert     *connect.Client[insightviewer.DeleteAlertRequest, insightviewer.DeleteAlertResponse]
	getReportAlerts *connect.Client[insightviewer.GetReportAlertsRequest, insightviewer.GetReportAlertsResponse]
	getUserAlerts   *connect.Client[insightviewer.GetUserAlertsRequest, insightviewer.GetUserAlertsResponse]
	enableAlert     *connect.Client[insightviewer.EnableAlertRequest, insightviewer.EnableAlertResponse]
	disableAlert    *connect.Client[insightviewer.DisableAlertRequest, insightviewer.DisableAlertResponse]
	testAlert       *connect.Client[insightviewer.TestAlertRequest, insightviewer.TestAlertResponse]
}

// CreateAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.CreateAlert.
func (c *reportAlertsServiceClient) CreateAlert(ctx context.Context, req *connect.Request[insightviewer.CreateAlertRequest]) (*connect.Response[insightviewer.CreateAlertResponse], error) {
	return c.createAlert.CallUnary(ctx, req)
}

// GetAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.GetAlert.
func (c *reportAlertsServiceClient) GetAlert(ctx context.Context, req *connect.Request[insightviewer.GetAlertRequest]) (*connect.Response[insightviewer.GetAlertResponse], error) {
	return c.getAlert.CallUnary(ctx, req)
}

// UpdateAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.UpdateAlert.
func (c *reportAlertsServiceClient) UpdateAlert(ctx context.Context, req *connect.Request[insightviewer.UpdateAlertRequest]) (*connect.Response[insightviewer.UpdateAlertResponse], error) {
	return c.updateAlert.CallUnary(ctx, req)
}

// DeleteAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.DeleteAlert.
func (c *reportAlertsServiceClient) DeleteAlert(ctx context.Context, req *connect.Request[insightviewer.DeleteAlertRequest]) (*connect.Response[insightviewer.DeleteAlertResponse], error) {
	return c.deleteAlert.CallUnary(ctx, req)
}

// GetReportAlerts calls insightviewer.api.v1.insightviewer.ReportAlertsService.GetReportAlerts.
func (c *reportAlertsServiceClient) GetReportAlerts(ctx context.Context, req *connect.Request[insightviewer.GetReportAlertsRequest]) (*connect.Response[insightviewer.GetReportAlertsResponse], error) {
	return c.getReportAlerts.CallUnary(ctx, req)
}

// GetUserAlerts calls insightviewer.api.v1.insightviewer.ReportAlertsService.GetUserAlerts.
func (c *reportAlertsServiceClient) GetUserAlerts(ctx context.Context, req *connect.Request[insightviewer.GetUserAlertsRequest]) (*connect.Response[insightviewer.GetUserAlertsResponse], error) {
	return c.getUserAlerts.CallUnary(ctx, req)
}

// EnableAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.EnableAlert.
func (c *reportAlertsServiceClient) EnableAlert(ctx context.Context, req *connect.Request[insightviewer.EnableAlertRequest]) (*connect.Response[insightviewer.EnableAlertResponse], error) {
	return c.enableAlert.CallUnary(ctx, req)
}

// DisableAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.DisableAlert.
func (c *reportAlertsServiceClient) DisableAlert(ctx context.Context, req *connect.Request[insightviewer.DisableAlertRequest]) (*connect.Response[insightviewer.DisableAlertResponse], error) {
	return c.disableAlert.CallUnary(ctx, req)
}

// TestAlert calls insightviewer.api.v1.insightviewer.ReportAlertsService.TestAlert.
func (c *reportAlertsServiceClient) TestAlert(ctx context.Context, req *connect.Request[insightviewer.TestAlertRequest]) (*connect.Response[insightviewer.TestAlertResponse], error) {
	return c.testAlert.CallUnary(ctx, req)
}

// ReportAlertsServiceHandler is an implementation of the
// insightviewer.api.v1.insightviewer.ReportAlertsService service.
type ReportAlertsServiceHandler interface {
	// Alert management
	CreateAlert(context.Context, *connect.Request[insightviewer.CreateAlertRequest]) (*connect.Response[insightviewer.CreateAlertResponse], error)
	GetAlert(context.Context, *connect.Request[insightviewer.GetAlertRequest]) (*connect.Response[insightviewer.GetAlertResponse], error)
	UpdateAlert(context.Context, *connect.Request[insightviewer.UpdateAlertRequest]) (*connect.Response[insightviewer.UpdateAlertResponse], error)
	DeleteAlert(context.Context, *connect.Request[insightviewer.DeleteAlertRequest]) (*connect.Response[insightviewer.DeleteAlertResponse], error)
	GetReportAlerts(context.Context, *connect.Request[insightviewer.GetReportAlertsRequest]) (*connect.Response[insightviewer.GetReportAlertsResponse], error)
	GetUserAlerts(context.Context, *connect.Request[insightviewer.GetUserAlertsRequest]) (*connect.Response[insightviewer.GetUserAlertsResponse], error)
	// Alert control
	EnableAlert(context.Context, *connect.Request[insightviewer.EnableAlertRequest]) (*connect.Response[insightviewer.EnableAlertResponse], error)
	DisableAlert(context.Context, *connect.Request[insightviewer.DisableAlertRequest]) (*connect.Response[insightviewer.DisableAlertResponse], error)
	TestAlert(context.Context, *connect.Request[insightviewer.TestAlertRequest]) (*connect.Response[insightviewer.TestAlertResponse], error)
}

// NewReportAlertsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReportAlertsServiceHandler(svc ReportAlertsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reportAlertsServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("ReportAlertsService").Methods()
	reportAlertsServiceCreateAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceCreateAlertProcedure,
		svc.CreateAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("CreateAlert")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceGetAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceGetAlertProcedure,
		svc.GetAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("GetAlert")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceUpdateAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceUpdateAlertProcedure,
		svc.UpdateAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("UpdateAlert")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceDeleteAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceDeleteAlertProcedure,
		svc.DeleteAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("DeleteAlert")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceGetReportAlertsHandler := connect.NewUnaryHandler(
		ReportAlertsServiceGetReportAlertsProcedure,
		svc.GetReportAlerts,
		connect.WithSchema(reportAlertsServiceMethods.ByName("GetReportAlerts")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceGetUserAlertsHandler := connect.NewUnaryHandler(
		ReportAlertsServiceGetUserAlertsProcedure,
		svc.GetUserAlerts,
		connect.WithSchema(reportAlertsServiceMethods.ByName("GetUserAlerts")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceEnableAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceEnableAlertProcedure,
		svc.EnableAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("EnableAlert")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceDisableAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceDisableAlertProcedure,
		svc.DisableAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("DisableAlert")),
		connect.WithHandlerOptions(opts...),
	)
	reportAlertsServiceTestAlertHandler := connect.NewUnaryHandler(
		ReportAlertsServiceTestAlertProcedure,
		svc.TestAlert,
		connect.WithSchema(reportAlertsServiceMethods.ByName("TestAlert")),
		connect.WithHandlerOptions(opts...),
	)
	return "/insightviewer.api.v1.insightviewer.ReportAlertsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReportAlertsServiceCreateAlertProcedure:
			reportAlertsServiceCreateAlertHandler.ServeHTTP(w, r)
		case ReportAlertsServiceGetAlertProcedure:
			reportAlertsServiceGetAlertHandler.ServeHTTP(w, r)
		case ReportAlertsServiceUpdateAlertProcedure:
			reportAlertsServiceUpdateAlertHandler.ServeHTTP(w, r)
		case ReportAlertsServiceDeleteAlertProcedure:
			reportAlertsServiceDeleteAlertHandler.ServeHTTP(w, r)
		case ReportAlertsServiceGetReportAlertsProcedure:
			reportAlertsServiceGetReportAlertsHandler.ServeHTTP(w, r)
		case ReportAlertsServiceGetUserAlertsProcedure:
			reportAlertsServiceGetUserAlertsHandler.ServeHTTP(w, r)
		case ReportAlertsServiceEnableAlertProcedure:
			reportAlertsServiceEnableAlertHandler.ServeHTTP(w, r)
		case ReportAlertsServiceDisableAlertProcedure:
			reportAlertsServiceDisableAlertHandler.ServeHTTP(w, r)
		case ReportAlertsServiceTestAlertProcedure:
			reportAlertsServiceTestAlertHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReportAlertsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReportAlertsServiceHandler struct{}

func (UnimplementedReportAlertsServiceHandler) CreateAlert(context.Context, *connect.Request[insightviewer.CreateAlertRequest]) (*connect.Response[insightviewer.CreateAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.CreateAlert is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) GetAlert(context.Context, *connect.Request[insightviewer.GetAlertRequest]) (*connect.Response[insightviewer.GetAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.GetAlert is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) UpdateAlert(context.Context, *connect.Request[insightviewer.UpdateAlertRequest]) (*connect.Response[insightviewer.UpdateAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.UpdateAlert is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) DeleteAlert(context.Context, *connect.Request[insightviewer.DeleteAlertRequest]) (*connect.Response[insightviewer.DeleteAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.DeleteAlert is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) GetReportAlerts(context.Context, *connect.Request[insightviewer.GetReportAlertsRequest]) (*connect.Response[insightviewer.GetReportAlertsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.GetReportAlerts is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) GetUserAlerts(context.Context, *connect.Request[insightviewer.GetUserAlertsRequest]) (*connect.Response[insightviewer.GetUserAlertsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.GetUserAlerts is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) EnableAlert(context.Context, *connect.Request[insightviewer.EnableAlertRequest]) (*connect.Response[insightviewer.EnableAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.EnableAlert is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) DisableAlert(context.Context, *connect.Request[insightviewer.DisableAlertRequest]) (*connect.Response[insightviewer.DisableAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.DisableAlert is not implemented"))
}

func (UnimplementedReportAlertsServiceHandler) TestAlert(context.Context, *connect.Request[insightviewer.TestAlertRequest]) (*connect.Response[insightviewer.TestAlertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.ReportAlertsService.TestAlert is not implemented"))
}

// CacheServiceClient is a client for the insightviewer.api.v1.insightviewer.CacheService service.
type CacheServiceClient interface {
	// Cache operations
	GetCachedResult(context.Context, *connect.Request[insightviewer.GetCachedResultRequest]) (*connect.Response[insightviewer.GetCachedResultResponse], error)
	InvalidateCache(context.Context, *connect.Request[insightviewer.InvalidateCacheRequest]) (*connect.Response[insightviewer.InvalidateCacheResponse], error)
	GetCacheStatistics(context.Context, *connect.Request[insightviewer.GetCacheStatisticsRequest]) (*connect.Response[insightviewer.GetCacheStatisticsResponse], error)
	CleanupCache(context.Context, *connect.Request[insightviewer.CleanupCacheRequest]) (*connect.Response[insightviewer.CleanupCacheResponse], error)
}

// NewCacheServiceClient constructs a client for the insightviewer.api.v1.insightviewer.CacheService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCacheServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CacheServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cacheServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("CacheService").Methods()
	return &cacheServiceClient{
		getCachedResult: connect.NewClient[insightviewer.GetCachedResultRequest, insightviewer.GetCachedResultResponse](
			httpClient,
			baseURL+CacheServiceGetCachedResultProcedure,
			connect.WithSchema(cacheServiceMethods.ByName("GetCachedResult")),
			connect.WithClientOptions(opts...),
		),
		invalidateCache: connect.NewClient[insightviewer.InvalidateCacheRequest, insightviewer.InvalidateCacheResponse](
			httpClient,
			baseURL+CacheServiceInvalidateCacheProcedure,
			connect.WithSchema(cacheServiceMethods.ByName("InvalidateCache")),
			connect.WithClientOptions(opts...),
		),
		getCacheStatistics: connect.NewClient[insightviewer.GetCacheStatisticsRequest, insightviewer.GetCacheStatisticsResponse](
			httpClient,
			baseURL+CacheServiceGetCacheStatisticsProcedure,
			connect.WithSchema(cacheServiceMethods.ByName("GetCacheStatistics")),
			connect.WithClientOptions(opts...),
		),
		cleanupCache: connect.NewClient[insightviewer.CleanupCacheRequest, insightviewer.CleanupCacheResponse](
			httpClient,
			baseURL+CacheServiceCleanupCacheProcedure,
			connect.WithSchema(cacheServiceMethods.ByName("CleanupCache")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cacheServiceClient implements CacheServiceClient.
type cacheServiceClient struct {
	getCachedResult    *connect.Client[insightviewer.GetCachedResultRequest, insightviewer.GetCachedResultResponse]
	invalidateCache    *connect.Client[insightviewer.InvalidateCacheRequest, insightviewer.InvalidateCacheResponse]
	getCacheStatistics *connect.Client[insightviewer.GetCacheStatisticsRequest, insightviewer.GetCacheStatisticsResponse]
	cleanupCache       *connect.Client[insightviewer.CleanupCacheRequest, insightviewer.CleanupCacheResponse]
}

// GetCachedResult calls insightviewer.api.v1.insightviewer.CacheService.GetCachedResult.
func (c *cacheServiceClient) GetCachedResult(ctx context.Context, req *connect.Request[insightviewer.GetCachedResultRequest]) (*connect.Response[insightviewer.GetCachedResultResponse], error) {
	return c.getCachedResult.CallUnary(ctx, req)
}

// InvalidateCache calls insightviewer.api.v1.insightviewer.CacheService.InvalidateCache.
func (c *cacheServiceClient) InvalidateCache(ctx context.Context, req *connect.Request[insightviewer.InvalidateCacheRequest]) (*connect.Response[insightviewer.InvalidateCacheResponse], error) {
	return c.invalidateCache.CallUnary(ctx, req)
}

// GetCacheStatistics calls insightviewer.api.v1.insightviewer.CacheService.GetCacheStatistics.
func (c *cacheServiceClient) GetCacheStatistics(ctx context.Context, req *connect.Request[insightviewer.GetCacheStatisticsRequest]) (*connect.Response[insightviewer.GetCacheStatisticsResponse], error) {
	return c.getCacheStatistics.CallUnary(ctx, req)
}

// CleanupCache calls insightviewer.api.v1.insightviewer.CacheService.CleanupCache.
func (c *cacheServiceClient) CleanupCache(ctx context.Context, req *connect.Request[insightviewer.CleanupCacheRequest]) (*connect.Response[insightviewer.CleanupCacheResponse], error) {
	return c.cleanupCache.CallUnary(ctx, req)
}

// CacheServiceHandler is an implementation of the insightviewer.api.v1.insightviewer.CacheService
// service.
type CacheServiceHandler interface {
	// Cache operations
	GetCachedResult(context.Context, *connect.Request[insightviewer.GetCachedResultRequest]) (*connect.Response[insightviewer.GetCachedResultResponse], error)
	InvalidateCache(context.Context, *connect.Request[insightviewer.InvalidateCacheRequest]) (*connect.Response[insightviewer.InvalidateCacheResponse], error)
	GetCacheStatistics(context.Context, *connect.Request[insightviewer.GetCacheStatisticsRequest]) (*connect.Response[insightviewer.GetCacheStatisticsResponse], error)
	CleanupCache(context.Context, *connect.Request[insightviewer.CleanupCacheRequest]) (*connect.Response[insightviewer.CleanupCacheResponse], error)
}

// NewCacheServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCacheServiceHandler(svc CacheServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cacheServiceMethods := insightviewer.File_insightviewer_proto_insightviewer_proto.Services().ByName("CacheService").Methods()
	cacheServiceGetCachedResultHandler := connect.NewUnaryHandler(
		CacheServiceGetCachedResultProcedure,
		svc.GetCachedResult,
		connect.WithSchema(cacheServiceMethods.ByName("GetCachedResult")),
		connect.WithHandlerOptions(opts...),
	)
	cacheServiceInvalidateCacheHandler := connect.NewUnaryHandler(
		CacheServiceInvalidateCacheProcedure,
		svc.InvalidateCache,
		connect.WithSchema(cacheServiceMethods.ByName("InvalidateCache")),
		connect.WithHandlerOptions(opts...),
	)
	cacheServiceGetCacheStatisticsHandler := connect.NewUnaryHandler(
		CacheServiceGetCacheStatisticsProcedure,
		svc.GetCacheStatistics,
		connect.WithSchema(cacheServiceMethods.ByName("GetCacheStatistics")),
		connect.WithHandlerOptions(opts...),
	)
	cacheServiceCleanupCacheHandler := connect.NewUnaryHandler(
		CacheServiceCleanupCacheProcedure,
		svc.CleanupCache,
		connect.WithSchema(cacheServiceMethods.ByName("CleanupCache")),
		connect.WithHandlerOptions(opts...),
	)
	return "/insightviewer.api.v1.insightviewer.CacheService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CacheServiceGetCachedResultProcedure:
			cacheServiceGetCachedResultHandler.ServeHTTP(w, r)
		case CacheServiceInvalidateCacheProcedure:
			cacheServiceInvalidateCacheHandler.ServeHTTP(w, r)
		case CacheServiceGetCacheStatisticsProcedure:
			cacheServiceGetCacheStatisticsHandler.ServeHTTP(w, r)
		case CacheServiceCleanupCacheProcedure:
			cacheServiceCleanupCacheHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCacheServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCacheServiceHandler struct{}

func (UnimplementedCacheServiceHandler) GetCachedResult(context.Context, *connect.Request[insightviewer.GetCachedResultRequest]) (*connect.Response[insightviewer.GetCachedResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.CacheService.GetCachedResult is not implemented"))
}

func (UnimplementedCacheServiceHandler) InvalidateCache(context.Context, *connect.Request[insightviewer.InvalidateCacheRequest]) (*connect.Response[insightviewer.InvalidateCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.CacheService.InvalidateCache is not implemented"))
}

func (UnimplementedCacheServiceHandler) GetCacheStatistics(context.Context, *connect.Request[insightviewer.GetCacheStatisticsRequest]) (*connect.Response[insightviewer.GetCacheStatisticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.CacheService.GetCacheStatistics is not implemented"))
}

func (UnimplementedCacheServiceHandler) CleanupCache(context.Context, *connect.Request[insightviewer.CleanupCacheRequest]) (*connect.Response[insightviewer.CleanupCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("insightviewer.api.v1.insightviewer.CacheService.CleanupCache is not implemented"))
}
