// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/user/proto/user_tenant.proto

package user_tenantconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	user_tenant "p9e.in/ugcl/identity/user/api/v2/user_tenant"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserTenantServiceName is the fully-qualified name of the UserTenantService service.
	UserTenantServiceName = "identity.user.api.v2.user_tenant.UserTenantService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserTenantServiceAssignUserToTenantProcedure is the fully-qualified name of the
	// UserTenantService's AssignUserToTenant RPC.
	UserTenantServiceAssignUserToTenantProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/AssignUserToTenant"
	// UserTenantServiceRemoveUserFromTenantProcedure is the fully-qualified name of the
	// UserTenantService's RemoveUserFromTenant RPC.
	UserTenantServiceRemoveUserFromTenantProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/RemoveUserFromTenant"
	// UserTenantServiceUpdateUserTenantRoleProcedure is the fully-qualified name of the
	// UserTenantService's UpdateUserTenantRole RPC.
	UserTenantServiceUpdateUserTenantRoleProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/UpdateUserTenantRole"
	// UserTenantServiceGetUserTenantsProcedure is the fully-qualified name of the UserTenantService's
	// GetUserTenants RPC.
	UserTenantServiceGetUserTenantsProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/GetUserTenants"
	// UserTenantServiceGetTenantUsersProcedure is the fully-qualified name of the UserTenantService's
	// GetTenantUsers RPC.
	UserTenantServiceGetTenantUsersProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/GetTenantUsers"
	// UserTenantServiceCheckUserTenantAccessProcedure is the fully-qualified name of the
	// UserTenantService's CheckUserTenantAccess RPC.
	UserTenantServiceCheckUserTenantAccessProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/CheckUserTenantAccess"
	// UserTenantServiceBulkAssignUsersToTenantProcedure is the fully-qualified name of the
	// UserTenantService's BulkAssignUsersToTenant RPC.
	UserTenantServiceBulkAssignUsersToTenantProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/BulkAssignUsersToTenant"
	// UserTenantServiceBulkRemoveUsersFromTenantProcedure is the fully-qualified name of the
	// UserTenantService's BulkRemoveUsersFromTenant RPC.
	UserTenantServiceBulkRemoveUsersFromTenantProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/BulkRemoveUsersFromTenant"
	// UserTenantServiceGetUserTenantHistoryProcedure is the fully-qualified name of the
	// UserTenantService's GetUserTenantHistory RPC.
	UserTenantServiceGetUserTenantHistoryProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/GetUserTenantHistory"
	// UserTenantServiceTransferUserBetweenTenantsProcedure is the fully-qualified name of the
	// UserTenantService's TransferUserBetweenTenants RPC.
	UserTenantServiceTransferUserBetweenTenantsProcedure = "/identity.user.api.v2.user_tenant.UserTenantService/TransferUserBetweenTenants"
)

// UserTenantServiceClient is a client for the identity.user.api.v2.user_tenant.UserTenantService
// service.
type UserTenantServiceClient interface {
	// Tenant Assignment
	AssignUserToTenant(context.Context, *connect.Request[user_tenant.AssignUserToTenantRequest]) (*connect.Response[emptypb.Empty], error)
	RemoveUserFromTenant(context.Context, *connect.Request[user_tenant.RemoveUserFromTenantRequest]) (*connect.Response[emptypb.Empty], error)
	UpdateUserTenantRole(context.Context, *connect.Request[user_tenant.UpdateUserTenantRoleRequest]) (*connect.Response[emptypb.Empty], error)
	// User-Tenant Queries
	GetUserTenants(context.Context, *connect.Request[user_tenant.GetUserTenantsRequest]) (*connect.Response[user_tenant.GetUserTenantsResponse], error)
	GetTenantUsers(context.Context, *connect.Request[user_tenant.GetTenantUsersRequest]) (*connect.Response[user_tenant.GetTenantUsersResponse], error)
	CheckUserTenantAccess(context.Context, *connect.Request[user_tenant.CheckUserTenantAccessRequest]) (*connect.Response[user_tenant.CheckUserTenantAccessResponse], error)
	// Bulk Operations
	BulkAssignUsersToTenant(context.Context, *connect.Request[user_tenant.BulkAssignUsersToTenantRequest]) (*connect.Response[user_tenant.BulkAssignUsersToTenantResponse], error)
	BulkRemoveUsersFromTenant(context.Context, *connect.Request[user_tenant.BulkRemoveUsersFromTenantRequest]) (*connect.Response[user_tenant.BulkRemoveUsersFromTenantResponse], error)
	// User-Tenant History
	GetUserTenantHistory(context.Context, *connect.Request[user_tenant.GetUserTenantHistoryRequest]) (*connect.Response[user_tenant.GetUserTenantHistoryResponse], error)
	// Transfer Operations
	TransferUserBetweenTenants(context.Context, *connect.Request[user_tenant.TransferUserBetweenTenantsRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewUserTenantServiceClient constructs a client for the
// identity.user.api.v2.user_tenant.UserTenantService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserTenantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserTenantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userTenantServiceMethods := user_tenant.File_identity_user_proto_user_tenant_proto.Services().ByName("UserTenantService").Methods()
	return &userTenantServiceClient{
		assignUserToTenant: connect.NewClient[user_tenant.AssignUserToTenantRequest, emptypb.Empty](
			httpClient,
			baseURL+UserTenantServiceAssignUserToTenantProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("AssignUserToTenant")),
			connect.WithClientOptions(opts...),
		),
		removeUserFromTenant: connect.NewClient[user_tenant.RemoveUserFromTenantRequest, emptypb.Empty](
			httpClient,
			baseURL+UserTenantServiceRemoveUserFromTenantProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("RemoveUserFromTenant")),
			connect.WithClientOptions(opts...),
		),
		updateUserTenantRole: connect.NewClient[user_tenant.UpdateUserTenantRoleRequest, emptypb.Empty](
			httpClient,
			baseURL+UserTenantServiceUpdateUserTenantRoleProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("UpdateUserTenantRole")),
			connect.WithClientOptions(opts...),
		),
		getUserTenants: connect.NewClient[user_tenant.GetUserTenantsRequest, user_tenant.GetUserTenantsResponse](
			httpClient,
			baseURL+UserTenantServiceGetUserTenantsProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("GetUserTenants")),
			connect.WithClientOptions(opts...),
		),
		getTenantUsers: connect.NewClient[user_tenant.GetTenantUsersRequest, user_tenant.GetTenantUsersResponse](
			httpClient,
			baseURL+UserTenantServiceGetTenantUsersProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("GetTenantUsers")),
			connect.WithClientOptions(opts...),
		),
		checkUserTenantAccess: connect.NewClient[user_tenant.CheckUserTenantAccessRequest, user_tenant.CheckUserTenantAccessResponse](
			httpClient,
			baseURL+UserTenantServiceCheckUserTenantAccessProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("CheckUserTenantAccess")),
			connect.WithClientOptions(opts...),
		),
		bulkAssignUsersToTenant: connect.NewClient[user_tenant.BulkAssignUsersToTenantRequest, user_tenant.BulkAssignUsersToTenantResponse](
			httpClient,
			baseURL+UserTenantServiceBulkAssignUsersToTenantProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("BulkAssignUsersToTenant")),
			connect.WithClientOptions(opts...),
		),
		bulkRemoveUsersFromTenant: connect.NewClient[user_tenant.BulkRemoveUsersFromTenantRequest, user_tenant.BulkRemoveUsersFromTenantResponse](
			httpClient,
			baseURL+UserTenantServiceBulkRemoveUsersFromTenantProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("BulkRemoveUsersFromTenant")),
			connect.WithClientOptions(opts...),
		),
		getUserTenantHistory: connect.NewClient[user_tenant.GetUserTenantHistoryRequest, user_tenant.GetUserTenantHistoryResponse](
			httpClient,
			baseURL+UserTenantServiceGetUserTenantHistoryProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("GetUserTenantHistory")),
			connect.WithClientOptions(opts...),
		),
		transferUserBetweenTenants: connect.NewClient[user_tenant.TransferUserBetweenTenantsRequest, emptypb.Empty](
			httpClient,
			baseURL+UserTenantServiceTransferUserBetweenTenantsProcedure,
			connect.WithSchema(userTenantServiceMethods.ByName("TransferUserBetweenTenants")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userTenantServiceClient implements UserTenantServiceClient.
type userTenantServiceClient struct {
	assignUserToTenant         *connect.Client[user_tenant.AssignUserToTenantRequest, emptypb.Empty]
	removeUserFromTenant       *connect.Client[user_tenant.RemoveUserFromTenantRequest, emptypb.Empty]
	updateUserTenantRole       *connect.Client[user_tenant.UpdateUserTenantRoleRequest, emptypb.Empty]
	getUserTenants             *connect.Client[user_tenant.GetUserTenantsRequest, user_tenant.GetUserTenantsResponse]
	getTenantUsers             *connect.Client[user_tenant.GetTenantUsersRequest, user_tenant.GetTenantUsersResponse]
	checkUserTenantAccess      *connect.Client[user_tenant.CheckUserTenantAccessRequest, user_tenant.CheckUserTenantAccessResponse]
	bulkAssignUsersToTenant    *connect.Client[user_tenant.BulkAssignUsersToTenantRequest, user_tenant.BulkAssignUsersToTenantResponse]
	bulkRemoveUsersFromTenant  *connect.Client[user_tenant.BulkRemoveUsersFromTenantRequest, user_tenant.BulkRemoveUsersFromTenantResponse]
	getUserTenantHistory       *connect.Client[user_tenant.GetUserTenantHistoryRequest, user_tenant.GetUserTenantHistoryResponse]
	transferUserBetweenTenants *connect.Client[user_tenant.TransferUserBetweenTenantsRequest, emptypb.Empty]
}

// AssignUserToTenant calls identity.user.api.v2.user_tenant.UserTenantService.AssignUserToTenant.
func (c *userTenantServiceClient) AssignUserToTenant(ctx context.Context, req *connect.Request[user_tenant.AssignUserToTenantRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.assignUserToTenant.CallUnary(ctx, req)
}

// RemoveUserFromTenant calls
// identity.user.api.v2.user_tenant.UserTenantService.RemoveUserFromTenant.
func (c *userTenantServiceClient) RemoveUserFromTenant(ctx context.Context, req *connect.Request[user_tenant.RemoveUserFromTenantRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.removeUserFromTenant.CallUnary(ctx, req)
}

// UpdateUserTenantRole calls
// identity.user.api.v2.user_tenant.UserTenantService.UpdateUserTenantRole.
func (c *userTenantServiceClient) UpdateUserTenantRole(ctx context.Context, req *connect.Request[user_tenant.UpdateUserTenantRoleRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.updateUserTenantRole.CallUnary(ctx, req)
}

// GetUserTenants calls identity.user.api.v2.user_tenant.UserTenantService.GetUserTenants.
func (c *userTenantServiceClient) GetUserTenants(ctx context.Context, req *connect.Request[user_tenant.GetUserTenantsRequest]) (*connect.Response[user_tenant.GetUserTenantsResponse], error) {
	return c.getUserTenants.CallUnary(ctx, req)
}

// GetTenantUsers calls identity.user.api.v2.user_tenant.UserTenantService.GetTenantUsers.
func (c *userTenantServiceClient) GetTenantUsers(ctx context.Context, req *connect.Request[user_tenant.GetTenantUsersRequest]) (*connect.Response[user_tenant.GetTenantUsersResponse], error) {
	return c.getTenantUsers.CallUnary(ctx, req)
}

// CheckUserTenantAccess calls
// identity.user.api.v2.user_tenant.UserTenantService.CheckUserTenantAccess.
func (c *userTenantServiceClient) CheckUserTenantAccess(ctx context.Context, req *connect.Request[user_tenant.CheckUserTenantAccessRequest]) (*connect.Response[user_tenant.CheckUserTenantAccessResponse], error) {
	return c.checkUserTenantAccess.CallUnary(ctx, req)
}

// BulkAssignUsersToTenant calls
// identity.user.api.v2.user_tenant.UserTenantService.BulkAssignUsersToTenant.
func (c *userTenantServiceClient) BulkAssignUsersToTenant(ctx context.Context, req *connect.Request[user_tenant.BulkAssignUsersToTenantRequest]) (*connect.Response[user_tenant.BulkAssignUsersToTenantResponse], error) {
	return c.bulkAssignUsersToTenant.CallUnary(ctx, req)
}

// BulkRemoveUsersFromTenant calls
// identity.user.api.v2.user_tenant.UserTenantService.BulkRemoveUsersFromTenant.
func (c *userTenantServiceClient) BulkRemoveUsersFromTenant(ctx context.Context, req *connect.Request[user_tenant.BulkRemoveUsersFromTenantRequest]) (*connect.Response[user_tenant.BulkRemoveUsersFromTenantResponse], error) {
	return c.bulkRemoveUsersFromTenant.CallUnary(ctx, req)
}

// GetUserTenantHistory calls
// identity.user.api.v2.user_tenant.UserTenantService.GetUserTenantHistory.
func (c *userTenantServiceClient) GetUserTenantHistory(ctx context.Context, req *connect.Request[user_tenant.GetUserTenantHistoryRequest]) (*connect.Response[user_tenant.GetUserTenantHistoryResponse], error) {
	return c.getUserTenantHistory.CallUnary(ctx, req)
}

// TransferUserBetweenTenants calls
// identity.user.api.v2.user_tenant.UserTenantService.TransferUserBetweenTenants.
func (c *userTenantServiceClient) TransferUserBetweenTenants(ctx context.Context, req *connect.Request[user_tenant.TransferUserBetweenTenantsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.transferUserBetweenTenants.CallUnary(ctx, req)
}

// UserTenantServiceHandler is an implementation of the
// identity.user.api.v2.user_tenant.UserTenantService service.
type UserTenantServiceHandler interface {
	// Tenant Assignment
	AssignUserToTenant(context.Context, *connect.Request[user_tenant.AssignUserToTenantRequest]) (*connect.Response[emptypb.Empty], error)
	RemoveUserFromTenant(context.Context, *connect.Request[user_tenant.RemoveUserFromTenantRequest]) (*connect.Response[emptypb.Empty], error)
	UpdateUserTenantRole(context.Context, *connect.Request[user_tenant.UpdateUserTenantRoleRequest]) (*connect.Response[emptypb.Empty], error)
	// User-Tenant Queries
	GetUserTenants(context.Context, *connect.Request[user_tenant.GetUserTenantsRequest]) (*connect.Response[user_tenant.GetUserTenantsResponse], error)
	GetTenantUsers(context.Context, *connect.Request[user_tenant.GetTenantUsersRequest]) (*connect.Response[user_tenant.GetTenantUsersResponse], error)
	CheckUserTenantAccess(context.Context, *connect.Request[user_tenant.CheckUserTenantAccessRequest]) (*connect.Response[user_tenant.CheckUserTenantAccessResponse], error)
	// Bulk Operations
	BulkAssignUsersToTenant(context.Context, *connect.Request[user_tenant.BulkAssignUsersToTenantRequest]) (*connect.Response[user_tenant.BulkAssignUsersToTenantResponse], error)
	BulkRemoveUsersFromTenant(context.Context, *connect.Request[user_tenant.BulkRemoveUsersFromTenantRequest]) (*connect.Response[user_tenant.BulkRemoveUsersFromTenantResponse], error)
	// User-Tenant History
	GetUserTenantHistory(context.Context, *connect.Request[user_tenant.GetUserTenantHistoryRequest]) (*connect.Response[user_tenant.GetUserTenantHistoryResponse], error)
	// Transfer Operations
	TransferUserBetweenTenants(context.Context, *connect.Request[user_tenant.TransferUserBetweenTenantsRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewUserTenantServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserTenantServiceHandler(svc UserTenantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userTenantServiceMethods := user_tenant.File_identity_user_proto_user_tenant_proto.Services().ByName("UserTenantService").Methods()
	userTenantServiceAssignUserToTenantHandler := connect.NewUnaryHandler(
		UserTenantServiceAssignUserToTenantProcedure,
		svc.AssignUserToTenant,
		connect.WithSchema(userTenantServiceMethods.ByName("AssignUserToTenant")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceRemoveUserFromTenantHandler := connect.NewUnaryHandler(
		UserTenantServiceRemoveUserFromTenantProcedure,
		svc.RemoveUserFromTenant,
		connect.WithSchema(userTenantServiceMethods.ByName("RemoveUserFromTenant")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceUpdateUserTenantRoleHandler := connect.NewUnaryHandler(
		UserTenantServiceUpdateUserTenantRoleProcedure,
		svc.UpdateUserTenantRole,
		connect.WithSchema(userTenantServiceMethods.ByName("UpdateUserTenantRole")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceGetUserTenantsHandler := connect.NewUnaryHandler(
		UserTenantServiceGetUserTenantsProcedure,
		svc.GetUserTenants,
		connect.WithSchema(userTenantServiceMethods.ByName("GetUserTenants")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceGetTenantUsersHandler := connect.NewUnaryHandler(
		UserTenantServiceGetTenantUsersProcedure,
		svc.GetTenantUsers,
		connect.WithSchema(userTenantServiceMethods.ByName("GetTenantUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceCheckUserTenantAccessHandler := connect.NewUnaryHandler(
		UserTenantServiceCheckUserTenantAccessProcedure,
		svc.CheckUserTenantAccess,
		connect.WithSchema(userTenantServiceMethods.ByName("CheckUserTenantAccess")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceBulkAssignUsersToTenantHandler := connect.NewUnaryHandler(
		UserTenantServiceBulkAssignUsersToTenantProcedure,
		svc.BulkAssignUsersToTenant,
		connect.WithSchema(userTenantServiceMethods.ByName("BulkAssignUsersToTenant")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceBulkRemoveUsersFromTenantHandler := connect.NewUnaryHandler(
		UserTenantServiceBulkRemoveUsersFromTenantProcedure,
		svc.BulkRemoveUsersFromTenant,
		connect.WithSchema(userTenantServiceMethods.ByName("BulkRemoveUsersFromTenant")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceGetUserTenantHistoryHandler := connect.NewUnaryHandler(
		UserTenantServiceGetUserTenantHistoryProcedure,
		svc.GetUserTenantHistory,
		connect.WithSchema(userTenantServiceMethods.ByName("GetUserTenantHistory")),
		connect.WithHandlerOptions(opts...),
	)
	userTenantServiceTransferUserBetweenTenantsHandler := connect.NewUnaryHandler(
		UserTenantServiceTransferUserBetweenTenantsProcedure,
		svc.TransferUserBetweenTenants,
		connect.WithSchema(userTenantServiceMethods.ByName("TransferUserBetweenTenants")),
		connect.WithHandlerOptions(opts...),
	)
	return "/identity.user.api.v2.user_tenant.UserTenantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserTenantServiceAssignUserToTenantProcedure:
			userTenantServiceAssignUserToTenantHandler.ServeHTTP(w, r)
		case UserTenantServiceRemoveUserFromTenantProcedure:
			userTenantServiceRemoveUserFromTenantHandler.ServeHTTP(w, r)
		case UserTenantServiceUpdateUserTenantRoleProcedure:
			userTenantServiceUpdateUserTenantRoleHandler.ServeHTTP(w, r)
		case UserTenantServiceGetUserTenantsProcedure:
			userTenantServiceGetUserTenantsHandler.ServeHTTP(w, r)
		case UserTenantServiceGetTenantUsersProcedure:
			userTenantServiceGetTenantUsersHandler.ServeHTTP(w, r)
		case UserTenantServiceCheckUserTenantAccessProcedure:
			userTenantServiceCheckUserTenantAccessHandler.ServeHTTP(w, r)
		case UserTenantServiceBulkAssignUsersToTenantProcedure:
			userTenantServiceBulkAssignUsersToTenantHandler.ServeHTTP(w, r)
		case UserTenantServiceBulkRemoveUsersFromTenantProcedure:
			userTenantServiceBulkRemoveUsersFromTenantHandler.ServeHTTP(w, r)
		case UserTenantServiceGetUserTenantHistoryProcedure:
			userTenantServiceGetUserTenantHistoryHandler.ServeHTTP(w, r)
		case UserTenantServiceTransferUserBetweenTenantsProcedure:
			userTenantServiceTransferUserBetweenTenantsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserTenantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserTenantServiceHandler struct{}

func (UnimplementedUserTenantServiceHandler) AssignUserToTenant(context.Context, *connect.Request[user_tenant.AssignUserToTenantRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.AssignUserToTenant is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) RemoveUserFromTenant(context.Context, *connect.Request[user_tenant.RemoveUserFromTenantRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.RemoveUserFromTenant is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) UpdateUserTenantRole(context.Context, *connect.Request[user_tenant.UpdateUserTenantRoleRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.UpdateUserTenantRole is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) GetUserTenants(context.Context, *connect.Request[user_tenant.GetUserTenantsRequest]) (*connect.Response[user_tenant.GetUserTenantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.GetUserTenants is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) GetTenantUsers(context.Context, *connect.Request[user_tenant.GetTenantUsersRequest]) (*connect.Response[user_tenant.GetTenantUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.GetTenantUsers is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) CheckUserTenantAccess(context.Context, *connect.Request[user_tenant.CheckUserTenantAccessRequest]) (*connect.Response[user_tenant.CheckUserTenantAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.CheckUserTenantAccess is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) BulkAssignUsersToTenant(context.Context, *connect.Request[user_tenant.BulkAssignUsersToTenantRequest]) (*connect.Response[user_tenant.BulkAssignUsersToTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.BulkAssignUsersToTenant is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) BulkRemoveUsersFromTenant(context.Context, *connect.Request[user_tenant.BulkRemoveUsersFromTenantRequest]) (*connect.Response[user_tenant.BulkRemoveUsersFromTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.BulkRemoveUsersFromTenant is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) GetUserTenantHistory(context.Context, *connect.Request[user_tenant.GetUserTenantHistoryRequest]) (*connect.Response[user_tenant.GetUserTenantHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.GetUserTenantHistory is not implemented"))
}

func (UnimplementedUserTenantServiceHandler) TransferUserBetweenTenants(context.Context, *connect.Request[user_tenant.TransferUserBetweenTenantsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.user.api.v2.user_tenant.UserTenantService.TransferUserBetweenTenants is not implemented"))
}
