// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: formbuilder/proto/approval.proto

package approvalconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	approval "p9e.in/ugcl/formbuilder/api/v2/approval"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApprovalServiceName is the fully-qualified name of the ApprovalService service.
	ApprovalServiceName = "formbuilder.api.v2.approval.ApprovalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApprovalServiceStartApprovalProcessProcedure is the fully-qualified name of the ApprovalService's
	// StartApprovalProcess RPC.
	ApprovalServiceStartApprovalProcessProcedure = "/formbuilder.api.v2.approval.ApprovalService/StartApprovalProcess"
	// ApprovalServiceProcessApprovalActionProcedure is the fully-qualified name of the
	// ApprovalService's ProcessApprovalAction RPC.
	ApprovalServiceProcessApprovalActionProcedure = "/formbuilder.api.v2.approval.ApprovalService/ProcessApprovalAction"
	// ApprovalServiceGetApprovalInstanceProcedure is the fully-qualified name of the ApprovalService's
	// GetApprovalInstance RPC.
	ApprovalServiceGetApprovalInstanceProcedure = "/formbuilder.api.v2.approval.ApprovalService/GetApprovalInstance"
	// ApprovalServiceListApprovalInstancesProcedure is the fully-qualified name of the
	// ApprovalService's ListApprovalInstances RPC.
	ApprovalServiceListApprovalInstancesProcedure = "/formbuilder.api.v2.approval.ApprovalService/ListApprovalInstances"
	// ApprovalServiceCancelApprovalInstanceProcedure is the fully-qualified name of the
	// ApprovalService's CancelApprovalInstance RPC.
	ApprovalServiceCancelApprovalInstanceProcedure = "/formbuilder.api.v2.approval.ApprovalService/CancelApprovalInstance"
	// ApprovalServiceCreateDelegateProcedure is the fully-qualified name of the ApprovalService's
	// CreateDelegate RPC.
	ApprovalServiceCreateDelegateProcedure = "/formbuilder.api.v2.approval.ApprovalService/CreateDelegate"
	// ApprovalServiceUpdateDelegateProcedure is the fully-qualified name of the ApprovalService's
	// UpdateDelegate RPC.
	ApprovalServiceUpdateDelegateProcedure = "/formbuilder.api.v2.approval.ApprovalService/UpdateDelegate"
	// ApprovalServiceDeleteDelegateProcedure is the fully-qualified name of the ApprovalService's
	// DeleteDelegate RPC.
	ApprovalServiceDeleteDelegateProcedure = "/formbuilder.api.v2.approval.ApprovalService/DeleteDelegate"
	// ApprovalServiceListDelegatesProcedure is the fully-qualified name of the ApprovalService's
	// ListDelegates RPC.
	ApprovalServiceListDelegatesProcedure = "/formbuilder.api.v2.approval.ApprovalService/ListDelegates"
	// ApprovalServiceGetApprovalMetricsProcedure is the fully-qualified name of the ApprovalService's
	// GetApprovalMetrics RPC.
	ApprovalServiceGetApprovalMetricsProcedure = "/formbuilder.api.v2.approval.ApprovalService/GetApprovalMetrics"
	// ApprovalServiceGetPendingApprovalsProcedure is the fully-qualified name of the ApprovalService's
	// GetPendingApprovals RPC.
	ApprovalServiceGetPendingApprovalsProcedure = "/formbuilder.api.v2.approval.ApprovalService/GetPendingApprovals"
	// ApprovalServiceGetApprovalHistoryProcedure is the fully-qualified name of the ApprovalService's
	// GetApprovalHistory RPC.
	ApprovalServiceGetApprovalHistoryProcedure = "/formbuilder.api.v2.approval.ApprovalService/GetApprovalHistory"
	// ApprovalServiceProcessEscalationsProcedure is the fully-qualified name of the ApprovalService's
	// ProcessEscalations RPC.
	ApprovalServiceProcessEscalationsProcedure = "/formbuilder.api.v2.approval.ApprovalService/ProcessEscalations"
	// ApprovalServiceGetEscalatedApprovalsProcedure is the fully-qualified name of the
	// ApprovalService's GetEscalatedApprovals RPC.
	ApprovalServiceGetEscalatedApprovalsProcedure = "/formbuilder.api.v2.approval.ApprovalService/GetEscalatedApprovals"
)

// ApprovalServiceClient is a client for the formbuilder.api.v2.approval.ApprovalService service.
type ApprovalServiceClient interface {
	// Approval Process Management
	StartApprovalProcess(context.Context, *connect.Request[approval.StartApprovalProcessRequest]) (*connect.Response[approval.StartApprovalProcessResponse], error)
	ProcessApprovalAction(context.Context, *connect.Request[approval.ProcessApprovalActionRequest]) (*connect.Response[approval.ProcessApprovalActionResponse], error)
	GetApprovalInstance(context.Context, *connect.Request[approval.GetApprovalInstanceRequest]) (*connect.Response[approval.GetApprovalInstanceResponse], error)
	ListApprovalInstances(context.Context, *connect.Request[approval.ListApprovalInstancesRequest]) (*connect.Response[approval.ListApprovalInstancesResponse], error)
	CancelApprovalInstance(context.Context, *connect.Request[approval.CancelApprovalInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Delegation Management
	CreateDelegate(context.Context, *connect.Request[approval.CreateDelegateRequest]) (*connect.Response[approval.CreateDelegateResponse], error)
	UpdateDelegate(context.Context, *connect.Request[approval.UpdateDelegateRequest]) (*connect.Response[approval.UpdateDelegateResponse], error)
	DeleteDelegate(context.Context, *connect.Request[approval.DeleteDelegateRequest]) (*connect.Response[emptypb.Empty], error)
	ListDelegates(context.Context, *connect.Request[approval.ListDelegatesRequest]) (*connect.Response[approval.ListDelegatesResponse], error)
	// Reporting and Analytics
	GetApprovalMetrics(context.Context, *connect.Request[approval.GetApprovalMetricsRequest]) (*connect.Response[approval.GetApprovalMetricsResponse], error)
	GetPendingApprovals(context.Context, *connect.Request[approval.GetPendingApprovalsRequest]) (*connect.Response[approval.GetPendingApprovalsResponse], error)
	GetApprovalHistory(context.Context, *connect.Request[approval.GetApprovalHistoryRequest]) (*connect.Response[approval.GetApprovalHistoryResponse], error)
	// Escalation Management
	ProcessEscalations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[approval.ProcessEscalationsResponse], error)
	GetEscalatedApprovals(context.Context, *connect.Request[approval.GetEscalatedApprovalsRequest]) (*connect.Response[approval.GetEscalatedApprovalsResponse], error)
}

// NewApprovalServiceClient constructs a client for the formbuilder.api.v2.approval.ApprovalService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApprovalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApprovalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	approvalServiceMethods := approval.File_formbuilder_proto_approval_proto.Services().ByName("ApprovalService").Methods()
	return &approvalServiceClient{
		startApprovalProcess: connect.NewClient[approval.StartApprovalProcessRequest, approval.StartApprovalProcessResponse](
			httpClient,
			baseURL+ApprovalServiceStartApprovalProcessProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("StartApprovalProcess")),
			connect.WithClientOptions(opts...),
		),
		processApprovalAction: connect.NewClient[approval.ProcessApprovalActionRequest, approval.ProcessApprovalActionResponse](
			httpClient,
			baseURL+ApprovalServiceProcessApprovalActionProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("ProcessApprovalAction")),
			connect.WithClientOptions(opts...),
		),
		getApprovalInstance: connect.NewClient[approval.GetApprovalInstanceRequest, approval.GetApprovalInstanceResponse](
			httpClient,
			baseURL+ApprovalServiceGetApprovalInstanceProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("GetApprovalInstance")),
			connect.WithClientOptions(opts...),
		),
		listApprovalInstances: connect.NewClient[approval.ListApprovalInstancesRequest, approval.ListApprovalInstancesResponse](
			httpClient,
			baseURL+ApprovalServiceListApprovalInstancesProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("ListApprovalInstances")),
			connect.WithClientOptions(opts...),
		),
		cancelApprovalInstance: connect.NewClient[approval.CancelApprovalInstanceRequest, emptypb.Empty](
			httpClient,
			baseURL+ApprovalServiceCancelApprovalInstanceProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("CancelApprovalInstance")),
			connect.WithClientOptions(opts...),
		),
		createDelegate: connect.NewClient[approval.CreateDelegateRequest, approval.CreateDelegateResponse](
			httpClient,
			baseURL+ApprovalServiceCreateDelegateProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("CreateDelegate")),
			connect.WithClientOptions(opts...),
		),
		updateDelegate: connect.NewClient[approval.UpdateDelegateRequest, approval.UpdateDelegateResponse](
			httpClient,
			baseURL+ApprovalServiceUpdateDelegateProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("UpdateDelegate")),
			connect.WithClientOptions(opts...),
		),
		deleteDelegate: connect.NewClient[approval.DeleteDelegateRequest, emptypb.Empty](
			httpClient,
			baseURL+ApprovalServiceDeleteDelegateProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("DeleteDelegate")),
			connect.WithClientOptions(opts...),
		),
		listDelegates: connect.NewClient[approval.ListDelegatesRequest, approval.ListDelegatesResponse](
			httpClient,
			baseURL+ApprovalServiceListDelegatesProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("ListDelegates")),
			connect.WithClientOptions(opts...),
		),
		getApprovalMetrics: connect.NewClient[approval.GetApprovalMetricsRequest, approval.GetApprovalMetricsResponse](
			httpClient,
			baseURL+ApprovalServiceGetApprovalMetricsProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("GetApprovalMetrics")),
			connect.WithClientOptions(opts...),
		),
		getPendingApprovals: connect.NewClient[approval.GetPendingApprovalsRequest, approval.GetPendingApprovalsResponse](
			httpClient,
			baseURL+ApprovalServiceGetPendingApprovalsProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("GetPendingApprovals")),
			connect.WithClientOptions(opts...),
		),
		getApprovalHistory: connect.NewClient[approval.GetApprovalHistoryRequest, approval.GetApprovalHistoryResponse](
			httpClient,
			baseURL+ApprovalServiceGetApprovalHistoryProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("GetApprovalHistory")),
			connect.WithClientOptions(opts...),
		),
		processEscalations: connect.NewClient[emptypb.Empty, approval.ProcessEscalationsResponse](
			httpClient,
			baseURL+ApprovalServiceProcessEscalationsProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("ProcessEscalations")),
			connect.WithClientOptions(opts...),
		),
		getEscalatedApprovals: connect.NewClient[approval.GetEscalatedApprovalsRequest, approval.GetEscalatedApprovalsResponse](
			httpClient,
			baseURL+ApprovalServiceGetEscalatedApprovalsProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("GetEscalatedApprovals")),
			connect.WithClientOptions(opts...),
		),
	}
}

// approvalServiceClient implements ApprovalServiceClient.
type approvalServiceClient struct {
	startApprovalProcess   *connect.Client[approval.StartApprovalProcessRequest, approval.StartApprovalProcessResponse]
	processApprovalAction  *connect.Client[approval.ProcessApprovalActionRequest, approval.ProcessApprovalActionResponse]
	getApprovalInstance    *connect.Client[approval.GetApprovalInstanceRequest, approval.GetApprovalInstanceResponse]
	listApprovalInstances  *connect.Client[approval.ListApprovalInstancesRequest, approval.ListApprovalInstancesResponse]
	cancelApprovalInstance *connect.Client[approval.CancelApprovalInstanceRequest, emptypb.Empty]
	createDelegate         *connect.Client[approval.CreateDelegateRequest, approval.CreateDelegateResponse]
	updateDelegate         *connect.Client[approval.UpdateDelegateRequest, approval.UpdateDelegateResponse]
	deleteDelegate         *connect.Client[approval.DeleteDelegateRequest, emptypb.Empty]
	listDelegates          *connect.Client[approval.ListDelegatesRequest, approval.ListDelegatesResponse]
	getApprovalMetrics     *connect.Client[approval.GetApprovalMetricsRequest, approval.GetApprovalMetricsResponse]
	getPendingApprovals    *connect.Client[approval.GetPendingApprovalsRequest, approval.GetPendingApprovalsResponse]
	getApprovalHistory     *connect.Client[approval.GetApprovalHistoryRequest, approval.GetApprovalHistoryResponse]
	processEscalations     *connect.Client[emptypb.Empty, approval.ProcessEscalationsResponse]
	getEscalatedApprovals  *connect.Client[approval.GetEscalatedApprovalsRequest, approval.GetEscalatedApprovalsResponse]
}

// StartApprovalProcess calls formbuilder.api.v2.approval.ApprovalService.StartApprovalProcess.
func (c *approvalServiceClient) StartApprovalProcess(ctx context.Context, req *connect.Request[approval.StartApprovalProcessRequest]) (*connect.Response[approval.StartApprovalProcessResponse], error) {
	return c.startApprovalProcess.CallUnary(ctx, req)
}

// ProcessApprovalAction calls formbuilder.api.v2.approval.ApprovalService.ProcessApprovalAction.
func (c *approvalServiceClient) ProcessApprovalAction(ctx context.Context, req *connect.Request[approval.ProcessApprovalActionRequest]) (*connect.Response[approval.ProcessApprovalActionResponse], error) {
	return c.processApprovalAction.CallUnary(ctx, req)
}

// GetApprovalInstance calls formbuilder.api.v2.approval.ApprovalService.GetApprovalInstance.
func (c *approvalServiceClient) GetApprovalInstance(ctx context.Context, req *connect.Request[approval.GetApprovalInstanceRequest]) (*connect.Response[approval.GetApprovalInstanceResponse], error) {
	return c.getApprovalInstance.CallUnary(ctx, req)
}

// ListApprovalInstances calls formbuilder.api.v2.approval.ApprovalService.ListApprovalInstances.
func (c *approvalServiceClient) ListApprovalInstances(ctx context.Context, req *connect.Request[approval.ListApprovalInstancesRequest]) (*connect.Response[approval.ListApprovalInstancesResponse], error) {
	return c.listApprovalInstances.CallUnary(ctx, req)
}

// CancelApprovalInstance calls formbuilder.api.v2.approval.ApprovalService.CancelApprovalInstance.
func (c *approvalServiceClient) CancelApprovalInstance(ctx context.Context, req *connect.Request[approval.CancelApprovalInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.cancelApprovalInstance.CallUnary(ctx, req)
}

// CreateDelegate calls formbuilder.api.v2.approval.ApprovalService.CreateDelegate.
func (c *approvalServiceClient) CreateDelegate(ctx context.Context, req *connect.Request[approval.CreateDelegateRequest]) (*connect.Response[approval.CreateDelegateResponse], error) {
	return c.createDelegate.CallUnary(ctx, req)
}

// UpdateDelegate calls formbuilder.api.v2.approval.ApprovalService.UpdateDelegate.
func (c *approvalServiceClient) UpdateDelegate(ctx context.Context, req *connect.Request[approval.UpdateDelegateRequest]) (*connect.Response[approval.UpdateDelegateResponse], error) {
	return c.updateDelegate.CallUnary(ctx, req)
}

// DeleteDelegate calls formbuilder.api.v2.approval.ApprovalService.DeleteDelegate.
func (c *approvalServiceClient) DeleteDelegate(ctx context.Context, req *connect.Request[approval.DeleteDelegateRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteDelegate.CallUnary(ctx, req)
}

// ListDelegates calls formbuilder.api.v2.approval.ApprovalService.ListDelegates.
func (c *approvalServiceClient) ListDelegates(ctx context.Context, req *connect.Request[approval.ListDelegatesRequest]) (*connect.Response[approval.ListDelegatesResponse], error) {
	return c.listDelegates.CallUnary(ctx, req)
}

// GetApprovalMetrics calls formbuilder.api.v2.approval.ApprovalService.GetApprovalMetrics.
func (c *approvalServiceClient) GetApprovalMetrics(ctx context.Context, req *connect.Request[approval.GetApprovalMetricsRequest]) (*connect.Response[approval.GetApprovalMetricsResponse], error) {
	return c.getApprovalMetrics.CallUnary(ctx, req)
}

// GetPendingApprovals calls formbuilder.api.v2.approval.ApprovalService.GetPendingApprovals.
func (c *approvalServiceClient) GetPendingApprovals(ctx context.Context, req *connect.Request[approval.GetPendingApprovalsRequest]) (*connect.Response[approval.GetPendingApprovalsResponse], error) {
	return c.getPendingApprovals.CallUnary(ctx, req)
}

// GetApprovalHistory calls formbuilder.api.v2.approval.ApprovalService.GetApprovalHistory.
func (c *approvalServiceClient) GetApprovalHistory(ctx context.Context, req *connect.Request[approval.GetApprovalHistoryRequest]) (*connect.Response[approval.GetApprovalHistoryResponse], error) {
	return c.getApprovalHistory.CallUnary(ctx, req)
}

// ProcessEscalations calls formbuilder.api.v2.approval.ApprovalService.ProcessEscalations.
func (c *approvalServiceClient) ProcessEscalations(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[approval.ProcessEscalationsResponse], error) {
	return c.processEscalations.CallUnary(ctx, req)
}

// GetEscalatedApprovals calls formbuilder.api.v2.approval.ApprovalService.GetEscalatedApprovals.
func (c *approvalServiceClient) GetEscalatedApprovals(ctx context.Context, req *connect.Request[approval.GetEscalatedApprovalsRequest]) (*connect.Response[approval.GetEscalatedApprovalsResponse], error) {
	return c.getEscalatedApprovals.CallUnary(ctx, req)
}

// ApprovalServiceHandler is an implementation of the formbuilder.api.v2.approval.ApprovalService
// service.
type ApprovalServiceHandler interface {
	// Approval Process Management
	StartApprovalProcess(context.Context, *connect.Request[approval.StartApprovalProcessRequest]) (*connect.Response[approval.StartApprovalProcessResponse], error)
	ProcessApprovalAction(context.Context, *connect.Request[approval.ProcessApprovalActionRequest]) (*connect.Response[approval.ProcessApprovalActionResponse], error)
	GetApprovalInstance(context.Context, *connect.Request[approval.GetApprovalInstanceRequest]) (*connect.Response[approval.GetApprovalInstanceResponse], error)
	ListApprovalInstances(context.Context, *connect.Request[approval.ListApprovalInstancesRequest]) (*connect.Response[approval.ListApprovalInstancesResponse], error)
	CancelApprovalInstance(context.Context, *connect.Request[approval.CancelApprovalInstanceRequest]) (*connect.Response[emptypb.Empty], error)
	// Delegation Management
	CreateDelegate(context.Context, *connect.Request[approval.CreateDelegateRequest]) (*connect.Response[approval.CreateDelegateResponse], error)
	UpdateDelegate(context.Context, *connect.Request[approval.UpdateDelegateRequest]) (*connect.Response[approval.UpdateDelegateResponse], error)
	DeleteDelegate(context.Context, *connect.Request[approval.DeleteDelegateRequest]) (*connect.Response[emptypb.Empty], error)
	ListDelegates(context.Context, *connect.Request[approval.ListDelegatesRequest]) (*connect.Response[approval.ListDelegatesResponse], error)
	// Reporting and Analytics
	GetApprovalMetrics(context.Context, *connect.Request[approval.GetApprovalMetricsRequest]) (*connect.Response[approval.GetApprovalMetricsResponse], error)
	GetPendingApprovals(context.Context, *connect.Request[approval.GetPendingApprovalsRequest]) (*connect.Response[approval.GetPendingApprovalsResponse], error)
	GetApprovalHistory(context.Context, *connect.Request[approval.GetApprovalHistoryRequest]) (*connect.Response[approval.GetApprovalHistoryResponse], error)
	// Escalation Management
	ProcessEscalations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[approval.ProcessEscalationsResponse], error)
	GetEscalatedApprovals(context.Context, *connect.Request[approval.GetEscalatedApprovalsRequest]) (*connect.Response[approval.GetEscalatedApprovalsResponse], error)
}

// NewApprovalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApprovalServiceHandler(svc ApprovalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	approvalServiceMethods := approval.File_formbuilder_proto_approval_proto.Services().ByName("ApprovalService").Methods()
	approvalServiceStartApprovalProcessHandler := connect.NewUnaryHandler(
		ApprovalServiceStartApprovalProcessProcedure,
		svc.StartApprovalProcess,
		connect.WithSchema(approvalServiceMethods.ByName("StartApprovalProcess")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceProcessApprovalActionHandler := connect.NewUnaryHandler(
		ApprovalServiceProcessApprovalActionProcedure,
		svc.ProcessApprovalAction,
		connect.WithSchema(approvalServiceMethods.ByName("ProcessApprovalAction")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceGetApprovalInstanceHandler := connect.NewUnaryHandler(
		ApprovalServiceGetApprovalInstanceProcedure,
		svc.GetApprovalInstance,
		connect.WithSchema(approvalServiceMethods.ByName("GetApprovalInstance")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceListApprovalInstancesHandler := connect.NewUnaryHandler(
		ApprovalServiceListApprovalInstancesProcedure,
		svc.ListApprovalInstances,
		connect.WithSchema(approvalServiceMethods.ByName("ListApprovalInstances")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceCancelApprovalInstanceHandler := connect.NewUnaryHandler(
		ApprovalServiceCancelApprovalInstanceProcedure,
		svc.CancelApprovalInstance,
		connect.WithSchema(approvalServiceMethods.ByName("CancelApprovalInstance")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceCreateDelegateHandler := connect.NewUnaryHandler(
		ApprovalServiceCreateDelegateProcedure,
		svc.CreateDelegate,
		connect.WithSchema(approvalServiceMethods.ByName("CreateDelegate")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceUpdateDelegateHandler := connect.NewUnaryHandler(
		ApprovalServiceUpdateDelegateProcedure,
		svc.UpdateDelegate,
		connect.WithSchema(approvalServiceMethods.ByName("UpdateDelegate")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceDeleteDelegateHandler := connect.NewUnaryHandler(
		ApprovalServiceDeleteDelegateProcedure,
		svc.DeleteDelegate,
		connect.WithSchema(approvalServiceMethods.ByName("DeleteDelegate")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceListDelegatesHandler := connect.NewUnaryHandler(
		ApprovalServiceListDelegatesProcedure,
		svc.ListDelegates,
		connect.WithSchema(approvalServiceMethods.ByName("ListDelegates")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceGetApprovalMetricsHandler := connect.NewUnaryHandler(
		ApprovalServiceGetApprovalMetricsProcedure,
		svc.GetApprovalMetrics,
		connect.WithSchema(approvalServiceMethods.ByName("GetApprovalMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceGetPendingApprovalsHandler := connect.NewUnaryHandler(
		ApprovalServiceGetPendingApprovalsProcedure,
		svc.GetPendingApprovals,
		connect.WithSchema(approvalServiceMethods.ByName("GetPendingApprovals")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceGetApprovalHistoryHandler := connect.NewUnaryHandler(
		ApprovalServiceGetApprovalHistoryProcedure,
		svc.GetApprovalHistory,
		connect.WithSchema(approvalServiceMethods.ByName("GetApprovalHistory")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceProcessEscalationsHandler := connect.NewUnaryHandler(
		ApprovalServiceProcessEscalationsProcedure,
		svc.ProcessEscalations,
		connect.WithSchema(approvalServiceMethods.ByName("ProcessEscalations")),
		connect.WithHandlerOptions(opts...),
	)
	approvalServiceGetEscalatedApprovalsHandler := connect.NewUnaryHandler(
		ApprovalServiceGetEscalatedApprovalsProcedure,
		svc.GetEscalatedApprovals,
		connect.WithSchema(approvalServiceMethods.ByName("GetEscalatedApprovals")),
		connect.WithHandlerOptions(opts...),
	)
	return "/formbuilder.api.v2.approval.ApprovalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApprovalServiceStartApprovalProcessProcedure:
			approvalServiceStartApprovalProcessHandler.ServeHTTP(w, r)
		case ApprovalServiceProcessApprovalActionProcedure:
			approvalServiceProcessApprovalActionHandler.ServeHTTP(w, r)
		case ApprovalServiceGetApprovalInstanceProcedure:
			approvalServiceGetApprovalInstanceHandler.ServeHTTP(w, r)
		case ApprovalServiceListApprovalInstancesProcedure:
			approvalServiceListApprovalInstancesHandler.ServeHTTP(w, r)
		case ApprovalServiceCancelApprovalInstanceProcedure:
			approvalServiceCancelApprovalInstanceHandler.ServeHTTP(w, r)
		case ApprovalServiceCreateDelegateProcedure:
			approvalServiceCreateDelegateHandler.ServeHTTP(w, r)
		case ApprovalServiceUpdateDelegateProcedure:
			approvalServiceUpdateDelegateHandler.ServeHTTP(w, r)
		case ApprovalServiceDeleteDelegateProcedure:
			approvalServiceDeleteDelegateHandler.ServeHTTP(w, r)
		case ApprovalServiceListDelegatesProcedure:
			approvalServiceListDelegatesHandler.ServeHTTP(w, r)
		case ApprovalServiceGetApprovalMetricsProcedure:
			approvalServiceGetApprovalMetricsHandler.ServeHTTP(w, r)
		case ApprovalServiceGetPendingApprovalsProcedure:
			approvalServiceGetPendingApprovalsHandler.ServeHTTP(w, r)
		case ApprovalServiceGetApprovalHistoryProcedure:
			approvalServiceGetApprovalHistoryHandler.ServeHTTP(w, r)
		case ApprovalServiceProcessEscalationsProcedure:
			approvalServiceProcessEscalationsHandler.ServeHTTP(w, r)
		case ApprovalServiceGetEscalatedApprovalsProcedure:
			approvalServiceGetEscalatedApprovalsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApprovalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApprovalServiceHandler struct{}

func (UnimplementedApprovalServiceHandler) StartApprovalProcess(context.Context, *connect.Request[approval.StartApprovalProcessRequest]) (*connect.Response[approval.StartApprovalProcessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.StartApprovalProcess is not implemented"))
}

func (UnimplementedApprovalServiceHandler) ProcessApprovalAction(context.Context, *connect.Request[approval.ProcessApprovalActionRequest]) (*connect.Response[approval.ProcessApprovalActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.ProcessApprovalAction is not implemented"))
}

func (UnimplementedApprovalServiceHandler) GetApprovalInstance(context.Context, *connect.Request[approval.GetApprovalInstanceRequest]) (*connect.Response[approval.GetApprovalInstanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.GetApprovalInstance is not implemented"))
}

func (UnimplementedApprovalServiceHandler) ListApprovalInstances(context.Context, *connect.Request[approval.ListApprovalInstancesRequest]) (*connect.Response[approval.ListApprovalInstancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.ListApprovalInstances is not implemented"))
}

func (UnimplementedApprovalServiceHandler) CancelApprovalInstance(context.Context, *connect.Request[approval.CancelApprovalInstanceRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.CancelApprovalInstance is not implemented"))
}

func (UnimplementedApprovalServiceHandler) CreateDelegate(context.Context, *connect.Request[approval.CreateDelegateRequest]) (*connect.Response[approval.CreateDelegateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.CreateDelegate is not implemented"))
}

func (UnimplementedApprovalServiceHandler) UpdateDelegate(context.Context, *connect.Request[approval.UpdateDelegateRequest]) (*connect.Response[approval.UpdateDelegateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.UpdateDelegate is not implemented"))
}

func (UnimplementedApprovalServiceHandler) DeleteDelegate(context.Context, *connect.Request[approval.DeleteDelegateRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.DeleteDelegate is not implemented"))
}

func (UnimplementedApprovalServiceHandler) ListDelegates(context.Context, *connect.Request[approval.ListDelegatesRequest]) (*connect.Response[approval.ListDelegatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.ListDelegates is not implemented"))
}

func (UnimplementedApprovalServiceHandler) GetApprovalMetrics(context.Context, *connect.Request[approval.GetApprovalMetricsRequest]) (*connect.Response[approval.GetApprovalMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.GetApprovalMetrics is not implemented"))
}

func (UnimplementedApprovalServiceHandler) GetPendingApprovals(context.Context, *connect.Request[approval.GetPendingApprovalsRequest]) (*connect.Response[approval.GetPendingApprovalsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.GetPendingApprovals is not implemented"))
}

func (UnimplementedApprovalServiceHandler) GetApprovalHistory(context.Context, *connect.Request[approval.GetApprovalHistoryRequest]) (*connect.Response[approval.GetApprovalHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.GetApprovalHistory is not implemented"))
}

func (UnimplementedApprovalServiceHandler) ProcessEscalations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[approval.ProcessEscalationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.ProcessEscalations is not implemented"))
}

func (UnimplementedApprovalServiceHandler) GetEscalatedApprovals(context.Context, *connect.Request[approval.GetEscalatedApprovalsRequest]) (*connect.Response[approval.GetEscalatedApprovalsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.approval.ApprovalService.GetEscalatedApprovals is not implemented"))
}
