// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: formbuilder/proto/forminstance.proto

package form_instanceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	form_instance "p9e.in/ugcl/formbuilder/api/v2/form_instance"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// formSubmissionName is the fully-qualified name of the formSubmission service.
	formSubmissionName = "formbuilder.api.v2.form_instance.formSubmission"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FormSubmissionSubmitFormProcedure is the fully-qualified name of the formSubmission's SubmitForm
	// RPC.
	FormSubmissionSubmitFormProcedure = "/formbuilder.api.v2.form_instance.formSubmission/SubmitForm"
	// FormSubmissionGetFormInstanceProcedure is the fully-qualified name of the formSubmission's
	// GetFormInstance RPC.
	FormSubmissionGetFormInstanceProcedure = "/formbuilder.api.v2.form_instance.formSubmission/GetFormInstance"
	// FormSubmissionUpdateFormInstanceProcedure is the fully-qualified name of the formSubmission's
	// UpdateFormInstance RPC.
	FormSubmissionUpdateFormInstanceProcedure = "/formbuilder.api.v2.form_instance.formSubmission/UpdateFormInstance"
)

// FormSubmissionClient is a client for the formbuilder.api.v2.form_instance.formSubmission service.
type FormSubmissionClient interface {
	SubmitForm(context.Context, *connect.Request[form_instance.SubmitFormRequest]) (*connect.Response[form_instance.SubmitFormResponse], error)
	GetFormInstance(context.Context, *connect.Request[form_instance.GetFormInstanceRequest]) (*connect.Response[form_instance.FormInstance], error)
	UpdateFormInstance(context.Context, *connect.Request[form_instance.UpdateFormInstanceRequest]) (*connect.Response[form_instance.SubmitFormResponse], error)
}

// NewFormSubmissionClient constructs a client for the
// formbuilder.api.v2.form_instance.formSubmission service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFormSubmissionClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FormSubmissionClient {
	baseURL = strings.TrimRight(baseURL, "/")
	formSubmissionMethods := form_instance.File_formbuilder_proto_forminstance_proto.Services().ByName("formSubmission").Methods()
	return &formSubmissionClient{
		submitForm: connect.NewClient[form_instance.SubmitFormRequest, form_instance.SubmitFormResponse](
			httpClient,
			baseURL+FormSubmissionSubmitFormProcedure,
			connect.WithSchema(formSubmissionMethods.ByName("SubmitForm")),
			connect.WithClientOptions(opts...),
		),
		getFormInstance: connect.NewClient[form_instance.GetFormInstanceRequest, form_instance.FormInstance](
			httpClient,
			baseURL+FormSubmissionGetFormInstanceProcedure,
			connect.WithSchema(formSubmissionMethods.ByName("GetFormInstance")),
			connect.WithClientOptions(opts...),
		),
		updateFormInstance: connect.NewClient[form_instance.UpdateFormInstanceRequest, form_instance.SubmitFormResponse](
			httpClient,
			baseURL+FormSubmissionUpdateFormInstanceProcedure,
			connect.WithSchema(formSubmissionMethods.ByName("UpdateFormInstance")),
			connect.WithClientOptions(opts...),
		),
	}
}

// formSubmissionClient implements FormSubmissionClient.
type formSubmissionClient struct {
	submitForm         *connect.Client[form_instance.SubmitFormRequest, form_instance.SubmitFormResponse]
	getFormInstance    *connect.Client[form_instance.GetFormInstanceRequest, form_instance.FormInstance]
	updateFormInstance *connect.Client[form_instance.UpdateFormInstanceRequest, form_instance.SubmitFormResponse]
}

// SubmitForm calls formbuilder.api.v2.form_instance.formSubmission.SubmitForm.
func (c *formSubmissionClient) SubmitForm(ctx context.Context, req *connect.Request[form_instance.SubmitFormRequest]) (*connect.Response[form_instance.SubmitFormResponse], error) {
	return c.submitForm.CallUnary(ctx, req)
}

// GetFormInstance calls formbuilder.api.v2.form_instance.formSubmission.GetFormInstance.
func (c *formSubmissionClient) GetFormInstance(ctx context.Context, req *connect.Request[form_instance.GetFormInstanceRequest]) (*connect.Response[form_instance.FormInstance], error) {
	return c.getFormInstance.CallUnary(ctx, req)
}

// UpdateFormInstance calls formbuilder.api.v2.form_instance.formSubmission.UpdateFormInstance.
func (c *formSubmissionClient) UpdateFormInstance(ctx context.Context, req *connect.Request[form_instance.UpdateFormInstanceRequest]) (*connect.Response[form_instance.SubmitFormResponse], error) {
	return c.updateFormInstance.CallUnary(ctx, req)
}

// FormSubmissionHandler is an implementation of the formbuilder.api.v2.form_instance.formSubmission
// service.
type FormSubmissionHandler interface {
	SubmitForm(context.Context, *connect.Request[form_instance.SubmitFormRequest]) (*connect.Response[form_instance.SubmitFormResponse], error)
	GetFormInstance(context.Context, *connect.Request[form_instance.GetFormInstanceRequest]) (*connect.Response[form_instance.FormInstance], error)
	UpdateFormInstance(context.Context, *connect.Request[form_instance.UpdateFormInstanceRequest]) (*connect.Response[form_instance.SubmitFormResponse], error)
}

// NewFormSubmissionHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFormSubmissionHandler(svc FormSubmissionHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	formSubmissionMethods := form_instance.File_formbuilder_proto_forminstance_proto.Services().ByName("formSubmission").Methods()
	formSubmissionSubmitFormHandler := connect.NewUnaryHandler(
		FormSubmissionSubmitFormProcedure,
		svc.SubmitForm,
		connect.WithSchema(formSubmissionMethods.ByName("SubmitForm")),
		connect.WithHandlerOptions(opts...),
	)
	formSubmissionGetFormInstanceHandler := connect.NewUnaryHandler(
		FormSubmissionGetFormInstanceProcedure,
		svc.GetFormInstance,
		connect.WithSchema(formSubmissionMethods.ByName("GetFormInstance")),
		connect.WithHandlerOptions(opts...),
	)
	formSubmissionUpdateFormInstanceHandler := connect.NewUnaryHandler(
		FormSubmissionUpdateFormInstanceProcedure,
		svc.UpdateFormInstance,
		connect.WithSchema(formSubmissionMethods.ByName("UpdateFormInstance")),
		connect.WithHandlerOptions(opts...),
	)
	return "/formbuilder.api.v2.form_instance.formSubmission/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FormSubmissionSubmitFormProcedure:
			formSubmissionSubmitFormHandler.ServeHTTP(w, r)
		case FormSubmissionGetFormInstanceProcedure:
			formSubmissionGetFormInstanceHandler.ServeHTTP(w, r)
		case FormSubmissionUpdateFormInstanceProcedure:
			formSubmissionUpdateFormInstanceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFormSubmissionHandler returns CodeUnimplemented from all methods.
type UnimplementedFormSubmissionHandler struct{}

func (UnimplementedFormSubmissionHandler) SubmitForm(context.Context, *connect.Request[form_instance.SubmitFormRequest]) (*connect.Response[form_instance.SubmitFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_instance.formSubmission.SubmitForm is not implemented"))
}

func (UnimplementedFormSubmissionHandler) GetFormInstance(context.Context, *connect.Request[form_instance.GetFormInstanceRequest]) (*connect.Response[form_instance.FormInstance], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_instance.formSubmission.GetFormInstance is not implemented"))
}

func (UnimplementedFormSubmissionHandler) UpdateFormInstance(context.Context, *connect.Request[form_instance.UpdateFormInstanceRequest]) (*connect.Response[form_instance.SubmitFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_instance.formSubmission.UpdateFormInstance is not implemented"))
}
