syntax = "proto3";

package user.api.v2.user;
option go_package = "p9e.in/ugcl/identity/api/v2/user;user";

import "google/protobuf/wrappers.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/empty.proto";

service UserService {
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    
  }

  rpc GetUser(UserIdentifier) returns (User) {
    
  }

  rpc CreateUser(CreateUserRequest) returns (UserIdentifier) {
    
  }

  rpc UpdateUser(UpdateUserRequest) returns (UserIdentifier) {
  }

  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {
  }

  rpc AssignRoleToUser(AssignRoleRequest) returns (google.protobuf.Empty) {
  }

  rpc RevokeRoleFromUser(AssignRoleRequest) returns (google.protobuf.Empty) {
  }
}

message User {
  google.protobuf.StringValue uuid = 1;
  int32 id = 2;
  google.protobuf.StringValue username = 3;
  google.protobuf.StringValue fullname = 4;
  google.protobuf.StringValue phone = 5;
  google.protobuf.StringValue email = 6 ;
  string password = 7;
  string confirm_password = 8;
  Gender gender = 9;
  repeated string tenant_id = 10;
  repeated string roles = 11;
  bool two_factor_enabled = 12;
  google.protobuf.StringValue two_factor_secret = 13 ;
  bool email_verified = 14;
  bool phone_verified = 15;
  bytes Avatar =16;
  bool is_active = 17;
}

enum Gender {
  UNKNOWN = 0;
  MALE = 1;
  FEMALE = 2;
  OTHER = 3;
}

message UserIdentifier {
  oneof identifier {
    int32 id = 1;
    string uuid = 2;
  }
}

message CreateUserRequest {
  User user = 1;
}

message UpdateUserRequest {
  User user = 1;
  google.protobuf.FieldMask update_mask = 2;
}

message DeleteUserRequest {
  int32 id = 1;
  bool force = 2;
}

message DeleteUserResponse {}

message AssignRoleRequest {
  string user_id = 1;
  string role_id = 2;
}

message ListUsersRequest {
  int32 page_offset = 1;
  int32 page_size = 2;
  repeated string sort = 3;
  google.protobuf.FieldMask fields = 4;
  UserFilter filter = 5;
}

message ListUsersResponse {
  int32 total_size = 1;
  int32 filter_size = 2;
  repeated User users = 3;
}

message UserFilter {
  google.protobuf.StringValue username = 1;
  google.protobuf.StringValue phone = 2;
  google.protobuf.StringValue email= 3;
  google.protobuf.StringValue fullname = 4;
  string search_term = 5;
  repeated string tenant_ids = 6;
  repeated string role_ids = 7;
  bool active_only = 8;
  repeated UserFilter and = 9;
  repeated UserFilter or = 10;
}
