// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/auth/proto/auth.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	auth "p9e.in/ugcl/identity/auth/api/v2/auth"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "identity.auth.api.v2.auth.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/identity.auth.api.v2.auth.AuthService/Login"
	// AuthServiceLoginWithOTPProcedure is the fully-qualified name of the AuthService's LoginWithOTP
	// RPC.
	AuthServiceLoginWithOTPProcedure = "/identity.auth.api.v2.auth.AuthService/LoginWithOTP"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/identity.auth.api.v2.auth.AuthService/Logout"
	// AuthServiceLogoutAllProcedure is the fully-qualified name of the AuthService's LogoutAll RPC.
	AuthServiceLogoutAllProcedure = "/identity.auth.api.v2.auth.AuthService/LogoutAll"
	// AuthServiceEnableTwoFactorProcedure is the fully-qualified name of the AuthService's
	// EnableTwoFactor RPC.
	AuthServiceEnableTwoFactorProcedure = "/identity.auth.api.v2.auth.AuthService/EnableTwoFactor"
	// AuthServiceDisableTwoFactorProcedure is the fully-qualified name of the AuthService's
	// DisableTwoFactor RPC.
	AuthServiceDisableTwoFactorProcedure = "/identity.auth.api.v2.auth.AuthService/DisableTwoFactor"
	// AuthServiceVerifyTwoFactorProcedure is the fully-qualified name of the AuthService's
	// VerifyTwoFactor RPC.
	AuthServiceVerifyTwoFactorProcedure = "/identity.auth.api.v2.auth.AuthService/VerifyTwoFactor"
	// AuthServiceGenerateBackupCodesProcedure is the fully-qualified name of the AuthService's
	// GenerateBackupCodes RPC.
	AuthServiceGenerateBackupCodesProcedure = "/identity.auth.api.v2.auth.AuthService/GenerateBackupCodes"
	// AuthServiceLockAccountProcedure is the fully-qualified name of the AuthService's LockAccount RPC.
	AuthServiceLockAccountProcedure = "/identity.auth.api.v2.auth.AuthService/LockAccount"
	// AuthServiceUnlockAccountProcedure is the fully-qualified name of the AuthService's UnlockAccount
	// RPC.
	AuthServiceUnlockAccountProcedure = "/identity.auth.api.v2.auth.AuthService/UnlockAccount"
	// AuthServiceGetAccountStatusProcedure is the fully-qualified name of the AuthService's
	// GetAccountStatus RPC.
	AuthServiceGetAccountStatusProcedure = "/identity.auth.api.v2.auth.AuthService/GetAccountStatus"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/identity.auth.api.v2.auth.AuthService/RefreshToken"
	// AuthServiceValidateTokenProcedure is the fully-qualified name of the AuthService's ValidateToken
	// RPC.
	AuthServiceValidateTokenProcedure = "/identity.auth.api.v2.auth.AuthService/ValidateToken"
	// AuthServiceRevokeTokenProcedure is the fully-qualified name of the AuthService's RevokeToken RPC.
	AuthServiceRevokeTokenProcedure = "/identity.auth.api.v2.auth.AuthService/RevokeToken"
	// AuthServiceRevokeAllTokensProcedure is the fully-qualified name of the AuthService's
	// RevokeAllTokens RPC.
	AuthServiceRevokeAllTokensProcedure = "/identity.auth.api.v2.auth.AuthService/RevokeAllTokens"
	// AuthServiceGetActiveSessionsProcedure is the fully-qualified name of the AuthService's
	// GetActiveSessions RPC.
	AuthServiceGetActiveSessionsProcedure = "/identity.auth.api.v2.auth.AuthService/GetActiveSessions"
	// AuthServiceRevokeSessionProcedure is the fully-qualified name of the AuthService's RevokeSession
	// RPC.
	AuthServiceRevokeSessionProcedure = "/identity.auth.api.v2.auth.AuthService/RevokeSession"
	// AuthServiceRevokeAllSessionsProcedure is the fully-qualified name of the AuthService's
	// RevokeAllSessions RPC.
	AuthServiceRevokeAllSessionsProcedure = "/identity.auth.api.v2.auth.AuthService/RevokeAllSessions"
	// AuthServiceGetSecurityEventsProcedure is the fully-qualified name of the AuthService's
	// GetSecurityEvents RPC.
	AuthServiceGetSecurityEventsProcedure = "/identity.auth.api.v2.auth.AuthService/GetSecurityEvents"
	// AuthServiceRecordSecurityEventProcedure is the fully-qualified name of the AuthService's
	// RecordSecurityEvent RPC.
	AuthServiceRecordSecurityEventProcedure = "/identity.auth.api.v2.auth.AuthService/RecordSecurityEvent"
)

// AuthServiceClient is a client for the identity.auth.api.v2.auth.AuthService service.
type AuthServiceClient interface {
	// Authentication
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error)
	LoginWithOTP(context.Context, *connect.Request[auth.LoginOTPRequest]) (*connect.Response[auth.LoginResponse], error)
	Logout(context.Context, *connect.Request[auth.LogoutRequest]) (*connect.Response[emptypb.Empty], error)
	LogoutAll(context.Context, *connect.Request[auth.LogoutAllRequest]) (*connect.Response[emptypb.Empty], error)
	// Two-Factor Authentication
	EnableTwoFactor(context.Context, *connect.Request[auth.EnableTwoFactorRequest]) (*connect.Response[auth.EnableTwoFactorResponse], error)
	DisableTwoFactor(context.Context, *connect.Request[auth.DisableTwoFactorRequest]) (*connect.Response[emptypb.Empty], error)
	VerifyTwoFactor(context.Context, *connect.Request[auth.VerifyTwoFactorRequest]) (*connect.Response[auth.VerifyTwoFactorResponse], error)
	GenerateBackupCodes(context.Context, *connect.Request[auth.GenerateBackupCodesRequest]) (*connect.Response[auth.GenerateBackupCodesResponse], error)
	// Account Security
	LockAccount(context.Context, *connect.Request[auth.LockAccountRequest]) (*connect.Response[emptypb.Empty], error)
	UnlockAccount(context.Context, *connect.Request[auth.UnlockAccountRequest]) (*connect.Response[emptypb.Empty], error)
	GetAccountStatus(context.Context, *connect.Request[auth.GetAccountStatusRequest]) (*connect.Response[auth.GetAccountStatusResponse], error)
	// Token Management
	RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error)
	ValidateToken(context.Context, *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error)
	RevokeToken(context.Context, *connect.Request[auth.RevokeTokenRequest]) (*connect.Response[emptypb.Empty], error)
	RevokeAllTokens(context.Context, *connect.Request[auth.RevokeAllTokensRequest]) (*connect.Response[emptypb.Empty], error)
	// Session Management
	GetActiveSessions(context.Context, *connect.Request[auth.GetActiveSessionsRequest]) (*connect.Response[auth.GetActiveSessionsResponse], error)
	RevokeSession(context.Context, *connect.Request[auth.RevokeSessionRequest]) (*connect.Response[emptypb.Empty], error)
	RevokeAllSessions(context.Context, *connect.Request[auth.RevokeAllSessionsRequest]) (*connect.Response[emptypb.Empty], error)
	// Security Events
	GetSecurityEvents(context.Context, *connect.Request[auth.GetSecurityEventsRequest]) (*connect.Response[auth.GetSecurityEventsResponse], error)
	RecordSecurityEvent(context.Context, *connect.Request[auth.RecordSecurityEventRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewAuthServiceClient constructs a client for the identity.auth.api.v2.auth.AuthService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := auth.File_identity_auth_proto_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		login: connect.NewClient[auth.LoginRequest, auth.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		loginWithOTP: connect.NewClient[auth.LoginOTPRequest, auth.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginWithOTPProcedure,
			connect.WithSchema(authServiceMethods.ByName("LoginWithOTP")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[auth.LogoutRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		logoutAll: connect.NewClient[auth.LogoutAllRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceLogoutAllProcedure,
			connect.WithSchema(authServiceMethods.ByName("LogoutAll")),
			connect.WithClientOptions(opts...),
		),
		enableTwoFactor: connect.NewClient[auth.EnableTwoFactorRequest, auth.EnableTwoFactorResponse](
			httpClient,
			baseURL+AuthServiceEnableTwoFactorProcedure,
			connect.WithSchema(authServiceMethods.ByName("EnableTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		disableTwoFactor: connect.NewClient[auth.DisableTwoFactorRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceDisableTwoFactorProcedure,
			connect.WithSchema(authServiceMethods.ByName("DisableTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		verifyTwoFactor: connect.NewClient[auth.VerifyTwoFactorRequest, auth.VerifyTwoFactorResponse](
			httpClient,
			baseURL+AuthServiceVerifyTwoFactorProcedure,
			connect.WithSchema(authServiceMethods.ByName("VerifyTwoFactor")),
			connect.WithClientOptions(opts...),
		),
		generateBackupCodes: connect.NewClient[auth.GenerateBackupCodesRequest, auth.GenerateBackupCodesResponse](
			httpClient,
			baseURL+AuthServiceGenerateBackupCodesProcedure,
			connect.WithSchema(authServiceMethods.ByName("GenerateBackupCodes")),
			connect.WithClientOptions(opts...),
		),
		lockAccount: connect.NewClient[auth.LockAccountRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceLockAccountProcedure,
			connect.WithSchema(authServiceMethods.ByName("LockAccount")),
			connect.WithClientOptions(opts...),
		),
		unlockAccount: connect.NewClient[auth.UnlockAccountRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceUnlockAccountProcedure,
			connect.WithSchema(authServiceMethods.ByName("UnlockAccount")),
			connect.WithClientOptions(opts...),
		),
		getAccountStatus: connect.NewClient[auth.GetAccountStatusRequest, auth.GetAccountStatusResponse](
			httpClient,
			baseURL+AuthServiceGetAccountStatusProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAccountStatus")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[auth.RefreshTokenRequest, auth.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		validateToken: connect.NewClient[auth.ValidateTokenRequest, auth.ValidateTokenResponse](
			httpClient,
			baseURL+AuthServiceValidateTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
			connect.WithClientOptions(opts...),
		),
		revokeToken: connect.NewClient[auth.RevokeTokenRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceRevokeTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeToken")),
			connect.WithClientOptions(opts...),
		),
		revokeAllTokens: connect.NewClient[auth.RevokeAllTokensRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceRevokeAllTokensProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeAllTokens")),
			connect.WithClientOptions(opts...),
		),
		getActiveSessions: connect.NewClient[auth.GetActiveSessionsRequest, auth.GetActiveSessionsResponse](
			httpClient,
			baseURL+AuthServiceGetActiveSessionsProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetActiveSessions")),
			connect.WithClientOptions(opts...),
		),
		revokeSession: connect.NewClient[auth.RevokeSessionRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceRevokeSessionProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeSession")),
			connect.WithClientOptions(opts...),
		),
		revokeAllSessions: connect.NewClient[auth.RevokeAllSessionsRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceRevokeAllSessionsProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeAllSessions")),
			connect.WithClientOptions(opts...),
		),
		getSecurityEvents: connect.NewClient[auth.GetSecurityEventsRequest, auth.GetSecurityEventsResponse](
			httpClient,
			baseURL+AuthServiceGetSecurityEventsProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetSecurityEvents")),
			connect.WithClientOptions(opts...),
		),
		recordSecurityEvent: connect.NewClient[auth.RecordSecurityEventRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceRecordSecurityEventProcedure,
			connect.WithSchema(authServiceMethods.ByName("RecordSecurityEvent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	login               *connect.Client[auth.LoginRequest, auth.LoginResponse]
	loginWithOTP        *connect.Client[auth.LoginOTPRequest, auth.LoginResponse]
	logout              *connect.Client[auth.LogoutRequest, emptypb.Empty]
	logoutAll           *connect.Client[auth.LogoutAllRequest, emptypb.Empty]
	enableTwoFactor     *connect.Client[auth.EnableTwoFactorRequest, auth.EnableTwoFactorResponse]
	disableTwoFactor    *connect.Client[auth.DisableTwoFactorRequest, emptypb.Empty]
	verifyTwoFactor     *connect.Client[auth.VerifyTwoFactorRequest, auth.VerifyTwoFactorResponse]
	generateBackupCodes *connect.Client[auth.GenerateBackupCodesRequest, auth.GenerateBackupCodesResponse]
	lockAccount         *connect.Client[auth.LockAccountRequest, emptypb.Empty]
	unlockAccount       *connect.Client[auth.UnlockAccountRequest, emptypb.Empty]
	getAccountStatus    *connect.Client[auth.GetAccountStatusRequest, auth.GetAccountStatusResponse]
	refreshToken        *connect.Client[auth.RefreshTokenRequest, auth.RefreshTokenResponse]
	validateToken       *connect.Client[auth.ValidateTokenRequest, auth.ValidateTokenResponse]
	revokeToken         *connect.Client[auth.RevokeTokenRequest, emptypb.Empty]
	revokeAllTokens     *connect.Client[auth.RevokeAllTokensRequest, emptypb.Empty]
	getActiveSessions   *connect.Client[auth.GetActiveSessionsRequest, auth.GetActiveSessionsResponse]
	revokeSession       *connect.Client[auth.RevokeSessionRequest, emptypb.Empty]
	revokeAllSessions   *connect.Client[auth.RevokeAllSessionsRequest, emptypb.Empty]
	getSecurityEvents   *connect.Client[auth.GetSecurityEventsRequest, auth.GetSecurityEventsResponse]
	recordSecurityEvent *connect.Client[auth.RecordSecurityEventRequest, emptypb.Empty]
}

// Login calls identity.auth.api.v2.auth.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// LoginWithOTP calls identity.auth.api.v2.auth.AuthService.LoginWithOTP.
func (c *authServiceClient) LoginWithOTP(ctx context.Context, req *connect.Request[auth.LoginOTPRequest]) (*connect.Response[auth.LoginResponse], error) {
	return c.loginWithOTP.CallUnary(ctx, req)
}

// Logout calls identity.auth.api.v2.auth.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[auth.LogoutRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.logout.CallUnary(ctx, req)
}

// LogoutAll calls identity.auth.api.v2.auth.AuthService.LogoutAll.
func (c *authServiceClient) LogoutAll(ctx context.Context, req *connect.Request[auth.LogoutAllRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.logoutAll.CallUnary(ctx, req)
}

// EnableTwoFactor calls identity.auth.api.v2.auth.AuthService.EnableTwoFactor.
func (c *authServiceClient) EnableTwoFactor(ctx context.Context, req *connect.Request[auth.EnableTwoFactorRequest]) (*connect.Response[auth.EnableTwoFactorResponse], error) {
	return c.enableTwoFactor.CallUnary(ctx, req)
}

// DisableTwoFactor calls identity.auth.api.v2.auth.AuthService.DisableTwoFactor.
func (c *authServiceClient) DisableTwoFactor(ctx context.Context, req *connect.Request[auth.DisableTwoFactorRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.disableTwoFactor.CallUnary(ctx, req)
}

// VerifyTwoFactor calls identity.auth.api.v2.auth.AuthService.VerifyTwoFactor.
func (c *authServiceClient) VerifyTwoFactor(ctx context.Context, req *connect.Request[auth.VerifyTwoFactorRequest]) (*connect.Response[auth.VerifyTwoFactorResponse], error) {
	return c.verifyTwoFactor.CallUnary(ctx, req)
}

// GenerateBackupCodes calls identity.auth.api.v2.auth.AuthService.GenerateBackupCodes.
func (c *authServiceClient) GenerateBackupCodes(ctx context.Context, req *connect.Request[auth.GenerateBackupCodesRequest]) (*connect.Response[auth.GenerateBackupCodesResponse], error) {
	return c.generateBackupCodes.CallUnary(ctx, req)
}

// LockAccount calls identity.auth.api.v2.auth.AuthService.LockAccount.
func (c *authServiceClient) LockAccount(ctx context.Context, req *connect.Request[auth.LockAccountRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.lockAccount.CallUnary(ctx, req)
}

// UnlockAccount calls identity.auth.api.v2.auth.AuthService.UnlockAccount.
func (c *authServiceClient) UnlockAccount(ctx context.Context, req *connect.Request[auth.UnlockAccountRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.unlockAccount.CallUnary(ctx, req)
}

// GetAccountStatus calls identity.auth.api.v2.auth.AuthService.GetAccountStatus.
func (c *authServiceClient) GetAccountStatus(ctx context.Context, req *connect.Request[auth.GetAccountStatusRequest]) (*connect.Response[auth.GetAccountStatusResponse], error) {
	return c.getAccountStatus.CallUnary(ctx, req)
}

// RefreshToken calls identity.auth.api.v2.auth.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// ValidateToken calls identity.auth.api.v2.auth.AuthService.ValidateToken.
func (c *authServiceClient) ValidateToken(ctx context.Context, req *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error) {
	return c.validateToken.CallUnary(ctx, req)
}

// RevokeToken calls identity.auth.api.v2.auth.AuthService.RevokeToken.
func (c *authServiceClient) RevokeToken(ctx context.Context, req *connect.Request[auth.RevokeTokenRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// RevokeAllTokens calls identity.auth.api.v2.auth.AuthService.RevokeAllTokens.
func (c *authServiceClient) RevokeAllTokens(ctx context.Context, req *connect.Request[auth.RevokeAllTokensRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revokeAllTokens.CallUnary(ctx, req)
}

// GetActiveSessions calls identity.auth.api.v2.auth.AuthService.GetActiveSessions.
func (c *authServiceClient) GetActiveSessions(ctx context.Context, req *connect.Request[auth.GetActiveSessionsRequest]) (*connect.Response[auth.GetActiveSessionsResponse], error) {
	return c.getActiveSessions.CallUnary(ctx, req)
}

// RevokeSession calls identity.auth.api.v2.auth.AuthService.RevokeSession.
func (c *authServiceClient) RevokeSession(ctx context.Context, req *connect.Request[auth.RevokeSessionRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revokeSession.CallUnary(ctx, req)
}

// RevokeAllSessions calls identity.auth.api.v2.auth.AuthService.RevokeAllSessions.
func (c *authServiceClient) RevokeAllSessions(ctx context.Context, req *connect.Request[auth.RevokeAllSessionsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revokeAllSessions.CallUnary(ctx, req)
}

// GetSecurityEvents calls identity.auth.api.v2.auth.AuthService.GetSecurityEvents.
func (c *authServiceClient) GetSecurityEvents(ctx context.Context, req *connect.Request[auth.GetSecurityEventsRequest]) (*connect.Response[auth.GetSecurityEventsResponse], error) {
	return c.getSecurityEvents.CallUnary(ctx, req)
}

// RecordSecurityEvent calls identity.auth.api.v2.auth.AuthService.RecordSecurityEvent.
func (c *authServiceClient) RecordSecurityEvent(ctx context.Context, req *connect.Request[auth.RecordSecurityEventRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.recordSecurityEvent.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the identity.auth.api.v2.auth.AuthService service.
type AuthServiceHandler interface {
	// Authentication
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error)
	LoginWithOTP(context.Context, *connect.Request[auth.LoginOTPRequest]) (*connect.Response[auth.LoginResponse], error)
	Logout(context.Context, *connect.Request[auth.LogoutRequest]) (*connect.Response[emptypb.Empty], error)
	LogoutAll(context.Context, *connect.Request[auth.LogoutAllRequest]) (*connect.Response[emptypb.Empty], error)
	// Two-Factor Authentication
	EnableTwoFactor(context.Context, *connect.Request[auth.EnableTwoFactorRequest]) (*connect.Response[auth.EnableTwoFactorResponse], error)
	DisableTwoFactor(context.Context, *connect.Request[auth.DisableTwoFactorRequest]) (*connect.Response[emptypb.Empty], error)
	VerifyTwoFactor(context.Context, *connect.Request[auth.VerifyTwoFactorRequest]) (*connect.Response[auth.VerifyTwoFactorResponse], error)
	GenerateBackupCodes(context.Context, *connect.Request[auth.GenerateBackupCodesRequest]) (*connect.Response[auth.GenerateBackupCodesResponse], error)
	// Account Security
	LockAccount(context.Context, *connect.Request[auth.LockAccountRequest]) (*connect.Response[emptypb.Empty], error)
	UnlockAccount(context.Context, *connect.Request[auth.UnlockAccountRequest]) (*connect.Response[emptypb.Empty], error)
	GetAccountStatus(context.Context, *connect.Request[auth.GetAccountStatusRequest]) (*connect.Response[auth.GetAccountStatusResponse], error)
	// Token Management
	RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error)
	ValidateToken(context.Context, *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error)
	RevokeToken(context.Context, *connect.Request[auth.RevokeTokenRequest]) (*connect.Response[emptypb.Empty], error)
	RevokeAllTokens(context.Context, *connect.Request[auth.RevokeAllTokensRequest]) (*connect.Response[emptypb.Empty], error)
	// Session Management
	GetActiveSessions(context.Context, *connect.Request[auth.GetActiveSessionsRequest]) (*connect.Response[auth.GetActiveSessionsResponse], error)
	RevokeSession(context.Context, *connect.Request[auth.RevokeSessionRequest]) (*connect.Response[emptypb.Empty], error)
	RevokeAllSessions(context.Context, *connect.Request[auth.RevokeAllSessionsRequest]) (*connect.Response[emptypb.Empty], error)
	// Security Events
	GetSecurityEvents(context.Context, *connect.Request[auth.GetSecurityEventsRequest]) (*connect.Response[auth.GetSecurityEventsResponse], error)
	RecordSecurityEvent(context.Context, *connect.Request[auth.RecordSecurityEventRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := auth.File_identity_auth_proto_auth_proto.Services().ByName("AuthService").Methods()
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginWithOTPHandler := connect.NewUnaryHandler(
		AuthServiceLoginWithOTPProcedure,
		svc.LoginWithOTP,
		connect.WithSchema(authServiceMethods.ByName("LoginWithOTP")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutAllHandler := connect.NewUnaryHandler(
		AuthServiceLogoutAllProcedure,
		svc.LogoutAll,
		connect.WithSchema(authServiceMethods.ByName("LogoutAll")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceEnableTwoFactorHandler := connect.NewUnaryHandler(
		AuthServiceEnableTwoFactorProcedure,
		svc.EnableTwoFactor,
		connect.WithSchema(authServiceMethods.ByName("EnableTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDisableTwoFactorHandler := connect.NewUnaryHandler(
		AuthServiceDisableTwoFactorProcedure,
		svc.DisableTwoFactor,
		connect.WithSchema(authServiceMethods.ByName("DisableTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifyTwoFactorHandler := connect.NewUnaryHandler(
		AuthServiceVerifyTwoFactorProcedure,
		svc.VerifyTwoFactor,
		connect.WithSchema(authServiceMethods.ByName("VerifyTwoFactor")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGenerateBackupCodesHandler := connect.NewUnaryHandler(
		AuthServiceGenerateBackupCodesProcedure,
		svc.GenerateBackupCodes,
		connect.WithSchema(authServiceMethods.ByName("GenerateBackupCodes")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLockAccountHandler := connect.NewUnaryHandler(
		AuthServiceLockAccountProcedure,
		svc.LockAccount,
		connect.WithSchema(authServiceMethods.ByName("LockAccount")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUnlockAccountHandler := connect.NewUnaryHandler(
		AuthServiceUnlockAccountProcedure,
		svc.UnlockAccount,
		connect.WithSchema(authServiceMethods.ByName("UnlockAccount")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAccountStatusHandler := connect.NewUnaryHandler(
		AuthServiceGetAccountStatusProcedure,
		svc.GetAccountStatus,
		connect.WithSchema(authServiceMethods.ByName("GetAccountStatus")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceValidateTokenHandler := connect.NewUnaryHandler(
		AuthServiceValidateTokenProcedure,
		svc.ValidateToken,
		connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeTokenHandler := connect.NewUnaryHandler(
		AuthServiceRevokeTokenProcedure,
		svc.RevokeToken,
		connect.WithSchema(authServiceMethods.ByName("RevokeToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeAllTokensHandler := connect.NewUnaryHandler(
		AuthServiceRevokeAllTokensProcedure,
		svc.RevokeAllTokens,
		connect.WithSchema(authServiceMethods.ByName("RevokeAllTokens")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetActiveSessionsHandler := connect.NewUnaryHandler(
		AuthServiceGetActiveSessionsProcedure,
		svc.GetActiveSessions,
		connect.WithSchema(authServiceMethods.ByName("GetActiveSessions")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeSessionHandler := connect.NewUnaryHandler(
		AuthServiceRevokeSessionProcedure,
		svc.RevokeSession,
		connect.WithSchema(authServiceMethods.ByName("RevokeSession")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeAllSessionsHandler := connect.NewUnaryHandler(
		AuthServiceRevokeAllSessionsProcedure,
		svc.RevokeAllSessions,
		connect.WithSchema(authServiceMethods.ByName("RevokeAllSessions")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetSecurityEventsHandler := connect.NewUnaryHandler(
		AuthServiceGetSecurityEventsProcedure,
		svc.GetSecurityEvents,
		connect.WithSchema(authServiceMethods.ByName("GetSecurityEvents")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRecordSecurityEventHandler := connect.NewUnaryHandler(
		AuthServiceRecordSecurityEventProcedure,
		svc.RecordSecurityEvent,
		connect.WithSchema(authServiceMethods.ByName("RecordSecurityEvent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/identity.auth.api.v2.auth.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceLoginWithOTPProcedure:
			authServiceLoginWithOTPHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		case AuthServiceLogoutAllProcedure:
			authServiceLogoutAllHandler.ServeHTTP(w, r)
		case AuthServiceEnableTwoFactorProcedure:
			authServiceEnableTwoFactorHandler.ServeHTTP(w, r)
		case AuthServiceDisableTwoFactorProcedure:
			authServiceDisableTwoFactorHandler.ServeHTTP(w, r)
		case AuthServiceVerifyTwoFactorProcedure:
			authServiceVerifyTwoFactorHandler.ServeHTTP(w, r)
		case AuthServiceGenerateBackupCodesProcedure:
			authServiceGenerateBackupCodesHandler.ServeHTTP(w, r)
		case AuthServiceLockAccountProcedure:
			authServiceLockAccountHandler.ServeHTTP(w, r)
		case AuthServiceUnlockAccountProcedure:
			authServiceUnlockAccountHandler.ServeHTTP(w, r)
		case AuthServiceGetAccountStatusProcedure:
			authServiceGetAccountStatusHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		case AuthServiceValidateTokenProcedure:
			authServiceValidateTokenHandler.ServeHTTP(w, r)
		case AuthServiceRevokeTokenProcedure:
			authServiceRevokeTokenHandler.ServeHTTP(w, r)
		case AuthServiceRevokeAllTokensProcedure:
			authServiceRevokeAllTokensHandler.ServeHTTP(w, r)
		case AuthServiceGetActiveSessionsProcedure:
			authServiceGetActiveSessionsHandler.ServeHTTP(w, r)
		case AuthServiceRevokeSessionProcedure:
			authServiceRevokeSessionHandler.ServeHTTP(w, r)
		case AuthServiceRevokeAllSessionsProcedure:
			authServiceRevokeAllSessionsHandler.ServeHTTP(w, r)
		case AuthServiceGetSecurityEventsProcedure:
			authServiceGetSecurityEventsHandler.ServeHTTP(w, r)
		case AuthServiceRecordSecurityEventProcedure:
			authServiceRecordSecurityEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) LoginWithOTP(context.Context, *connect.Request[auth.LoginOTPRequest]) (*connect.Response[auth.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.LoginWithOTP is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[auth.LogoutRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.Logout is not implemented"))
}

func (UnimplementedAuthServiceHandler) LogoutAll(context.Context, *connect.Request[auth.LogoutAllRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.LogoutAll is not implemented"))
}

func (UnimplementedAuthServiceHandler) EnableTwoFactor(context.Context, *connect.Request[auth.EnableTwoFactorRequest]) (*connect.Response[auth.EnableTwoFactorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.EnableTwoFactor is not implemented"))
}

func (UnimplementedAuthServiceHandler) DisableTwoFactor(context.Context, *connect.Request[auth.DisableTwoFactorRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.DisableTwoFactor is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifyTwoFactor(context.Context, *connect.Request[auth.VerifyTwoFactorRequest]) (*connect.Response[auth.VerifyTwoFactorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.VerifyTwoFactor is not implemented"))
}

func (UnimplementedAuthServiceHandler) GenerateBackupCodes(context.Context, *connect.Request[auth.GenerateBackupCodesRequest]) (*connect.Response[auth.GenerateBackupCodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.GenerateBackupCodes is not implemented"))
}

func (UnimplementedAuthServiceHandler) LockAccount(context.Context, *connect.Request[auth.LockAccountRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.LockAccount is not implemented"))
}

func (UnimplementedAuthServiceHandler) UnlockAccount(context.Context, *connect.Request[auth.UnlockAccountRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.UnlockAccount is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAccountStatus(context.Context, *connect.Request[auth.GetAccountStatusRequest]) (*connect.Response[auth.GetAccountStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.GetAccountStatus is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.RefreshToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) ValidateToken(context.Context, *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.ValidateToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeToken(context.Context, *connect.Request[auth.RevokeTokenRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.RevokeToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeAllTokens(context.Context, *connect.Request[auth.RevokeAllTokensRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.RevokeAllTokens is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetActiveSessions(context.Context, *connect.Request[auth.GetActiveSessionsRequest]) (*connect.Response[auth.GetActiveSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.GetActiveSessions is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeSession(context.Context, *connect.Request[auth.RevokeSessionRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.RevokeSession is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeAllSessions(context.Context, *connect.Request[auth.RevokeAllSessionsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.RevokeAllSessions is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetSecurityEvents(context.Context, *connect.Request[auth.GetSecurityEventsRequest]) (*connect.Response[auth.GetSecurityEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.GetSecurityEvents is not implemented"))
}

func (UnimplementedAuthServiceHandler) RecordSecurityEvent(context.Context, *connect.Request[auth.RecordSecurityEventRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("identity.auth.api.v2.auth.AuthService.RecordSecurityEvent is not implemented"))
}
