syntax = "proto3";

package vendors.contractors.api.v2.contractor;
option go_package = "p9e.in/ugcl/vendors/api/v2/contractor;contractor";

import "google/protobuf/struct.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";
import "identity/proto/user.proto";

service ContractorService {
  rpc CreateContractor(CreateContractorRequest) returns (Contractor) {}

  rpc UpdateContractor(UpdateContractorRequest) returns (Contractor) {}

  rpc GetContractor(ContractorIdentifier) returns (Contractor) {}

  rpc ListContractors(ListContractorsRequest) returns (ListContractorsResponse) {}

  rpc DeleteContractor(ContractorIdentifier) returns (google.protobuf.Empty) {}

  rpc GetContractorByUserId(UserIdentifier) returns (Contractor) {}
  
}

message Contractor {
  string id = 1;
  string company_name = 2;
  string company_type =3;
  string gst =4;
  string pan = 5;
  string category = 6;
  string person_id =7; //user id of the person who is the contact person
  repeated string associated_project = 8;
  repeated string working_site = 9;
  google.protobuf.Timestamp contract_start_date = 10;
  google.protobuf.Timestamp contract_end_date = 11;
  string status = 12;
  google.protobuf.Struct metadata = 13;
  google.protobuf.Timestamp created_at = 14;
  google.protobuf.Timestamp updated_at = 15;
}

message CreateContractorRequest {
  Contractor contractor =1;
  user.api.v2.user.User user =2;
}

message UpdateContractorRequest {
  Contractor contractor = 1;
  google.protobuf.FieldMask update_mask = 2;
}

message ContractorIdentifier {
  string id = 1;
}

message UserIdentifier {
  string user_id = 1;
}

message ListContractorsRequest {
  int32 page_size = 1;
  int32 page_offset = 2;
  ContractorFilter filter = 3;
  repeated string sort = 4;
}

message ListContractorsResponse {
  repeated Contractor contractors = 1;
  int32 total_count = 2;
}

message ContractorFilter {
  string company_name = 1;
  string department = 2;
  string status = 3;
  string manager_id = 4;
  double min_hourly_rate = 5;
  double max_hourly_rate = 6;
  repeated string skills = 7;
}