// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: formbuilder/proto/formbuilder.proto

package form_builderconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	form_builder "p9e.in/ugcl/formbuilder/api/v2/form_builder"
	workflow "p9e.in/ugcl/formbuilder/api/v2/workflow"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FormBuilderName is the fully-qualified name of the FormBuilder service.
	FormBuilderName = "formbuilder.api.v2.form_builder.FormBuilder"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FormBuilderCreateFormProcedure is the fully-qualified name of the FormBuilder's CreateForm RPC.
	FormBuilderCreateFormProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/CreateForm"
	// FormBuilderGetFormProcedure is the fully-qualified name of the FormBuilder's GetForm RPC.
	FormBuilderGetFormProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/GetForm"
	// FormBuilderUpdateFormProcedure is the fully-qualified name of the FormBuilder's UpdateForm RPC.
	FormBuilderUpdateFormProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/UpdateForm"
	// FormBuilderDeleteFormProcedure is the fully-qualified name of the FormBuilder's DeleteForm RPC.
	FormBuilderDeleteFormProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/DeleteForm"
	// FormBuilderListFormsProcedure is the fully-qualified name of the FormBuilder's ListForms RPC.
	FormBuilderListFormsProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/ListForms"
	// FormBuilderMigrateFormVersionProcedure is the fully-qualified name of the FormBuilder's
	// MigrateFormVersion RPC.
	FormBuilderMigrateFormVersionProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/MigrateFormVersion"
	// FormBuilderGetFieldOptionsProcedure is the fully-qualified name of the FormBuilder's
	// GetFieldOptions RPC.
	FormBuilderGetFieldOptionsProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/GetFieldOptions"
	// FormBuilderRefreshFieldCacheProcedure is the fully-qualified name of the FormBuilder's
	// RefreshFieldCache RPC.
	FormBuilderRefreshFieldCacheProcedure = "/formbuilder.api.v2.form_builder.FormBuilder/RefreshFieldCache"
)

// FormBuilderClient is a client for the formbuilder.api.v2.form_builder.FormBuilder service.
type FormBuilderClient interface {
	CreateForm(context.Context, *connect.Request[form_builder.CreateFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error)
	GetForm(context.Context, *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.GetFormResponse], error)
	UpdateForm(context.Context, *connect.Request[form_builder.FormDefinition]) (*connect.Response[form_builder.CreateFormResponse], error)
	DeleteForm(context.Context, *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error)
	ListForms(context.Context, *connect.Request[form_builder.ListFormsRequest]) (*connect.Response[form_builder.ListFormsResponse], error)
	MigrateFormVersion(context.Context, *connect.Request[form_builder.MigrateFormRequest]) (*connect.Response[form_builder.MigrateFormResponse], error)
	GetFieldOptions(context.Context, *connect.Request[form_builder.GetFieldOptionsRequest]) (*connect.Response[form_builder.GetFieldOptionsResponse], error)
	RefreshFieldCache(context.Context, *connect.Request[form_builder.RefreshCacheRequest]) (*connect.Response[form_builder.RefreshCacheResponse], error)
}

// NewFormBuilderClient constructs a client for the formbuilder.api.v2.form_builder.FormBuilder
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFormBuilderClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FormBuilderClient {
	baseURL = strings.TrimRight(baseURL, "/")
	formBuilderMethods := form_builder.File_formbuilder_proto_formbuilder_proto.Services().ByName("FormBuilder").Methods()
	return &formBuilderClient{
		createForm: connect.NewClient[form_builder.CreateFormRequest, form_builder.CreateFormResponse](
			httpClient,
			baseURL+FormBuilderCreateFormProcedure,
			connect.WithSchema(formBuilderMethods.ByName("CreateForm")),
			connect.WithClientOptions(opts...),
		),
		getForm: connect.NewClient[workflow.GetFormRequest, form_builder.GetFormResponse](
			httpClient,
			baseURL+FormBuilderGetFormProcedure,
			connect.WithSchema(formBuilderMethods.ByName("GetForm")),
			connect.WithClientOptions(opts...),
		),
		updateForm: connect.NewClient[form_builder.FormDefinition, form_builder.CreateFormResponse](
			httpClient,
			baseURL+FormBuilderUpdateFormProcedure,
			connect.WithSchema(formBuilderMethods.ByName("UpdateForm")),
			connect.WithClientOptions(opts...),
		),
		deleteForm: connect.NewClient[workflow.GetFormRequest, form_builder.CreateFormResponse](
			httpClient,
			baseURL+FormBuilderDeleteFormProcedure,
			connect.WithSchema(formBuilderMethods.ByName("DeleteForm")),
			connect.WithClientOptions(opts...),
		),
		listForms: connect.NewClient[form_builder.ListFormsRequest, form_builder.ListFormsResponse](
			httpClient,
			baseURL+FormBuilderListFormsProcedure,
			connect.WithSchema(formBuilderMethods.ByName("ListForms")),
			connect.WithClientOptions(opts...),
		),
		migrateFormVersion: connect.NewClient[form_builder.MigrateFormRequest, form_builder.MigrateFormResponse](
			httpClient,
			baseURL+FormBuilderMigrateFormVersionProcedure,
			connect.WithSchema(formBuilderMethods.ByName("MigrateFormVersion")),
			connect.WithClientOptions(opts...),
		),
		getFieldOptions: connect.NewClient[form_builder.GetFieldOptionsRequest, form_builder.GetFieldOptionsResponse](
			httpClient,
			baseURL+FormBuilderGetFieldOptionsProcedure,
			connect.WithSchema(formBuilderMethods.ByName("GetFieldOptions")),
			connect.WithClientOptions(opts...),
		),
		refreshFieldCache: connect.NewClient[form_builder.RefreshCacheRequest, form_builder.RefreshCacheResponse](
			httpClient,
			baseURL+FormBuilderRefreshFieldCacheProcedure,
			connect.WithSchema(formBuilderMethods.ByName("RefreshFieldCache")),
			connect.WithClientOptions(opts...),
		),
	}
}

// formBuilderClient implements FormBuilderClient.
type formBuilderClient struct {
	createForm         *connect.Client[form_builder.CreateFormRequest, form_builder.CreateFormResponse]
	getForm            *connect.Client[workflow.GetFormRequest, form_builder.GetFormResponse]
	updateForm         *connect.Client[form_builder.FormDefinition, form_builder.CreateFormResponse]
	deleteForm         *connect.Client[workflow.GetFormRequest, form_builder.CreateFormResponse]
	listForms          *connect.Client[form_builder.ListFormsRequest, form_builder.ListFormsResponse]
	migrateFormVersion *connect.Client[form_builder.MigrateFormRequest, form_builder.MigrateFormResponse]
	getFieldOptions    *connect.Client[form_builder.GetFieldOptionsRequest, form_builder.GetFieldOptionsResponse]
	refreshFieldCache  *connect.Client[form_builder.RefreshCacheRequest, form_builder.RefreshCacheResponse]
}

// CreateForm calls formbuilder.api.v2.form_builder.FormBuilder.CreateForm.
func (c *formBuilderClient) CreateForm(ctx context.Context, req *connect.Request[form_builder.CreateFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error) {
	return c.createForm.CallUnary(ctx, req)
}

// GetForm calls formbuilder.api.v2.form_builder.FormBuilder.GetForm.
func (c *formBuilderClient) GetForm(ctx context.Context, req *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.GetFormResponse], error) {
	return c.getForm.CallUnary(ctx, req)
}

// UpdateForm calls formbuilder.api.v2.form_builder.FormBuilder.UpdateForm.
func (c *formBuilderClient) UpdateForm(ctx context.Context, req *connect.Request[form_builder.FormDefinition]) (*connect.Response[form_builder.CreateFormResponse], error) {
	return c.updateForm.CallUnary(ctx, req)
}

// DeleteForm calls formbuilder.api.v2.form_builder.FormBuilder.DeleteForm.
func (c *formBuilderClient) DeleteForm(ctx context.Context, req *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error) {
	return c.deleteForm.CallUnary(ctx, req)
}

// ListForms calls formbuilder.api.v2.form_builder.FormBuilder.ListForms.
func (c *formBuilderClient) ListForms(ctx context.Context, req *connect.Request[form_builder.ListFormsRequest]) (*connect.Response[form_builder.ListFormsResponse], error) {
	return c.listForms.CallUnary(ctx, req)
}

// MigrateFormVersion calls formbuilder.api.v2.form_builder.FormBuilder.MigrateFormVersion.
func (c *formBuilderClient) MigrateFormVersion(ctx context.Context, req *connect.Request[form_builder.MigrateFormRequest]) (*connect.Response[form_builder.MigrateFormResponse], error) {
	return c.migrateFormVersion.CallUnary(ctx, req)
}

// GetFieldOptions calls formbuilder.api.v2.form_builder.FormBuilder.GetFieldOptions.
func (c *formBuilderClient) GetFieldOptions(ctx context.Context, req *connect.Request[form_builder.GetFieldOptionsRequest]) (*connect.Response[form_builder.GetFieldOptionsResponse], error) {
	return c.getFieldOptions.CallUnary(ctx, req)
}

// RefreshFieldCache calls formbuilder.api.v2.form_builder.FormBuilder.RefreshFieldCache.
func (c *formBuilderClient) RefreshFieldCache(ctx context.Context, req *connect.Request[form_builder.RefreshCacheRequest]) (*connect.Response[form_builder.RefreshCacheResponse], error) {
	return c.refreshFieldCache.CallUnary(ctx, req)
}

// FormBuilderHandler is an implementation of the formbuilder.api.v2.form_builder.FormBuilder
// service.
type FormBuilderHandler interface {
	CreateForm(context.Context, *connect.Request[form_builder.CreateFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error)
	GetForm(context.Context, *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.GetFormResponse], error)
	UpdateForm(context.Context, *connect.Request[form_builder.FormDefinition]) (*connect.Response[form_builder.CreateFormResponse], error)
	DeleteForm(context.Context, *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error)
	ListForms(context.Context, *connect.Request[form_builder.ListFormsRequest]) (*connect.Response[form_builder.ListFormsResponse], error)
	MigrateFormVersion(context.Context, *connect.Request[form_builder.MigrateFormRequest]) (*connect.Response[form_builder.MigrateFormResponse], error)
	GetFieldOptions(context.Context, *connect.Request[form_builder.GetFieldOptionsRequest]) (*connect.Response[form_builder.GetFieldOptionsResponse], error)
	RefreshFieldCache(context.Context, *connect.Request[form_builder.RefreshCacheRequest]) (*connect.Response[form_builder.RefreshCacheResponse], error)
}

// NewFormBuilderHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFormBuilderHandler(svc FormBuilderHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	formBuilderMethods := form_builder.File_formbuilder_proto_formbuilder_proto.Services().ByName("FormBuilder").Methods()
	formBuilderCreateFormHandler := connect.NewUnaryHandler(
		FormBuilderCreateFormProcedure,
		svc.CreateForm,
		connect.WithSchema(formBuilderMethods.ByName("CreateForm")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderGetFormHandler := connect.NewUnaryHandler(
		FormBuilderGetFormProcedure,
		svc.GetForm,
		connect.WithSchema(formBuilderMethods.ByName("GetForm")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderUpdateFormHandler := connect.NewUnaryHandler(
		FormBuilderUpdateFormProcedure,
		svc.UpdateForm,
		connect.WithSchema(formBuilderMethods.ByName("UpdateForm")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderDeleteFormHandler := connect.NewUnaryHandler(
		FormBuilderDeleteFormProcedure,
		svc.DeleteForm,
		connect.WithSchema(formBuilderMethods.ByName("DeleteForm")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderListFormsHandler := connect.NewUnaryHandler(
		FormBuilderListFormsProcedure,
		svc.ListForms,
		connect.WithSchema(formBuilderMethods.ByName("ListForms")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderMigrateFormVersionHandler := connect.NewUnaryHandler(
		FormBuilderMigrateFormVersionProcedure,
		svc.MigrateFormVersion,
		connect.WithSchema(formBuilderMethods.ByName("MigrateFormVersion")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderGetFieldOptionsHandler := connect.NewUnaryHandler(
		FormBuilderGetFieldOptionsProcedure,
		svc.GetFieldOptions,
		connect.WithSchema(formBuilderMethods.ByName("GetFieldOptions")),
		connect.WithHandlerOptions(opts...),
	)
	formBuilderRefreshFieldCacheHandler := connect.NewUnaryHandler(
		FormBuilderRefreshFieldCacheProcedure,
		svc.RefreshFieldCache,
		connect.WithSchema(formBuilderMethods.ByName("RefreshFieldCache")),
		connect.WithHandlerOptions(opts...),
	)
	return "/formbuilder.api.v2.form_builder.FormBuilder/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FormBuilderCreateFormProcedure:
			formBuilderCreateFormHandler.ServeHTTP(w, r)
		case FormBuilderGetFormProcedure:
			formBuilderGetFormHandler.ServeHTTP(w, r)
		case FormBuilderUpdateFormProcedure:
			formBuilderUpdateFormHandler.ServeHTTP(w, r)
		case FormBuilderDeleteFormProcedure:
			formBuilderDeleteFormHandler.ServeHTTP(w, r)
		case FormBuilderListFormsProcedure:
			formBuilderListFormsHandler.ServeHTTP(w, r)
		case FormBuilderMigrateFormVersionProcedure:
			formBuilderMigrateFormVersionHandler.ServeHTTP(w, r)
		case FormBuilderGetFieldOptionsProcedure:
			formBuilderGetFieldOptionsHandler.ServeHTTP(w, r)
		case FormBuilderRefreshFieldCacheProcedure:
			formBuilderRefreshFieldCacheHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFormBuilderHandler returns CodeUnimplemented from all methods.
type UnimplementedFormBuilderHandler struct{}

func (UnimplementedFormBuilderHandler) CreateForm(context.Context, *connect.Request[form_builder.CreateFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.CreateForm is not implemented"))
}

func (UnimplementedFormBuilderHandler) GetForm(context.Context, *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.GetFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.GetForm is not implemented"))
}

func (UnimplementedFormBuilderHandler) UpdateForm(context.Context, *connect.Request[form_builder.FormDefinition]) (*connect.Response[form_builder.CreateFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.UpdateForm is not implemented"))
}

func (UnimplementedFormBuilderHandler) DeleteForm(context.Context, *connect.Request[workflow.GetFormRequest]) (*connect.Response[form_builder.CreateFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.DeleteForm is not implemented"))
}

func (UnimplementedFormBuilderHandler) ListForms(context.Context, *connect.Request[form_builder.ListFormsRequest]) (*connect.Response[form_builder.ListFormsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.ListForms is not implemented"))
}

func (UnimplementedFormBuilderHandler) MigrateFormVersion(context.Context, *connect.Request[form_builder.MigrateFormRequest]) (*connect.Response[form_builder.MigrateFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.MigrateFormVersion is not implemented"))
}

func (UnimplementedFormBuilderHandler) GetFieldOptions(context.Context, *connect.Request[form_builder.GetFieldOptionsRequest]) (*connect.Response[form_builder.GetFieldOptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.GetFieldOptions is not implemented"))
}

func (UnimplementedFormBuilderHandler) RefreshFieldCache(context.Context, *connect.Request[form_builder.RefreshCacheRequest]) (*connect.Response[form_builder.RefreshCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("formbuilder.api.v2.form_builder.FormBuilder.RefreshFieldCache is not implemented"))
}
