// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupCacheBySize(ctx context.Context, limit int32) error
	CleanupOldReportRuns(ctx context.Context, runAt pgtype.Timestamptz) error
	// =============================================================================
	// Report Cache Queries - InsightViewer Service
	// =============================================================================
	CreateCacheEntry(ctx context.Context, arg CreateCacheEntryParams) (ReportCache, error)
	// =============================================================================
	// Report Alerts Queries - InsightViewer Service
	// =============================================================================
	CreateReportAlert(ctx context.Context, arg CreateReportAlertParams) (ReportAlert, error)
	// =============================================================================
	// Report Exports Queries - InsightViewer Service
	// =============================================================================
	CreateReportExport(ctx context.Context, arg CreateReportExportParams) (ReportExport, error)
	// =============================================================================
	// Report Results Queries - InsightViewer Service
	// =============================================================================
	CreateReportResult(ctx context.Context, arg CreateReportResultParams) (ReportResult, error)
	// =============================================================================
	// Report Runs Queries - InsightViewer Service
	// =============================================================================
	CreateReportRun(ctx context.Context, arg CreateReportRunParams) (ReportRun, error)
	// =============================================================================
	// Report Schedules Queries - InsightViewer Service
	// =============================================================================
	CreateReportSchedule(ctx context.Context, arg CreateReportScheduleParams) (ReportSchedule, error)
	// =============================================================================
	// Report Subscriptions Queries - InsightViewer Service
	// =============================================================================
	CreateReportSubscription(ctx context.Context, arg CreateReportSubscriptionParams) (ReportSubscription, error)
	DeleteCacheByReportID(ctx context.Context, reportID pgtype.UUID) error
	DeleteCacheEntry(ctx context.Context, cacheKey string) error
	DeleteExpiredCache(ctx context.Context) error
	DeleteExpiredExports(ctx context.Context) error
	DeleteExpiredResults(ctx context.Context) error
	DeleteReportAlert(ctx context.Context, id pgtype.UUID) error
	DeleteReportResultsByRunID(ctx context.Context, runID pgtype.UUID) error
	DeleteReportSchedule(ctx context.Context, id pgtype.UUID) error
	DeleteReportSubscription(ctx context.Context, id pgtype.UUID) error
	GetActiveAlerts(ctx context.Context) ([]ReportAlert, error)
	GetActiveSchedules(ctx context.Context) ([]ReportSchedule, error)
	GetActiveSubscriptions(ctx context.Context, arg GetActiveSubscriptionsParams) ([]ReportSubscription, error)
	GetAlertStatistics(ctx context.Context, lastTriggeredAt pgtype.Timestamptz) (GetAlertStatisticsRow, error)
	GetAlertsBySeverity(ctx context.Context, severity pgtype.Text) ([]ReportAlert, error)
	GetAlertsByUser(ctx context.Context, arg GetAlertsByUserParams) ([]ReportAlert, error)
	GetCacheEntriesByType(ctx context.Context, arg GetCacheEntriesByTypeParams) ([]ReportCache, error)
	GetCacheEntryByKey(ctx context.Context, cacheKey string) (ReportCache, error)
	GetCacheStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetCacheStatisticsRow, error)
	GetExportStatistics(ctx context.Context, generatedAt pgtype.Timestamptz) (GetExportStatisticsRow, error)
	GetExportsByStatus(ctx context.Context, status pgtype.Text) ([]ReportExport, error)
	GetLargestCacheEntries(ctx context.Context, limit int32) ([]GetLargestCacheEntriesRow, error)
	GetLargestResults(ctx context.Context, limit int32) ([]GetLargestResultsRow, error)
	GetLeastRecentlyUsedCache(ctx context.Context, limit int32) ([]GetLeastRecentlyUsedCacheRow, error)
	GetMostAccessedResults(ctx context.Context, arg GetMostAccessedResultsParams) ([]GetMostAccessedResultsRow, error)
	GetRecentlyTriggeredAlerts(ctx context.Context, lastTriggeredAt pgtype.Timestamptz) ([]ReportAlert, error)
	GetReportAlertByID(ctx context.Context, id pgtype.UUID) (ReportAlert, error)
	GetReportAlertsByReportID(ctx context.Context, reportID pgtype.UUID) ([]ReportAlert, error)
	GetReportExportByID(ctx context.Context, id pgtype.UUID) (ReportExport, error)
	GetReportExportsByRunID(ctx context.Context, runID pgtype.UUID) ([]ReportExport, error)
	GetReportExportsByUser(ctx context.Context, arg GetReportExportsByUserParams) ([]ReportExport, error)
	GetReportResultByID(ctx context.Context, id pgtype.UUID) (ReportResult, error)
	GetReportResultByRunID(ctx context.Context, runID pgtype.UUID) (ReportResult, error)
	GetReportResultsByCacheRef(ctx context.Context, cacheRef pgtype.Text) (ReportResult, error)
	GetReportRunByID(ctx context.Context, id pgtype.UUID) (ReportRun, error)
	GetReportRunStatistics(ctx context.Context, arg GetReportRunStatisticsParams) (GetReportRunStatisticsRow, error)
	GetReportRunsByReportID(ctx context.Context, arg GetReportRunsByReportIDParams) ([]ReportRun, error)
	GetReportRunsByUser(ctx context.Context, arg GetReportRunsByUserParams) ([]ReportRun, error)
	GetReportRunsWithStatus(ctx context.Context, arg GetReportRunsWithStatusParams) ([]ReportRun, error)
	GetReportScheduleByID(ctx context.Context, id pgtype.UUID) (ReportSchedule, error)
	GetReportSchedulesByReportID(ctx context.Context, reportID pgtype.UUID) ([]ReportSchedule, error)
	GetReportSubscriptionByID(ctx context.Context, id pgtype.UUID) (ReportSubscription, error)
	GetResultStorageStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetResultStorageStatisticsRow, error)
	GetRunningReports(ctx context.Context) ([]ReportRun, error)
	GetSchedulesByUser(ctx context.Context, arg GetSchedulesByUserParams) ([]ReportSchedule, error)
	GetSchedulesDueForExecution(ctx context.Context) ([]ReportSchedule, error)
	GetSubscriptionByReportAndUser(ctx context.Context, arg GetSubscriptionByReportAndUserParams) (ReportSubscription, error)
	GetSubscriptionStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetSubscriptionStatisticsRow, error)
	GetSubscriptionsByReportID(ctx context.Context, reportID pgtype.UUID) ([]ReportSubscription, error)
	GetSubscriptionsByUserID(ctx context.Context, userID pgtype.UUID) ([]ReportSubscription, error)
	GetSubscriptionsForNotification(ctx context.Context, reportID pgtype.UUID) ([]ReportSubscription, error)
	IncrementCacheMiss(ctx context.Context, cacheKey string) error
	IncrementDownloadCount(ctx context.Context, id pgtype.UUID) error
	TriggerAlert(ctx context.Context, id pgtype.UUID) error
	UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (ReportAlert, error)
	UpdateCacheAccess(ctx context.Context, cacheKey string) error
	UpdateExportStatus(ctx context.Context, arg UpdateExportStatusParams) (ReportExport, error)
	UpdateLastNotification(ctx context.Context, id pgtype.UUID) error
	UpdateReportAlert(ctx context.Context, arg UpdateReportAlertParams) (ReportAlert, error)
	UpdateReportRunStatus(ctx context.Context, arg UpdateReportRunStatusParams) (ReportRun, error)
	UpdateReportSchedule(ctx context.Context, arg UpdateReportScheduleParams) (ReportSchedule, error)
	UpdateReportSubscription(ctx context.Context, arg UpdateReportSubscriptionParams) (ReportSubscription, error)
	UpdateResultAccess(ctx context.Context, id pgtype.UUID) error
	UpdateScheduleExecution(ctx context.Context, arg UpdateScheduleExecutionParams) error
	UpdateScheduleStatus(ctx context.Context, arg UpdateScheduleStatusParams) (ReportSchedule, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (ReportSubscription, error)
}

var _ Querier = (*Queries)(nil)
