// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupCacheBySize = `-- name: CleanupCacheBySize :exec
DELETE FROM report_cache
WHERE id IN (
    SELECT id
    FROM report_cache
    ORDER BY last_accessed_at ASC
    LIMIT $1
)
`

func (q *Queries) CleanupCacheBySize(ctx context.Context, limit int32) error {
	_, err := q.db.Exec(ctx, cleanupCacheBySize, limit)
	return err
}

const createCacheEntry = `-- name: CreateCacheEntry :one

INSERT INTO report_cache (
    cache_key,
    cache_type,
    report_id,
    data,
    data_text,
    size_bytes,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING
    id,
    cache_key,
    cache_type,
    report_id,
    data,
    data_text,
    size_bytes,
    created_at,
    expires_at,
    last_accessed_at,
    access_count,
    hit_count,
    miss_count
`

type CreateCacheEntryParams struct {
	CacheKey  string             `db:"cache_key" json:"cache_key"`
	CacheType string             `db:"cache_type" json:"cache_type"`
	ReportID  pgtype.UUID        `db:"report_id" json:"report_id"`
	Data      []byte             `db:"data" json:"data"`
	DataText  pgtype.Text        `db:"data_text" json:"data_text"`
	SizeBytes pgtype.Int4        `db:"size_bytes" json:"size_bytes"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// =============================================================================
// Report Cache Queries - InsightViewer Service
// =============================================================================
func (q *Queries) CreateCacheEntry(ctx context.Context, arg CreateCacheEntryParams) (ReportCache, error) {
	row := q.db.QueryRow(ctx, createCacheEntry,
		arg.CacheKey,
		arg.CacheType,
		arg.ReportID,
		arg.Data,
		arg.DataText,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	var i ReportCache
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.CacheType,
		&i.ReportID,
		&i.Data,
		&i.DataText,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.HitCount,
		&i.MissCount,
	)
	return i, err
}

const deleteCacheByReportID = `-- name: DeleteCacheByReportID :exec
DELETE FROM report_cache
WHERE report_id = $1
`

func (q *Queries) DeleteCacheByReportID(ctx context.Context, reportID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCacheByReportID, reportID)
	return err
}

const deleteCacheEntry = `-- name: DeleteCacheEntry :exec
DELETE FROM report_cache
WHERE cache_key = $1
`

func (q *Queries) DeleteCacheEntry(ctx context.Context, cacheKey string) error {
	_, err := q.db.Exec(ctx, deleteCacheEntry, cacheKey)
	return err
}

const deleteExpiredCache = `-- name: DeleteExpiredCache :exec
DELETE FROM report_cache
WHERE expires_at IS NOT NULL AND expires_at <= NOW()
`

func (q *Queries) DeleteExpiredCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCache)
	return err
}

const getCacheEntriesByType = `-- name: GetCacheEntriesByType :many
SELECT
    id,
    cache_key,
    cache_type,
    report_id,
    data,
    data_text,
    size_bytes,
    created_at,
    expires_at,
    last_accessed_at,
    access_count,
    hit_count,
    miss_count
FROM report_cache
WHERE cache_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCacheEntriesByTypeParams struct {
	CacheType string `db:"cache_type" json:"cache_type"`
	Limit     int32  `db:"limit" json:"limit"`
	Offset    int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetCacheEntriesByType(ctx context.Context, arg GetCacheEntriesByTypeParams) ([]ReportCache, error) {
	rows, err := q.db.Query(ctx, getCacheEntriesByType, arg.CacheType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCache{}
	for rows.Next() {
		var i ReportCache
		if err := rows.Scan(
			&i.ID,
			&i.CacheKey,
			&i.CacheType,
			&i.ReportID,
			&i.Data,
			&i.DataText,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.HitCount,
			&i.MissCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCacheEntryByKey = `-- name: GetCacheEntryByKey :one
SELECT
    id,
    cache_key,
    cache_type,
    report_id,
    data,
    data_text,
    size_bytes,
    created_at,
    expires_at,
    last_accessed_at,
    access_count,
    hit_count,
    miss_count
FROM report_cache
WHERE cache_key = $1 AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetCacheEntryByKey(ctx context.Context, cacheKey string) (ReportCache, error) {
	row := q.db.QueryRow(ctx, getCacheEntryByKey, cacheKey)
	var i ReportCache
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.CacheType,
		&i.ReportID,
		&i.Data,
		&i.DataText,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.HitCount,
		&i.MissCount,
	)
	return i, err
}

const getCacheStatistics = `-- name: GetCacheStatistics :one
SELECT
    COUNT(*) as total_entries,
    SUM(size_bytes) as total_size_bytes,
    AVG(size_bytes) as avg_size_bytes,
    SUM(hit_count) as total_hits,
    SUM(miss_count) as total_misses,
    CASE
        WHEN SUM(hit_count + miss_count) > 0
        THEN (SUM(hit_count)::float / SUM(hit_count + miss_count)::float) * 100
        ELSE 0
    END as hit_rate_percent,
    COUNT(CASE WHEN cache_type = 'result' THEN 1 END) as result_entries,
    COUNT(CASE WHEN cache_type = 'metadata' THEN 1 END) as metadata_entries,
    COUNT(CASE WHEN cache_type = 'query_plan' THEN 1 END) as query_plan_entries,
    COUNT(CASE WHEN cache_type = 'field_values' THEN 1 END) as field_values_entries
FROM report_cache
WHERE created_at >= $1
`

type GetCacheStatisticsRow struct {
	TotalEntries       int64   `db:"total_entries" json:"total_entries"`
	TotalSizeBytes     int64   `db:"total_size_bytes" json:"total_size_bytes"`
	AvgSizeBytes       float64 `db:"avg_size_bytes" json:"avg_size_bytes"`
	TotalHits          int64   `db:"total_hits" json:"total_hits"`
	TotalMisses        int64   `db:"total_misses" json:"total_misses"`
	HitRatePercent     int32   `db:"hit_rate_percent" json:"hit_rate_percent"`
	ResultEntries      int64   `db:"result_entries" json:"result_entries"`
	MetadataEntries    int64   `db:"metadata_entries" json:"metadata_entries"`
	QueryPlanEntries   int64   `db:"query_plan_entries" json:"query_plan_entries"`
	FieldValuesEntries int64   `db:"field_values_entries" json:"field_values_entries"`
}

func (q *Queries) GetCacheStatistics(ctx context.Context, createdAt pgtype.Timestamptz) (GetCacheStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getCacheStatistics, createdAt)
	var i GetCacheStatisticsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.TotalSizeBytes,
		&i.AvgSizeBytes,
		&i.TotalHits,
		&i.TotalMisses,
		&i.HitRatePercent,
		&i.ResultEntries,
		&i.MetadataEntries,
		&i.QueryPlanEntries,
		&i.FieldValuesEntries,
	)
	return i, err
}

const getLargestCacheEntries = `-- name: GetLargestCacheEntries :many
SELECT
    id,
    cache_key,
    cache_type,
    report_id,
    size_bytes,
    created_at,
    last_accessed_at,
    access_count
FROM report_cache
ORDER BY size_bytes DESC
LIMIT $1
`

type GetLargestCacheEntriesRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	CacheKey       string             `db:"cache_key" json:"cache_key"`
	CacheType      string             `db:"cache_type" json:"cache_type"`
	ReportID       pgtype.UUID        `db:"report_id" json:"report_id"`
	SizeBytes      pgtype.Int4        `db:"size_bytes" json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `db:"last_accessed_at" json:"last_accessed_at"`
	AccessCount    pgtype.Int4        `db:"access_count" json:"access_count"`
}

func (q *Queries) GetLargestCacheEntries(ctx context.Context, limit int32) ([]GetLargestCacheEntriesRow, error) {
	rows, err := q.db.Query(ctx, getLargestCacheEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLargestCacheEntriesRow{}
	for rows.Next() {
		var i GetLargestCacheEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CacheKey,
			&i.CacheType,
			&i.ReportID,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeastRecentlyUsedCache = `-- name: GetLeastRecentlyUsedCache :many
SELECT
    id,
    cache_key,
    cache_type,
    report_id,
    size_bytes,
    created_at,
    last_accessed_at,
    access_count
FROM report_cache
ORDER BY last_accessed_at ASC
LIMIT $1
`

type GetLeastRecentlyUsedCacheRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	CacheKey       string             `db:"cache_key" json:"cache_key"`
	CacheType      string             `db:"cache_type" json:"cache_type"`
	ReportID       pgtype.UUID        `db:"report_id" json:"report_id"`
	SizeBytes      pgtype.Int4        `db:"size_bytes" json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `db:"last_accessed_at" json:"last_accessed_at"`
	AccessCount    pgtype.Int4        `db:"access_count" json:"access_count"`
}

func (q *Queries) GetLeastRecentlyUsedCache(ctx context.Context, limit int32) ([]GetLeastRecentlyUsedCacheRow, error) {
	rows, err := q.db.Query(ctx, getLeastRecentlyUsedCache, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeastRecentlyUsedCacheRow{}
	for rows.Next() {
		var i GetLeastRecentlyUsedCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.CacheKey,
			&i.CacheType,
			&i.ReportID,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCacheMiss = `-- name: IncrementCacheMiss :exec
UPDATE report_cache
SET
    miss_count = miss_count + 1
WHERE cache_key = $1
`

func (q *Queries) IncrementCacheMiss(ctx context.Context, cacheKey string) error {
	_, err := q.db.Exec(ctx, incrementCacheMiss, cacheKey)
	return err
}

const updateCacheAccess = `-- name: UpdateCacheAccess :exec
UPDATE report_cache
SET
    last_accessed_at = NOW(),
    access_count = access_count + 1,
    hit_count = hit_count + 1
WHERE cache_key = $1
`

func (q *Queries) UpdateCacheAccess(ctx context.Context, cacheKey string) error {
	_, err := q.db.Exec(ctx, updateCacheAccess, cacheKey)
	return err
}
