// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldReportRuns = `-- name: CleanupOldReportRuns :exec
DELETE FROM report_runs
WHERE run_at < $1 AND status IN ('completed', 'failed', 'cancelled', 'timeout')
`

func (q *Queries) CleanupOldReportRuns(ctx context.Context, runAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, cleanupOldReportRuns, runAt)
	return err
}

const createReportRun = `-- name: CreateReportRun :one

INSERT INTO report_runs (
    report_id,
    report_version,
    run_by,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
`

type CreateReportRunParams struct {
	ReportID      pgtype.UUID `db:"report_id" json:"report_id"`
	ReportVersion int32       `db:"report_version" json:"report_version"`
	RunBy         pgtype.UUID `db:"run_by" json:"run_by"`
	Parameters    []byte      `db:"parameters" json:"parameters"`
	ExecutionPlan pgtype.Text `db:"execution_plan" json:"execution_plan"`
	CacheKey      pgtype.Text `db:"cache_key" json:"cache_key"`
	TriggeredBy   pgtype.Text `db:"triggered_by" json:"triggered_by"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
}

// =============================================================================
// Report Runs Queries - InsightViewer Service
// =============================================================================
func (q *Queries) CreateReportRun(ctx context.Context, arg CreateReportRunParams) (ReportRun, error) {
	row := q.db.QueryRow(ctx, createReportRun,
		arg.ReportID,
		arg.ReportVersion,
		arg.RunBy,
		arg.Parameters,
		arg.ExecutionPlan,
		arg.CacheKey,
		arg.TriggeredBy,
		arg.Metadata,
	)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ReportVersion,
		&i.RunBy,
		&i.RunAt,
		&i.CompletedAt,
		&i.Status,
		&i.DurationMs,
		&i.RowCount,
		&i.ErrorMessage,
		&i.Parameters,
		&i.ExecutionPlan,
		&i.CacheKey,
		&i.TriggeredBy,
		&i.Metadata,
	)
	return i, err
}

const getReportRunByID = `-- name: GetReportRunByID :one
SELECT
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
FROM report_runs
WHERE id = $1
`

func (q *Queries) GetReportRunByID(ctx context.Context, id pgtype.UUID) (ReportRun, error) {
	row := q.db.QueryRow(ctx, getReportRunByID, id)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ReportVersion,
		&i.RunBy,
		&i.RunAt,
		&i.CompletedAt,
		&i.Status,
		&i.DurationMs,
		&i.RowCount,
		&i.ErrorMessage,
		&i.Parameters,
		&i.ExecutionPlan,
		&i.CacheKey,
		&i.TriggeredBy,
		&i.Metadata,
	)
	return i, err
}

const getReportRunStatistics = `-- name: GetReportRunStatistics :one
SELECT
    COUNT(*) as total_runs,
    COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_runs,
    COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_runs,
    COUNT(CASE WHEN status = 'running' THEN 1 END) as running_runs,
    AVG(duration_ms) as avg_duration_ms,
    MAX(duration_ms) as max_duration_ms,
    MIN(duration_ms) as min_duration_ms
FROM report_runs
WHERE report_id = $1 AND run_at >= $2
`

type GetReportRunStatisticsParams struct {
	ReportID pgtype.UUID        `db:"report_id" json:"report_id"`
	RunAt    pgtype.Timestamptz `db:"run_at" json:"run_at"`
}

type GetReportRunStatisticsRow struct {
	TotalRuns     int64       `db:"total_runs" json:"total_runs"`
	CompletedRuns int64       `db:"completed_runs" json:"completed_runs"`
	FailedRuns    int64       `db:"failed_runs" json:"failed_runs"`
	RunningRuns   int64       `db:"running_runs" json:"running_runs"`
	AvgDurationMs float64     `db:"avg_duration_ms" json:"avg_duration_ms"`
	MaxDurationMs interface{} `db:"max_duration_ms" json:"max_duration_ms"`
	MinDurationMs interface{} `db:"min_duration_ms" json:"min_duration_ms"`
}

func (q *Queries) GetReportRunStatistics(ctx context.Context, arg GetReportRunStatisticsParams) (GetReportRunStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getReportRunStatistics, arg.ReportID, arg.RunAt)
	var i GetReportRunStatisticsRow
	err := row.Scan(
		&i.TotalRuns,
		&i.CompletedRuns,
		&i.FailedRuns,
		&i.RunningRuns,
		&i.AvgDurationMs,
		&i.MaxDurationMs,
		&i.MinDurationMs,
	)
	return i, err
}

const getReportRunsByReportID = `-- name: GetReportRunsByReportID :many
SELECT
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
FROM report_runs
WHERE report_id = $1
ORDER BY run_at DESC
LIMIT $2 OFFSET $3
`

type GetReportRunsByReportIDParams struct {
	ReportID pgtype.UUID `db:"report_id" json:"report_id"`
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetReportRunsByReportID(ctx context.Context, arg GetReportRunsByReportIDParams) ([]ReportRun, error) {
	rows, err := q.db.Query(ctx, getReportRunsByReportID, arg.ReportID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRun{}
	for rows.Next() {
		var i ReportRun
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ReportVersion,
			&i.RunBy,
			&i.RunAt,
			&i.CompletedAt,
			&i.Status,
			&i.DurationMs,
			&i.RowCount,
			&i.ErrorMessage,
			&i.Parameters,
			&i.ExecutionPlan,
			&i.CacheKey,
			&i.TriggeredBy,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportRunsByUser = `-- name: GetReportRunsByUser :many
SELECT
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
FROM report_runs
WHERE run_by = $1
ORDER BY run_at DESC
LIMIT $2 OFFSET $3
`

type GetReportRunsByUserParams struct {
	RunBy  pgtype.UUID `db:"run_by" json:"run_by"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetReportRunsByUser(ctx context.Context, arg GetReportRunsByUserParams) ([]ReportRun, error) {
	rows, err := q.db.Query(ctx, getReportRunsByUser, arg.RunBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRun{}
	for rows.Next() {
		var i ReportRun
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ReportVersion,
			&i.RunBy,
			&i.RunAt,
			&i.CompletedAt,
			&i.Status,
			&i.DurationMs,
			&i.RowCount,
			&i.ErrorMessage,
			&i.Parameters,
			&i.ExecutionPlan,
			&i.CacheKey,
			&i.TriggeredBy,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportRunsWithStatus = `-- name: GetReportRunsWithStatus :many
SELECT
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
FROM report_runs
WHERE status = $1
ORDER BY run_at DESC
LIMIT $2 OFFSET $3
`

type GetReportRunsWithStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetReportRunsWithStatus(ctx context.Context, arg GetReportRunsWithStatusParams) ([]ReportRun, error) {
	rows, err := q.db.Query(ctx, getReportRunsWithStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRun{}
	for rows.Next() {
		var i ReportRun
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ReportVersion,
			&i.RunBy,
			&i.RunAt,
			&i.CompletedAt,
			&i.Status,
			&i.DurationMs,
			&i.RowCount,
			&i.ErrorMessage,
			&i.Parameters,
			&i.ExecutionPlan,
			&i.CacheKey,
			&i.TriggeredBy,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningReports = `-- name: GetRunningReports :many
SELECT
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
FROM report_runs
WHERE status = 'running'
ORDER BY run_at ASC
`

func (q *Queries) GetRunningReports(ctx context.Context) ([]ReportRun, error) {
	rows, err := q.db.Query(ctx, getRunningReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRun{}
	for rows.Next() {
		var i ReportRun
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ReportVersion,
			&i.RunBy,
			&i.RunAt,
			&i.CompletedAt,
			&i.Status,
			&i.DurationMs,
			&i.RowCount,
			&i.ErrorMessage,
			&i.Parameters,
			&i.ExecutionPlan,
			&i.CacheKey,
			&i.TriggeredBy,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportRunStatus = `-- name: UpdateReportRunStatus :one
UPDATE report_runs
SET
    status = $2,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled', 'timeout') THEN NOW() ELSE completed_at END,
    duration_ms = CASE WHEN $2 IN ('completed', 'failed', 'cancelled', 'timeout') THEN EXTRACT(EPOCH FROM (NOW() - run_at)) * 1000 ELSE duration_ms END,
    row_count = COALESCE($3, row_count),
    error_message = COALESCE($4, error_message)
WHERE id = $1
RETURNING
    id,
    report_id,
    report_version,
    run_by,
    run_at,
    completed_at,
    status,
    duration_ms,
    row_count,
    error_message,
    parameters,
    execution_plan,
    cache_key,
    triggered_by,
    metadata
`

type UpdateReportRunStatusParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Status       string      `db:"status" json:"status"`
	RowCount     pgtype.Int4 `db:"row_count" json:"row_count"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

func (q *Queries) UpdateReportRunStatus(ctx context.Context, arg UpdateReportRunStatusParams) (ReportRun, error) {
	row := q.db.QueryRow(ctx, updateReportRunStatus,
		arg.ID,
		arg.Status,
		arg.RowCount,
		arg.ErrorMessage,
	)
	var i ReportRun
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ReportVersion,
		&i.RunBy,
		&i.RunAt,
		&i.CompletedAt,
		&i.Status,
		&i.DurationMs,
		&i.RowCount,
		&i.ErrorMessage,
		&i.Parameters,
		&i.ExecutionPlan,
		&i.CacheKey,
		&i.TriggeredBy,
		&i.Metadata,
	)
	return i, err
}
