// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/proto/user.proto

package userconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	user "p9e.in/ugcl/identity/api/v2/user"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.api.v2.user.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/user.api.v2.user.UserService/ListUsers"
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/user.api.v2.user.UserService/GetUser"
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/user.api.v2.user.UserService/CreateUser"
	// UserServiceUpdateUserProcedure is the fully-qualified name of the UserService's UpdateUser RPC.
	UserServiceUpdateUserProcedure = "/user.api.v2.user.UserService/UpdateUser"
	// UserServiceDeleteUserProcedure is the fully-qualified name of the UserService's DeleteUser RPC.
	UserServiceDeleteUserProcedure = "/user.api.v2.user.UserService/DeleteUser"
	// UserServiceAssignRoleToUserProcedure is the fully-qualified name of the UserService's
	// AssignRoleToUser RPC.
	UserServiceAssignRoleToUserProcedure = "/user.api.v2.user.UserService/AssignRoleToUser"
	// UserServiceRevokeRoleFromUserProcedure is the fully-qualified name of the UserService's
	// RevokeRoleFromUser RPC.
	UserServiceRevokeRoleFromUserProcedure = "/user.api.v2.user.UserService/RevokeRoleFromUser"
)

// UserServiceClient is a client for the user.api.v2.user.UserService service.
type UserServiceClient interface {
	ListUsers(context.Context, *connect.Request[user.ListUsersRequest]) (*connect.Response[user.ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[user.UserIdentifier]) (*connect.Response[user.User], error)
	CreateUser(context.Context, *connect.Request[user.CreateUserRequest]) (*connect.Response[user.UserIdentifier], error)
	UpdateUser(context.Context, *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.UserIdentifier], error)
	DeleteUser(context.Context, *connect.Request[user.DeleteUserRequest]) (*connect.Response[user.DeleteUserResponse], error)
	AssignRoleToUser(context.Context, *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error)
	RevokeRoleFromUser(context.Context, *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewUserServiceClient constructs a client for the user.api.v2.user.UserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := user.File_identity_proto_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		listUsers: connect.NewClient[user.ListUsersRequest, user.ListUsersResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[user.UserIdentifier, user.User](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[user.CreateUserRequest, user.UserIdentifier](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[user.UpdateUserRequest, user.UserIdentifier](
			httpClient,
			baseURL+UserServiceUpdateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[user.DeleteUserRequest, user.DeleteUserResponse](
			httpClient,
			baseURL+UserServiceDeleteUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		assignRoleToUser: connect.NewClient[user.AssignRoleRequest, emptypb.Empty](
			httpClient,
			baseURL+UserServiceAssignRoleToUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("AssignRoleToUser")),
			connect.WithClientOptions(opts...),
		),
		revokeRoleFromUser: connect.NewClient[user.AssignRoleRequest, emptypb.Empty](
			httpClient,
			baseURL+UserServiceRevokeRoleFromUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("RevokeRoleFromUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	listUsers          *connect.Client[user.ListUsersRequest, user.ListUsersResponse]
	getUser            *connect.Client[user.UserIdentifier, user.User]
	createUser         *connect.Client[user.CreateUserRequest, user.UserIdentifier]
	updateUser         *connect.Client[user.UpdateUserRequest, user.UserIdentifier]
	deleteUser         *connect.Client[user.DeleteUserRequest, user.DeleteUserResponse]
	assignRoleToUser   *connect.Client[user.AssignRoleRequest, emptypb.Empty]
	revokeRoleFromUser *connect.Client[user.AssignRoleRequest, emptypb.Empty]
}

// ListUsers calls user.api.v2.user.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[user.ListUsersRequest]) (*connect.Response[user.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// GetUser calls user.api.v2.user.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[user.UserIdentifier]) (*connect.Response[user.User], error) {
	return c.getUser.CallUnary(ctx, req)
}

// CreateUser calls user.api.v2.user.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[user.CreateUserRequest]) (*connect.Response[user.UserIdentifier], error) {
	return c.createUser.CallUnary(ctx, req)
}

// UpdateUser calls user.api.v2.user.UserService.UpdateUser.
func (c *userServiceClient) UpdateUser(ctx context.Context, req *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.UserIdentifier], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls user.api.v2.user.UserService.DeleteUser.
func (c *userServiceClient) DeleteUser(ctx context.Context, req *connect.Request[user.DeleteUserRequest]) (*connect.Response[user.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// AssignRoleToUser calls user.api.v2.user.UserService.AssignRoleToUser.
func (c *userServiceClient) AssignRoleToUser(ctx context.Context, req *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.assignRoleToUser.CallUnary(ctx, req)
}

// RevokeRoleFromUser calls user.api.v2.user.UserService.RevokeRoleFromUser.
func (c *userServiceClient) RevokeRoleFromUser(ctx context.Context, req *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revokeRoleFromUser.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the user.api.v2.user.UserService service.
type UserServiceHandler interface {
	ListUsers(context.Context, *connect.Request[user.ListUsersRequest]) (*connect.Response[user.ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[user.UserIdentifier]) (*connect.Response[user.User], error)
	CreateUser(context.Context, *connect.Request[user.CreateUserRequest]) (*connect.Response[user.UserIdentifier], error)
	UpdateUser(context.Context, *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.UserIdentifier], error)
	DeleteUser(context.Context, *connect.Request[user.DeleteUserRequest]) (*connect.Response[user.DeleteUserResponse], error)
	AssignRoleToUser(context.Context, *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error)
	RevokeRoleFromUser(context.Context, *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := user.File_identity_proto_user_proto.Services().ByName("UserService").Methods()
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(userServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDeleteUserHandler := connect.NewUnaryHandler(
		UserServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceAssignRoleToUserHandler := connect.NewUnaryHandler(
		UserServiceAssignRoleToUserProcedure,
		svc.AssignRoleToUser,
		connect.WithSchema(userServiceMethods.ByName("AssignRoleToUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceRevokeRoleFromUserHandler := connect.NewUnaryHandler(
		UserServiceRevokeRoleFromUserProcedure,
		svc.RevokeRoleFromUser,
		connect.WithSchema(userServiceMethods.ByName("RevokeRoleFromUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.api.v2.user.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProcedure:
			userServiceUpdateUserHandler.ServeHTTP(w, r)
		case UserServiceDeleteUserProcedure:
			userServiceDeleteUserHandler.ServeHTTP(w, r)
		case UserServiceAssignRoleToUserProcedure:
			userServiceAssignRoleToUserHandler.ServeHTTP(w, r)
		case UserServiceRevokeRoleFromUserProcedure:
			userServiceRevokeRoleFromUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[user.ListUsersRequest]) (*connect.Response[user.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.ListUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[user.UserIdentifier]) (*connect.Response[user.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[user.CreateUserRequest]) (*connect.Response[user.UserIdentifier], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUser(context.Context, *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.UserIdentifier], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.UpdateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteUser(context.Context, *connect.Request[user.DeleteUserRequest]) (*connect.Response[user.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.DeleteUser is not implemented"))
}

func (UnimplementedUserServiceHandler) AssignRoleToUser(context.Context, *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.AssignRoleToUser is not implemented"))
}

func (UnimplementedUserServiceHandler) RevokeRoleFromUser(context.Context, *connect.Request[user.AssignRoleRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.api.v2.user.UserService.RevokeRoleFromUser is not implemented"))
}
